import React,{useEffect,useMemo,useRef,useState} from 'react';
import {getPublicExamEvent,registerExamCandidate,getExamIntroduction,startExamAttempt,getAttemptQuestions,saveAttemptAnswer,getAttemptSubmissionSummary,submitExamAttempt} from './eventApi';

const FALLBACK_EVENT_ID=import.meta.env.VITE_DEFAULT_EVENT_ID||'';
const TOEIC_OPTIONS=[
  ['NEVER_STUDIED','Chưa học'],
  ['STUDIED_NOT_TESTED','Đã học nhưng chưa thi'],
  ['TOOK_TOEIC','Đã thi TOEIC'],
  ['OTHER_CERTIFICATE','Đã học/thi chứng chỉ khác'],
];
const EMPTY_FORM={fullName:'',phone:'',email:'',birthYear:'',toeicExperience:'',privacyConsent:false,marketingConsent:false};

const Icon=({children,className=''})=><span aria-hidden="true" className={`material-symbols-outlined ${className}`}>{children}</span>;
const textOnly=html=>String(html||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim();
const displayExamTitle=value=>String(value||'').replace(/^\s*\[[^\]]+\]\s*/,'').replace(/[_-]{2,}/g,' ').trim();
const minutes=seconds=>Math.max(1,Math.ceil(Number(seconds||0)/60));
const formatDeadline=value=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
function skillMeta(title=''){
  const normalized=title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  if(normalized.includes('listening')||normalized.includes('nghe'))return {icon:'headphones',tone:'listening',hint:'Nghe hiểu'};
  if(normalized.includes('reading')||normalized.includes('doc'))return {icon:'menu_book',tone:'reading',hint:'Đọc hiểu'};
  if(normalized.includes('speaking')||normalized.includes('noi'))return {icon:'mic',tone:'speaking',hint:'Phản xạ nói'};
  if(normalized.includes('writing')||normalized.includes('viet'))return {icon:'edit_note',tone:'writing',hint:'Viết tiếng Anh'};
  return {icon:'quiz',tone:'other',hint:'Phần thi'};
}
function eventIdFromLocation(){const match=window.location.pathname.match(/\/events\/([0-9a-f-]+)/i);return match?.[1]||new URLSearchParams(window.location.search).get('eventId')||FALLBACK_EVENT_ID;}

export default function App(){
  const eventId=useMemo(eventIdFromLocation,[]);
  const isIntroduction=window.location.pathname.endsWith('/introduction');
  const isAttemptReady=/\/attempts\/[0-9a-f-]+$/i.test(window.location.pathname);
  const [event,setEvent]=useState(null);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');
  useEffect(()=>{if(!eventId){setLoadError('Đường dẫn kỳ thi không hợp lệ.');setLoading(false);return undefined;}const controller=new AbortController();let active=true;setLoading(true);setLoadError('');getPublicExamEvent(eventId,{signal:controller.signal}).then(data=>{if(active)setEvent(data);}).catch(error=>{if(active&&error.name!=='AbortError')setLoadError(error.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[eventId]);
  if(loading)return <StateScreen icon="progress_activity" title="Đang tải kỳ thi" description="Vui lòng chờ trong giây lát..." loading/>;
  if(loadError||!event)return <StateScreen icon="error" title="Không thể mở kỳ thi" description={loadError||'Kỳ thi không tồn tại.'}/>;
  if(isAttemptReady)return <ExamTakingPage event={event}/>;
  if(isIntroduction)return <IntroductionPage event={event}/>;
  return <LandingPage event={event}/>;
}

function IntroductionPage({event}){
  const [intro,setIntro]=useState(null);const [error,setError]=useState('');const [audioState,setAudioState]=useState('idle');const [starting,setStarting]=useState(false);
  const saved=useMemo(()=>{try{return JSON.parse(sessionStorage.getItem(`exam-registration:${event.id}`)||'null');}catch{return null;}},[event.id]);
  useEffect(()=>{if(!saved?.candidateToken){setError('Phiên đăng ký cũ chưa có mã xác thực. Vui lòng quay lại và gửi thông tin một lần nữa.');return;}let active=true;getExamIntroduction(event.id,saved.candidateToken).then(data=>{if(active)setIntro(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[event.id,saved?.candidateToken]);
  const playAudioTest=async()=>{if(audioState==='playing')return;setAudioState('playing');try{const AudioContext=window.AudioContext||window.webkitAudioContext;const context=new AudioContext();await context.resume();const gain=context.createGain();const oscillator=context.createOscillator();gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.16,context.currentTime+.05);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+1.15);oscillator.frequency.setValueAtTime(660,context.currentTime);oscillator.frequency.setValueAtTime(880,context.currentTime+.55);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+1.2);await new Promise(resolve=>{oscillator.onended=resolve;});await context.close();setAudioState('passed');}catch{setAudioState('error');}};
  const begin=async()=>{if(!intro||starting||(intro.requirements.requiresAudio&&audioState!=='passed'))return;setStarting(true);setError('');try{const attempt=await startExamAttempt(event.id,saved.candidateToken,{audioConfirmed:audioState==='passed'});sessionStorage.setItem(`exam-attempt:${event.id}`,JSON.stringify(attempt));window.location.assign(`/events/${event.id}/attempts/${attempt.attemptId}`);}catch(e){setError(e.message);}finally{setStarting(false);}};
  if(error&&!intro)return <main className="mobile-shell"><StateScreen icon="lock" title="Cần đăng ký lại" description={error}/><button className="intro-recover" type="button" onClick={()=>window.location.replace(`/events/${event.id}`)}>Quay lại nhập thông tin</button></main>;
  if(!intro)return <StateScreen icon="progress_activity" title="Đang chuẩn bị" description="Đang kiểm tra thông tin đăng ký..." loading/>;
  const {candidate,requirements}=intro;const canStart=!requirements.requiresAudio||audioState==='passed';
  const ready=canStart&&event.canEnter;
  const readinessLabel=!event.canEnter?'Không khả dụng':requirements.requiresAudio&&audioState!=='passed'?'Chưa kiểm tra':'Sẵn sàng';
  return <main className="mobile-shell prep-app"><header className="prep-header"><button type="button" onClick={()=>window.location.assign(`/events/${event.id}`)} aria-label="Quay lại"><Icon>arrow_back</Icon></button><img src="/IIG_logo.webp" alt="IIG Việt Nam"/><div><strong>Chuẩn bị làm bài</strong><span>IIG English Quick Test</span></div><em className={ready?'is-ready':'is-pending'}><i/>{readinessLabel}</em></header>
    <div className="prep-content"><section className="prep-campaign" style={{backgroundImage:`linear-gradient(to top,rgba(3,38,28,.86),rgba(3,38,28,.12)),url("${event.bannerUrl||'/workshop-hero-v2.png'}")`}}><div><span><i/>Campus Workshop</span><em>Miễn phí</em></div><p>IIG Việt Nam • English Quick Test</p><strong>Đánh giá năng lực tiếng Anh</strong></section>
      <section className="prep-welcome"><div className="prep-person"><span>{candidate.fullName.trim().charAt(0).toUpperCase()}<i><Icon>check</Icon></i></span><div><h1>Chào {candidate.fullName.split(/\s+/).slice(-1)[0]} ✨</h1><p>Thông tin đăng ký đã được ghi nhận</p></div></div></section>
      <section className="prep-sheet"><div className="prep-exam"><div className="prep-exam-label"><span><i/>Thông tin bài kiểm tra</span></div><h2>{displayExamTitle(event.exam.title).replace(/\s*[—-]\s*\d+\s*Questions?$/i,'')}</h2><p>Đánh giá nhanh {event.exam.parts.length} kỹ năng tiếng Anh</p><div><b><Icon>assignment</Icon><strong>{event.exam.totalQuestions} câu</strong><small>Tổng số câu</small></b><b><Icon>schedule</Icon><strong>{minutes(event.exam.durationSeconds)} phút</strong><small>Thời gian</small></b><b><Icon>view_list</Icon><strong>{event.exam.parts.length} phần</strong><small>Kỹ năng</small></b></div></div>
        <div className="prep-section"><div className="prep-section-head"><h3>Nội dung bài kiểm tra</h3><span>{event.exam.parts.length} kỹ năng toàn diện</span></div><div className="prep-parts">{event.exam.parts.map((part,index)=><SkillRow key={part.id||index} part={part}/>)}</div></div>
        {requirements.requiresAudio&&<div className="prep-section"><h3>Kiểm tra âm thanh</h3><div className={`prep-audio audio-${audioState}`}><span><Icon>{audioState==='passed'?'check':'headphones'}</Icon></span><div><strong>{audioState==='passed'?'Âm thanh đã sẵn sàng':'Phát thử âm thanh'}</strong><small>{audioState==='playing'?'Đang phát âm thanh mẫu...':'Đảm bảo bạn có thể nghe trước khi bắt đầu'}</small></div><em>{audioState==='passed'?'Sẵn sàng':audioState==='playing'?'Đang phát':'Chưa kiểm tra'}</em><button type="button" onClick={playAudioTest} disabled={audioState==='playing'}>{audioState==='passed'?'Phát lại':audioState==='playing'?'Đang phát':'Phát thử'}</button></div>{audioState==='error'&&<p className="device-error">Không thể phát âm thanh. Hãy kiểm tra âm lượng và thử lại.</p>}</div>}
        <div className="prep-section prep-notes"><h3><Icon>fact_check</Icon>Quy chế &amp; lưu ý làm bài</h3><ul><li><Icon>check_circle</Icon>Sử dụng tai nghe để nghe phần Listening rõ ràng.</li><li><Icon>check_circle</Icon>Giữ pin và kết nối mạng ổn định trong suốt bài thi.</li><li><Icon>check_circle</Icon>Đáp án được tự động lưu ngay khi lựa chọn.</li><li><Icon>check_circle</Icon>Nộp bài để nhận kết quả và phân tích điểm ngay.</li></ul></div>
      </section>
      <div className="prep-accreditation"><Icon>verified</Icon><span>IIG Việt Nam • Đơn vị tổ chức bài đánh giá</span></div>
      {error&&<div className="intro-error"><Icon>error</Icon>{error}</div>}
    </div>
    <footer className="prep-bottom"><div><button className="prep-back" type="button" onClick={()=>window.location.assign(`/events/${event.id}`)}><Icon>arrow_back</Icon>Quay lại</button><button className="primary-cta" type="button" disabled={!ready||starting} onClick={begin}>{starting?'Đang chuẩn bị...':canStart?'Bắt đầu làm bài thi ngay':'Kiểm tra âm thanh trước'} <Icon>{starting?'progress_activity':canStart?'arrow_forward':'headphones'}</Icon></button></div></footer>
  </main>;
}

function MiniMetric({icon,text,amber=false}){return <div className={amber?'amber':''}><span><Icon>{icon}</Icon></span><b>{text}</b></div>}
function SkillRow({part}){const meta=skillMeta(part.title);const descriptions={listening:'Nghe hội thoại và bài nói ngắn',reading:'Đọc hiểu nội dung và chọn đáp án',speaking:'Ghi âm câu trả lời',writing:'Viết câu trả lời',other:'Hoàn thành phần thi'};const labels={listening:'Audio',reading:'Đọc hiểu',speaking:'Ghi âm',writing:'Tự luận',other:'Phần thi'};return <div className={`prep-part prep-part-${meta.tone}`}><div className="prep-part-main"><span><Icon>{meta.icon}</Icon></span><div><div className="prep-part-title"><strong>{part.title} Module</strong><b>{labels[meta.tone]}</b></div><small>{descriptions[meta.tone]}</small></div><em>{part.questionCount} câu</em></div></div>}
function safeMarkup(html){
  if(!html)return {__html:''};
  const documentNode=new DOMParser().parseFromString(String(html),'text/html');
  documentNode.querySelectorAll('script,style,iframe,object,embed,form,input,button').forEach(node=>node.remove());
  documentNode.body.querySelectorAll('*').forEach(node=>[...node.attributes].forEach(attribute=>{
    const name=attribute.name.toLowerCase();const value=attribute.value.trim().toLowerCase();
    if(name.startsWith('on')||name==='style'||value.startsWith('javascript:'))node.removeAttribute(attribute.name);
  }));
  return {__html:documentNode.body.innerHTML};
}

function formatClock(seconds){const safe=Math.max(0,Number(seconds)||0);return `${String(Math.floor(safe/60)).padStart(2,'0')}:${String(safe%60).padStart(2,'0')}`;}
function formatExamClock(seconds){const safe=Math.max(0,Math.floor(Number(seconds)||0));const hours=Math.floor(safe/3600);const minutes=Math.floor((safe%3600)/60);const secs=safe%60;return `${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`;}

function QuestionAudio({src}){
  const ref=useRef(null);const [playing,setPlaying]=useState(false);const [time,setTime]=useState(0);const [duration,setDuration]=useState(0);const [speed,setSpeed]=useState(1);const [muted,setMuted]=useState(false);
  useEffect(()=>{setPlaying(false);setTime(0);setDuration(0);setSpeed(1);setMuted(false);},[src]);
  const toggle=async()=>{const audio=ref.current;if(!audio)return;if(audio.paused)await audio.play();else audio.pause();};
  const cycleSpeed=()=>{const next=speed===1?1.25:speed===1.25?1.5:1;setSpeed(next);if(ref.current)ref.current.playbackRate=next;};
  const seek=event=>{const value=Number(event.target.value);if(ref.current)ref.current.currentTime=value;setTime(value);};
  return <div className="exam-audio"><div className="exam-audio-meta"><span><Icon>headphones</Icon></span><div><strong>Audio câu hỏi</strong><small>Nhấn phát để bắt đầu nghe</small></div><button type="button" onClick={cycleSpeed}>{speed.toFixed(speed===1?1:2).replace(/0$/,'')}x</button></div><div className="exam-audio-controls"><button className="audio-play" type="button" onClick={toggle} aria-label={playing?'Tạm dừng':'Phát âm thanh'}><Icon>{playing?'pause':'play_arrow'}</Icon></button><div><div className="audio-wave" aria-hidden="true">{[8,14,20,16,18,12,9,13,18,20,12,16,9,14,8].map((height,index)=><i key={index} className={duration&&index/15<=time/duration?'played':''} style={{height}}/>)}</div><input aria-label="Tiến độ audio" type="range" min="0" max={duration||0} step="0.1" value={time} onChange={seek}/><p><span>{formatClock(Math.floor(time))}</span><span>{formatClock(Math.floor(duration))}</span></p></div><button className="audio-volume" type="button" onClick={()=>{setMuted(value=>{if(ref.current)ref.current.muted=!value;return !value;});}} aria-label={muted?'Bật âm thanh':'Tắt âm thanh'}><Icon>{muted?'volume_off':'volume_up'}</Icon></button></div><audio ref={ref} src={src} preload="metadata" onLoadedMetadata={event=>setDuration(event.currentTarget.duration||0)} onTimeUpdate={event=>setTime(event.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/></div>;
}

function ExamTakingPage({event}){
  const saved=useMemo(()=>{try{const attemptId=window.location.pathname.match(/\/attempts\/([0-9a-f-]+)/i)?.[1];const resultAccess=attemptId?JSON.parse(localStorage.getItem(`exam-result:${event.id}:${attemptId}`)||'null'):null;if(resultAccess?.attemptToken)return resultAccess;const stored=JSON.parse(sessionStorage.getItem(`exam-attempt:${event.id}`)||'null');if(stored)return stored;if(import.meta.env.DEV&&attemptId===import.meta.env.VITE_PREVIEW_ATTEMPT_ID&&import.meta.env.VITE_PREVIEW_ATTEMPT_TOKEN)return {attemptId,attemptToken:import.meta.env.VITE_PREVIEW_ATTEMPT_TOKEN};return null;}catch{return null;}},[event.id]);
  const [delivery,setDelivery]=useState(null);const [error,setError]=useState('');const [current,setCurrent]=useState(0);const [answers,setAnswers]=useState({});const [flagged,setFlagged]=useState({});const [saveStates,setSaveStates]=useState({});const [showGrid,setShowGrid]=useState(false);const [remaining,setRemaining]=useState(0);const [submitSummary,setSubmitSummary]=useState(null);const [submitResult,setSubmitResult]=useState(null);const [submitting,setSubmitting]=useState(false);const [submitError,setSubmitError]=useState('');
  const saveTimers=useRef(new Map());const saveQueues=useRef(new Map());const saveVersions=useRef(new Map());const hasUnsaved=useRef(false);const autoSubmitTriggered=useRef(false);const autoSubmitRetryTimer=useRef(null);const [online,setOnline]=useState(navigator.onLine);const backupKey=`exam-answer-backup:${saved?.attemptId||'unknown'}`;
  const readBackup=()=>{try{return JSON.parse(localStorage.getItem(backupKey)||'{}');}catch{return {};}};
  const refreshUnsaved=backup=>{hasUnsaved.current=Object.values(backup||readBackup()).some(value=>value?.dirty);};
  const writeBackup=(id,value)=>{const backup=readBackup();backup[id]=value;try{localStorage.setItem(backupKey,JSON.stringify(backup));}catch{}refreshUnsaved(backup);};
  const persistAnswer=(id,payload,version)=>{setSaveStates(value=>({...value,[id]:'saving'}));const previous=saveQueues.current.get(id)||Promise.resolve();const queued=previous.catch(()=>{}).then(()=>saveAttemptAnswer(event.id,saved.attemptId,id,saved.attemptToken,{selectedOptionKey:payload.selectedOptionKey||null,flagged:payload.flagged===true}));saveQueues.current.set(id,queued);queued.then(result=>{if(saveVersions.current.get(id)===version)setSaveStates(value=>({...value,[id]:'saved'}));writeBackup(id,{selectedOptionKey:result.selectedOptionKey||'',flagged:result.flagged,dirty:false,savedAt:result.savedAt});}).catch(saveError=>{if(saveVersions.current.get(id)===version)setSaveStates(value=>({...value,[id]:'error'}));hasUnsaved.current=true;if(saveError?.code==='ATTEMPT_EXPIRED'||saveError?.code==='ATTEMPT_NOT_IN_PROGRESS')setRemaining(0);});return queued;};
  const flushDirtyAnswers=()=>{if(!saved?.attemptId||!saved?.attemptToken||!navigator.onLine)return Promise.resolve([]);const pending=[];const backup=readBackup();for(const [id,payload] of Object.entries(backup)){if(!payload?.dirty)continue;const timer=saveTimers.current.get(id);if(timer)window.clearTimeout(timer);saveTimers.current.delete(id);const version=(saveVersions.current.get(id)||0)+1;saveVersions.current.set(id,version);pending.push(persistAnswer(id,payload,version));}return Promise.allSettled(pending);};
  const finalizeSubmission=async({automatic=false}={})=>{if(!navigator.onLine){setSubmitError(automatic?'Hết giờ. Bài sẽ tự nộp ngay khi có kết nối mạng.':'Bạn đang mất kết nối. Hãy kết nối mạng trước khi nộp bài.');autoSubmitTriggered.current=false;return false;}setSubmitting(true);setSubmitError('');try{await flushDirtyAnswers();await Promise.allSettled([...saveQueues.current.values()]);if(hasUnsaved.current&&!automatic)throw new Error('Vẫn còn câu trả lời chưa lưu được. Vui lòng thử lại.');const result=await submitExamAttempt(event.id,saved.attemptId,saved.attemptToken);if(autoSubmitRetryTimer.current)window.clearTimeout(autoSubmitRetryTimer.current);localStorage.removeItem(backupKey);hasUnsaved.current=false;if(result.resultToken)localStorage.setItem(`exam-result:${event.id}:${saved.attemptId}`,JSON.stringify({attemptId:saved.attemptId,attemptToken:result.resultToken,expiresAt:result.resultTokenExpiresAt}));setSubmitResult(result);setSubmitSummary(null);return true;}catch(e){setSubmitError(e.message||(automatic?'Chưa thể tự nộp bài. Hệ thống sẽ tự thử lại.':'Không thể nộp bài. Vui lòng thử lại.'));if(automatic&&navigator.onLine&&!autoSubmitRetryTimer.current)autoSubmitRetryTimer.current=window.setTimeout(()=>{autoSubmitRetryTimer.current=null;autoSubmitTriggered.current=false;setRemaining(0);finalizeSubmission({automatic:true});},2500);return false;}finally{setSubmitting(false);}};
  useEffect(()=>{if(!saved?.attemptId||!saved?.attemptToken){setError('Không tìm thấy phiên làm bài. Vui lòng quay lại màn chuẩn bị.');return;}let active=true;getAttemptQuestions(event.id,saved.attemptId,saved.attemptToken).then(data=>{if(active){const restoredAnswers={};const restoredFlags={};for(const item of (data.parts||[]).flatMap(part=>part.questions||[])){if(item.selectedOption)restoredAnswers[item.id]=item.selectedOption;if(item.flagged)restoredFlags[item.id]=true;}const backup=readBackup();for(const [id,value] of Object.entries(backup)){if(value?.dirty){restoredAnswers[id]=value.selectedOptionKey||'';restoredFlags[id]=value.flagged===true;}}refreshUnsaved(backup);setAnswers(restoredAnswers);setFlagged(restoredFlags);setDelivery(data);setRemaining(data.attempt.remainingSeconds);if(navigator.onLine)window.setTimeout(flushDirtyAnswers,0);}}).catch(async e=>{if(!active)return;if(e.code==='ATTEMPT_NOT_IN_PROGRESS'||e.code==='ATTEMPT_EXPIRED'){try{const result=await submitExamAttempt(event.id,saved.attemptId,saved.attemptToken);if(active){localStorage.removeItem(backupKey);if(result.resultToken)localStorage.setItem(`exam-result:${event.id}:${saved.attemptId}`,JSON.stringify({attemptId:saved.attemptId,attemptToken:result.resultToken,expiresAt:result.resultTokenExpiresAt}));hasUnsaved.current=false;setSubmitResult(result);}}catch(resultError){if(active)setError(resultError.message);}}else setError(e.message);});return()=>{active=false;};},[event.id,saved?.attemptId,saved?.attemptToken,backupKey]);
  useEffect(()=>{if(!delivery)return undefined;const timer=window.setInterval(()=>setRemaining(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer);},[delivery]);
  useEffect(()=>()=>{for(const timer of saveTimers.current.values())window.clearTimeout(timer);if(autoSubmitRetryTimer.current)window.clearTimeout(autoSubmitRetryTimer.current);},[]);
  useEffect(()=>{const connected=()=>{autoSubmitTriggered.current=false;setOnline(true);flushDirtyAnswers();};const disconnected=()=>setOnline(false);window.addEventListener('online',connected);window.addEventListener('offline',disconnected);return()=>{window.removeEventListener('online',connected);window.removeEventListener('offline',disconnected);};},[event.id,saved?.attemptId,saved?.attemptToken,backupKey]);
  useEffect(()=>{if(!delivery||submitResult||submitting)return;if(remaining===1&&online)flushDirtyAnswers();if(remaining!==0||autoSubmitTriggered.current)return;autoSubmitTriggered.current=true;finalizeSubmission({automatic:true});},[remaining,online,delivery,submitResult,submitting]);
  useEffect(()=>{const warn=leaveEvent=>{if(!hasUnsaved.current)return;leaveEvent.preventDefault();leaveEvent.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
  const flat=useMemo(()=>delivery?(delivery.parts||[]).flatMap((part,partIndex)=>(part.questions||[]).map(question=>({...question,part,partIndex}))):[],[delivery]);
  if(error)return <main className="mobile-shell"><StateScreen icon="error" title="Không thể mở bài thi" description={error}/><button className="intro-recover" type="button" onClick={()=>window.location.replace(`/events/${event.id}/introduction`)}>Quay lại màn chuẩn bị</button></main>;
  if(submitResult)return <ExamCompleted event={event} result={submitResult}/>;
  if(!delivery)return <StateScreen icon="progress_activity" title="Đang tải đề thi" description="Đang chuẩn bị câu hỏi đầu tiên..." loading/>;
  if(!flat.length)return <StateScreen icon="quiz" title="Đề thi chưa có câu hỏi" description="Vui lòng liên hệ người tổ chức."/>;
  const question=flat[Math.min(current,flat.length-1)];const content=question.content||{};const selected=answers[question.id]||'';const progress=Math.round(((current+1)/flat.length)*100);const media=content.media||[];const audio=media.find(item=>item.type==='AUDIO')?.url||content.audioUrl;const video=media.find(item=>item.type==='VIDEO')?.url||content.videoUrl||null;const image=media.find(item=>item.type==='IMAGE')?.url||content.imageUrl;const groupLabel=question.group?.label||`Câu hỏi ${question.number}`;
  const queueSave=(target,selectedOptionKey,isFlagged)=>{const id=target.id;const version=(saveVersions.current.get(id)||0)+1;saveVersions.current.set(id,version);setSaveStates(value=>({...value,[id]:'pending'}));const payload={selectedOptionKey,flagged:isFlagged,dirty:true};writeBackup(id,payload);const existing=saveTimers.current.get(id);if(existing)window.clearTimeout(existing);saveTimers.current.set(id,window.setTimeout(()=>{saveTimers.current.delete(id);persistAnswer(id,payload,version);},400));};
  const choose=key=>{setAnswers(value=>({...value,[question.id]:key}));queueSave(question,key,Boolean(flagged[question.id]));};
  const clearAnswer=()=>{setAnswers(value=>({...value,[question.id]:''}));queueSave(question,'',Boolean(flagged[question.id]));};
  const toggleFlag=()=>{const next=!flagged[question.id];setFlagged(value=>({...value,[question.id]:next}));queueSave(question,selected,next);};
  const prepareSubmit=async()=>{if(!navigator.onLine){setSubmitError('Bạn đang mất kết nối. Hãy kết nối mạng trước khi nộp bài.');return;}setSubmitting(true);setSubmitError('');try{await flushDirtyAnswers();await Promise.allSettled([...saveQueues.current.values()]);if(hasUnsaved.current)throw new Error('Vẫn còn câu trả lời chưa lưu được. Vui lòng thử lại.');setSubmitSummary(await getAttemptSubmissionSummary(event.id,saved.attemptId,saved.attemptToken));}catch(e){setSubmitError(e.message||'Không thể kiểm tra bài làm.');}finally{setSubmitting(false);}};
  const confirmSubmit=()=>finalizeSubmission();
  const move=delta=>{const target=Math.max(0,Math.min(flat.length-1,current+delta));const sameParent=flat[target]?.parentQuestionId===question.parentQuestionId;setCurrent(target);window.requestAnimationFrame(()=>{if(sameParent)document.querySelector('.exam-question')?.scrollIntoView({behavior:'smooth',block:'start'});else window.scrollTo({top:0,behavior:'smooth'});});};
  const visibleContentHtml=question.part.type==='LISTENING'&&/^\s*<[^>]+>\s*audio\s+script\s*:/i.test(content.html||'')?'':content.html;
  return <main className="mobile-shell exam-app">
    <header className="exam-header"><button type="button" aria-label="Quay lại màn chuẩn bị" onClick={()=>window.location.assign(`/events/${event.id}/introduction`)}><Icon>arrow_back</Icon></button><img src="/IIG_logo.webp" alt="IIG Việt Nam"/><div className="exam-brand"><strong>Làm bài kiểm tra</strong><small>IIG English Quick Test</small></div><span><Icon>timer</Icon>{formatExamClock(remaining)}</span><em>{current+1}/{flat.length}</em></header>
    <div className="exam-progress"><i style={{width:`${progress}%`}}/></div>
    <div className="exam-body">
      <div className="exam-group-title"><span><Icon>format_list_numbered</Icon></span><strong>{groupLabel.replace(/^Câu hỏi/i,'Nhóm câu hỏi')}</strong><small>Nội dung dùng chung cho nhóm câu hỏi</small></div>
      <section className="exam-context" key={question.parentQuestionId||content.id}><header><div><strong>{question.part.type==='LISTENING'?'Nghe nội dung và trả lời câu hỏi':'Đọc nội dung và trả lời câu hỏi'}</strong><span>{content.title||'Nội dung dùng chung'}</span></div></header>
        {video&&<video className="exam-video" src={video} controls playsInline preload="metadata"/>}
        {audio&&<QuestionAudio src={audio}/>}
        {image&&<button className="exam-image" type="button" onClick={()=>window.open(image,'_blank','noopener,noreferrer')}><img src={image} alt={content.title||'Hình ảnh câu hỏi'}/><span><Icon>zoom_in</Icon>Chạm để xem lớn</span></button>}
        {visibleContentHtml&&<div className="exam-rich-content" dangerouslySetInnerHTML={safeMarkup(visibleContentHtml)}/>}
      </section>
      <section className="exam-question"><header><strong>Câu {question.number}</strong><button className={flagged[question.id]?'flagged':''} type="button" onClick={toggleFlag}><Icon>bookmark</Icon>{flagged[question.id]?'Đã đánh dấu':'Đánh dấu xem lại'}</button></header><div className="exam-prompt" dangerouslySetInnerHTML={safeMarkup(question.promptHtml)}/><div className="exam-options">{question.options.map(option=><button type="button" key={option.id||option.key} className={selected===option.key?'selected':''} onClick={()=>choose(option.key)}><span>{selected===option.key?<Icon>check</Icon>:option.key}</span><b>{option.text}</b><i/></button>)}</div>{selected&&<footer><span className={`answer-save answer-save-${saveStates[question.id]||'idle'}`}><Icon>{saveStates[question.id]==='error'?'error':saveStates[question.id]==='saving'||saveStates[question.id]==='pending'?'sync':'check_circle'}</Icon>{saveStates[question.id]==='error'?'Chưa lưu được':saveStates[question.id]==='saving'||saveStates[question.id]==='pending'?'Đang lưu...':saveStates[question.id]==='saved'?'Đã lưu':'Đã chọn đáp án'}</span><button type="button" onClick={clearAnswer}>Xóa lựa chọn</button></footer>}</section>
    </div>
    {showGrid&&<div className="question-grid-backdrop" onClick={()=>setShowGrid(false)}><section onClick={e=>e.stopPropagation()}><i className="question-grid-handle"/><header><div><strong>Danh sách câu hỏi</strong><small><b>{Object.values(answers).filter(Boolean).length}</b>/{flat.length} câu đã hoàn thành</small><span className="question-grid-progress"><i style={{width:`${Math.round((Object.values(answers).filter(Boolean).length/flat.length)*100)}%`}}/></span></div><button type="button" onClick={()=>setShowGrid(false)} aria-label="Đóng danh sách câu hỏi"><Icon>close</Icon></button></header><div>{flat.map((item,index)=><button type="button" key={item.id} aria-label={`Câu ${index+1}${answers[item.id]?', đã trả lời':''}${flagged[item.id]?', đã đánh dấu':''}`} className={`${index===current?'current ':''}${answers[item.id]?'answered ':''}${flagged[item.id]?'flagged':''}`} onClick={()=>{setCurrent(index);setShowGrid(false);}}><span>{index+1}</span>{answers[item.id]&&index!==current&&<Icon>check</Icon>}</button>)}</div><footer><span className="unanswered"><i/>Chưa làm</span><span className="answered"><i/>Đã trả lời</span><span className="viewing"><i/>Đang xem</span></footer></section></div>}
    {submitSummary&&<div className="submit-backdrop" onClick={()=>!submitting&&setSubmitSummary(null)}><section className="submit-dialog" onClick={e=>e.stopPropagation()}><div className="submit-dialog-icon"><Icon>assignment_turned_in</Icon></div><h2>Xác nhận nộp bài</h2><p>Kiểm tra lại tình trạng bài làm trước khi hoàn thành.</p><div className="submit-stats"><div><strong>{submitSummary.answeredCount}</strong><span>Đã trả lời</span></div><div className={submitSummary.unansweredCount?'warning':''}><strong>{submitSummary.unansweredCount}</strong><span>Chưa trả lời</span></div><div><strong>{submitSummary.flaggedCount}</strong><span>Đánh dấu</span></div></div>{submitSummary.unansweredCount>0&&<div className="submit-warning"><Icon>warning</Icon>Bạn vẫn có thể nộp bài, nhưng các câu trống sẽ không được tính điểm.</div>}{submitError&&<div className="submit-error">{submitError}</div>}<footer><button type="button" disabled={submitting} onClick={()=>setSubmitSummary(null)}>Làm tiếp</button><button type="button" disabled={submitting} onClick={confirmSubmit}>{submitting?'Đang nộp...':'Nộp bài'}</button></footer></section></div>}
    {submitError&&!submitSummary&&<div className="exam-submit-error"><Icon>error</Icon>{submitError}<button type="button" onClick={()=>setSubmitError('')}><Icon>close</Icon></button></div>}
    <button className="question-list-trigger" type="button" onClick={()=>setShowGrid(true)}><Icon>format_list_numbered</Icon>Danh sách {flat.length} câu <i>{Object.values(answers).filter(Boolean).length}</i></button>
    <footer className="exam-nav"><button className="exam-nav-prev" type="button" disabled={current===0||submitting} onClick={()=>move(-1)}><Icon>chevron_left</Icon>Trước</button><button className="exam-nav-grid" type="button" onClick={()=>setShowGrid(true)} aria-label={`Mở danh sách ${flat.length} câu hỏi, đã trả lời ${Object.values(answers).filter(Boolean).length} câu`}><Icon>grid_view</Icon><i>{Object.values(answers).filter(Boolean).length}</i></button><button className="exam-nav-next" type="button" disabled={submitting} onClick={()=>current===flat.length-1?prepareSubmit():move(1)}>{current===flat.length-1?'Nộp bài':'Tiếp theo'}<Icon>{current===flat.length-1?'check_circle':'chevron_right'}</Icon></button></footer>
  </main>;
}

function ExamCompleted({event,result}){
  const percent=Number.isFinite(Number(result.scorePercent))?Number(result.scorePercent):Math.round(((result.correctCount||0)/Math.max(1,result.totalQuestions||1))*100);
  const maxScore=Number(result.maxScore)||result.totalQuestions||0;
  const submittedAt=result.submittedAt?new Intl.DateTimeFormat('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(result.submittedAt)):'';
  const candidate=result.candidate||{};const name=candidate.fullName||'Bạn';
  const message=percent>=80?'Xuất sắc hoàn thành!':percent>=60?'Hoàn thành rất tốt!':'Bạn đã hoàn thành!';
  const durationSeconds=Math.max(0,Number(result.durationSeconds)||0);const duration=durationSeconds<60?`${durationSeconds} giây`:`${Math.floor(durationSeconds/60)}m ${String(durationSeconds%60).padStart(2,'0')}s`;const rank=result.ranking;const toeic=result.toeicEstimate;
  const avatarThemes=[['#e0f2fe','#0369a1','👩🏻'],['#fef3c7','#a16207','👨🏻'],['#ede9fe','#6d28d9','👩🏻‍🦱'],['#dcfce7','#047857','🧑🏻']];
  const avatar=avatarThemes[[...String(candidate.email||name)].reduce((sum,char)=>sum+char.charCodeAt(0),0)%avatarThemes.length];
  return <main className="mobile-shell result-app">
    <header className="result-header"><img src="/IIG_logo.webp" alt="IIG Việt Nam"/><div><strong>Kết quả Workshop <em>LIVE</em></strong><small>{event.schoolName||'IIG English Quick Test'}</small></div><span><Icon>verified</Icon>Đã nộp bài</span></header>
    <div className="result-content"><section className="result-identity"><i className="confetti confetti-one">✨</i><i className="confetti confetti-two">🎉</i><span><Icon>school</Icon>IIG English Challenge • {candidate.schoolName||event.schoolName}</span><div className="result-avatar" style={{background:avatar[0],color:avatar[1]}}><span>{avatar[2]}</span>{rank&&<em>{rank.rank<=3?'🏆 TOP 3':`HẠNG #${rank.rank}`}</em>}</div><h1>{message}<br/><b>{name}</b></h1><p>{candidate.email||''}<i/>{candidate.schoolName||event.schoolName}</p></section>
      {rank&&<section className="result-ranking"><header><strong><i/>Xếp hạng kỳ thi</strong><span>{rank.totalCandidates} thí sinh</span></header><div><article><small>Vị trí hiện tại</small><strong>#{rank.rank}<em>/{rank.totalCandidates}</em></strong><span>Đứng thứ {rank.rank} trong kỳ thi</span></article><article><small>Thời gian làm bài</small><strong>{duration}</strong><span>Đã hoàn thành bài thi</span></article></div></section>}
      <section className="result-analysis"><header><div><Icon>analytics</Icon><h2>Điểm số & Kết quả bài thi</h2></div><span>{result.totalScore}/{maxScore} điểm</span></header><div className="result-score-card"><div className="result-score-ring" style={{'--score':`${Math.max(0,Math.min(100,percent)) * 3.6}deg`}}><div><strong>{result.totalScore}</strong><small>/{maxScore} điểm</small></div></div><div className="result-score-copy">{toeic&&<><small className="toeic-label">Dự đoán TOEIC</small><strong>{toeic.min} - {toeic.max}<em>/{toeic.scale}</em></strong></>}<small>Đúng <b>{result.correctCount}/{result.totalQuestions}</b> câu trắc nghiệm</small><mark>Điểm quy đổi tham khảo</mark></div></div>
        {!!result.partBreakdown?.length&&<div className="result-parts"><header><h2>Phân tích theo phần thi</h2><span>So với tổng điểm từng phần</span></header>{result.partBreakdown.map((part,index)=><article key={part.id||index}><div><strong><Icon>{skillMeta(part.title).icon}</Icon>{part.title}</strong><span>{part.score}/{part.maxScore} điểm</span></div><div><i style={{width:`${part.percent}%`}}/></div><small>{part.correctCount}/{part.totalQuestions} câu đúng • {part.percent}%</small></article>)}</div>}
      </section>
      {!!result.leaderboard?.entries?.length&&<section className="result-leaderboard"><header><div><Icon>military_tech</Icon><h2>Top 3 kỳ thi</h2></div><span><i/>Cập nhật trực tiếp</span></header><div className={`leaderboard-list count-${result.leaderboard.entries.length}`}>{result.leaderboard.entries.map(entry=><article className={`${entry.rank===1?'winner ':''}${entry.isCurrentCandidate?'current':''}`} key={entry.rank}><div>{entry.rank===1?'🥇':entry.rank===2?'🥈':'🥉'}</div><strong>{entry.displayName}</strong><small>Hạng {entry.rank}</small><b>{entry.score}đ</b></article>)}</div><p>{rank?.rank<=3?<>Bạn đang nằm trong <strong>Top 3</strong> của kỳ thi!</>:<>Bạn cần thêm <strong>{result.leaderboard.pointsToTop3} điểm</strong> để vào Top 3.</>}</p></section>}
      {submittedAt&&<p className="result-time"><Icon>schedule</Icon>Hoàn thành lúc {submittedAt}</p>}
      <div className="result-note"><Icon>info</Icon><p>Kết quả quy đổi mang tính tham khảo, không thay thế điểm TOEIC chính thức.</p></div>
    </div>
    <footer className="result-footer"><button type="button" onClick={()=>window.location.assign(`/events/${event.id}`)}><Icon>home</Icon>Về trang kỳ thi</button></footer>
  </main>;
}

function LandingPage({event}){
  const [form,setForm]=useState(EMPTY_FORM);const [errors,setErrors]=useState({});const [notice,setNotice]=useState('');const [submitting,setSubmitting]=useState(false);
  const canEnter=event.canEnter===true;const skillNames=event.exam.parts.map(part=>part.title).filter(Boolean);const heroImage=event.bannerUrl||'/workshop-hero-v2.png';const birthYears=useMemo(()=>{const top=new Date().getFullYear()-10;return Array.from({length:top-1950+1},(_,index)=>top-index);},[]);
  const update=(key,value)=>{setForm(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:''}));setNotice('');};
  const submit=async submitEvent=>{submitEvent.preventDefault();const next={};if(!form.fullName.trim())next.fullName='Vui lòng nhập họ và tên.';if(!/^(?:\+?84|0)(?:\d[ .-]?){8,10}$/.test(form.phone.trim()))next.phone='Số điện thoại không hợp lệ.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))next.email='Email không hợp lệ.';if(!form.birthYear)next.birthYear='Vui lòng chọn năm sinh.';if(!form.toeicExperience)next.toeicExperience='Vui lòng chọn tình trạng học/thi TOEIC.';if(!form.privacyConsent)next.privacyConsent='Bạn cần đồng ý để tiếp tục.';setErrors(next);if(Object.keys(next).length){document.querySelector('[aria-invalid="true"]')?.focus();return;}setSubmitting(true);setNotice('');try{const registration=await registerExamCandidate(event.id,{...form,birthYear:Number(form.birthYear)});sessionStorage.setItem(`exam-registration:${event.id}`,JSON.stringify(registration));window.location.assign(`/events/${event.id}/introduction`);}catch(error){setNotice(error.message||'Không thể lưu thông tin. Vui lòng thử lại.');}finally{setSubmitting(false);}};
  return <main className="mobile-shell">
    <header className="app-header"><div className="brand"><img src="/IIG_logo.webp" alt="IIG Việt Nam"/><div><strong>IIG Việt Nam</strong><span>Education Assessment</span></div></div><span className="quick-badge"><i/>Quick Test</span></header>
    <div className="page-content">
      <section className="hero-card">
        <div className="hero-media has-image" style={{backgroundImage:`linear-gradient(to top,rgba(8,46,34,.86) 0%,rgba(9,53,39,.2) 62%,rgba(0,0,0,.08) 100%),url("${heroImage}")`}}>
          <div className="hero-badges"><span className="workshop"><i/>Workshop</span><span>Miễn phí</span></div>
          <div className="hero-eyebrow"><Icon>verified</Icon>IIG Việt Nam × Workshop tại trường</div>
          <div className="deadline"><Icon>schedule</Icon>Hạn: {formatDeadline(event.endAt)}</div>
        </div>
        <div className="hero-copy"><span className="hero-kicker">English Quick Assessment</span><h1>{event.name}</h1><p>{textOnly(event.description)}</p><div className="event-school"><span className="school-icon iig-organizer-logo"><img src="/IIG_logo.webp" alt="IIG Việt Nam"/></span><div><strong>{event.schoolName}</strong><span>Được tổ chức bởi IIG Việt Nam</span></div><Icon className="verified-icon">verified</Icon></div></div>
      </section>

      <section className="exam-overview" aria-label="Thông tin bài kiểm tra">
        <div className="summary-grid">
          <SummaryCard icon="fact_check" value={`${event.exam.totalQuestions} câu`} label={`${skillNames.length} kỹ năng`}/>
          <SummaryCard icon="schedule" value={`${minutes(event.exam.durationSeconds)} phút`} label="Thời gian làm bài" tone="amber"/>
          <SummaryCard icon="auto_awesome" value="Kết quả ngay" label="Phân tích tức thì"/>
        </div>
        <div className="skill-strip"><header><div><Icon>bolt</Icon><span>Nội dung bài kiểm tra</span></div><small>{event.exam.totalQuestions} câu • {skillNames.length} kỹ năng</small></header><ul>{event.exam.parts.map((part,index)=>{const meta=skillMeta(part.title);return <li className={`skill-${meta.tone}`} key={part.id||`${part.title}-${index}`}><span className="skill-icon"><Icon>{meta.icon}</Icon></span><span className="skill-copy"><strong>{part.title}</strong><small>{meta.hint}</small></span><span className="skill-count"><b>{part.questionCount}</b> câu</span></li>;})}</ul></div>
      </section>

      {!canEnter&&<AccessNotice state={event.accessState} reason={event.unavailableReason} startAt={event.startAt}/>}

      <section className="form-card">
        <div className="section-heading"><div><span><Icon>person</Icon></span><div><h2>Thông tin của bạn</h2><p>Điền thông tin để nhận kết quả và lộ trình phù hợp.</p></div><em>1 phút</em></div></div>
        <form onSubmit={submit} noValidate>
          <Field id="fullName" label="Họ và tên" icon="person" error={errors.fullName}><input id="fullName" value={form.fullName} onChange={e=>update('fullName',e.target.value)} placeholder="Ví dụ: Nguyễn Văn An" autoComplete="name" aria-invalid={Boolean(errors.fullName)}/></Field>
          <Field id="phone" label="Số điện thoại" icon="call" error={errors.phone}><input id="phone" type="tel" inputMode="tel" value={form.phone} onChange={e=>update('phone',e.target.value)} placeholder="0912 345 678" autoComplete="tel" aria-invalid={Boolean(errors.phone)}/></Field>
          <Field id="email" label="Email" icon="mail" error={errors.email}><input id="email" type="email" inputMode="email" value={form.email} onChange={e=>update('email',e.target.value)} placeholder="nguyenvanan@gmail.com" autoComplete="email" aria-invalid={Boolean(errors.email)}/></Field>
          <Field id="school" label="Tên trường" icon="school"><input id="school" value={event.schoolName||''} readOnly className="readonly"/><Icon className="field-trailing">lock</Icon></Field>
          <Field id="birthYear" label="Năm sinh" icon="calendar_today" error={errors.birthYear}><select id="birthYear" value={form.birthYear} onChange={e=>update('birthYear',e.target.value)} aria-invalid={Boolean(errors.birthYear)}><option value="">Chọn năm sinh</option>{birthYears.map(year=><option key={year} value={year}>{year}</option>)}</select><Icon className="field-trailing">keyboard_arrow_down</Icon></Field>
          <Field id="toeicExperience" label="Đã học TOEIC chưa?" icon="menu_book" error={errors.toeicExperience}><select id="toeicExperience" value={form.toeicExperience} onChange={e=>update('toeicExperience',e.target.value)} aria-invalid={Boolean(errors.toeicExperience)}><option value="">Chọn tình trạng học/thi TOEIC</option>{TOEIC_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select><Icon className="field-trailing">keyboard_arrow_down</Icon></Field>
          <div className="consents">
            <CheckRow checked={form.privacyConsent} onChange={checked=>update('privacyConsent',checked)} required error={errors.privacyConsent}>Tôi đồng ý để IIG Việt Nam xử lý thông tin nhằm tổ chức bài kiểm tra và gửi kết quả.</CheckRow>
            <CheckRow checked={form.marketingConsent} onChange={checked=>update('marketingConsent',checked)}>Tôi muốn nhận thông tin tư vấn về chương trình học phù hợp.</CheckRow>
            <a href="#privacy">Chính sách bảo mật của IIG Việt Nam ↗</a>
          </div>
          {notice&&<div className="form-notice"><Icon>info</Icon>{notice}</div>}
          <button className="primary-cta" type="submit" disabled={!canEnter||submitting}>{submitting?'Đang lưu thông tin...':'Bắt đầu kiểm tra'} <Icon>{submitting?'progress_activity':'arrow_forward'}</Icon></button>
        </form>
      </section>
      <p className="trust-message">🔒 Thông tin của bạn được IIG Việt Nam bảo mật.</p>
      <p className="disclaimer">Kết quả chỉ mang tính tham khảo và không thay thế điểm TOEIC chính thức.</p>
    </div>
  </main>;
}

function SummaryCard({icon,value,label,tone=''}){return <article className={`summary-card ${tone}`}><span><Icon>{icon}</Icon></span><strong>{value}</strong><small>{label}</small></article>}
function Field({id,label,icon,error,children}){return <div className={`field${error?' has-error':''}`}><label htmlFor={id}>{label} <b>*</b></label><div className="field-control"><Icon>{icon}</Icon>{children}</div>{error&&<p><Icon>error</Icon>{error}</p>}</div>}
function CheckRow({checked,onChange,required=false,error,children}){return <div><label className="check-row"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{children}{required&&<b> *</b>}</span></label>{error&&<p className="check-error">{error}</p>}</div>}
function AccessNotice({state,reason,startAt}){const upcoming=state==='UPCOMING';return <section className="access-notice"><Icon>{upcoming?'event':'event_busy'}</Icon><div><strong>{upcoming?'Kỳ thi chưa bắt đầu':'Kỳ thi không còn nhận bài'}</strong><p>{reason}{upcoming?` Thời gian mở: ${formatDeadline(startAt)}.`:''}</p></div></section>}
function StateScreen({icon,title,description,loading=false}){return <main className="mobile-shell state-screen"><div className={loading?'spin':''}><Icon>{icon}</Icon></div><h1>{title}</h1><p>{description}</p><button type="button" onClick={()=>window.location.reload()}>Thử lại</button></main>}
