ALTER TABLE local_voice_clones ADD COLUMN IF NOT EXISTS engine VARCHAR(80) NOT NULL DEFAULT 'legacy';
ALTER TABLE local_voice_clones ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'ready';
ALTER TABLE local_voice_clones ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

