-- Standard report templates derived from the approved July monthly workbook.
WITH kpi(team_code,code,name,unit,direction,aggregation,input_mode,formula_code,display_order) AS (VALUES
('REV','DT_01','Doanh thu thực hiện tháng','Tỷ đồng','increase_good','sum','derived','DT_01',1),
('REV','DT_02','Doanh thu lũy kế năm','Tỷ đồng','increase_good','ytd_last_value','manual',NULL,2),
('REV','DT_03','Số đơn hàng','Đơn','increase_good','sum','derived','DT_03',3),
('REV','DT_04','Doanh thu trung bình/đơn hàng','Triệu đồng','increase_good','ratio_of_sums','derived','DT_04',4),
('REV','DT_05','Doanh thu trung bình/Sales','Triệu đồng','increase_good','ratio_of_sums','manual',NULL,5),
('REV','DT_06','Số lượng Sales','Người','monitor','last_value','manual',NULL,6),
('ADS','ADS_01','Doanh thu từ Ads','Tỷ đồng','increase_good','sum','derived','ADS_01',1),
('ADS','ADS_02','Số lượng data mang về','Lượt','increase_good','sum','derived','ADS_02',2),
('ADS','ADS_03','Số đơn hàng từ Ads','Đơn','increase_good','sum','derived','ADS_03',3),
('ADS','ADS_04','Tỷ lệ chốt (đơn/data)','%','increase_good','ratio_of_sums','derived','ADS_04',4),
('ADS','ADS_05','Ngân sách đã sử dụng','Tỷ đồng','monitor','sum','derived','ADS_05',5),
('ADS','ADS_06','Chi phí/Doanh thu (CPR)','%','decrease_good','ratio_of_sums','derived','ADS_06',6),
('ADS','ADS_07','Doanh thu trung bình/đơn Ads','Triệu đồng','increase_good','ratio_of_sums','derived','ADS_07',7),
('COM','TT_01','Tổng Followers','Lượt','increase_good','last_value','derived','TT_01',1),
('COM','TT_02','Tăng trưởng Followers','%','increase_good','ratio_of_sums','derived','TT_02',2),
('COM','TT_03','Tổng Reach','Lượt','increase_good','sum','derived','TT_03',3),
('COM','TT_04','Tỷ lệ tiếp cận Organic','%','increase_good','ratio_of_sums','derived','TT_04',4),
('COM','TT_05','Engagement Rate','%','increase_good','ratio_of_sums','derived','TT_05',5),
('COM','TT_06','Lượt xem Video','Lượt','increase_good','sum','derived','TT_06',6),
('COM','TT_07','Số lượng Data từ Content','Lượt','increase_good','sum','derived','TT_07',7),
('COM','TT_08','Ngân sách Content','Triệu đồng','monitor','sum','derived','TT_08',8),
('COM','TT_09','Doanh thu từ Content','Triệu đồng','increase_good','sum','derived','TT_09',9),
('TRADE','TRADE_01','Tổng số trường đã triển khai','Trường','increase_good','last_value','manual',NULL,1),
('TRADE','TRADE_02','Trường ký kết triển khai mới','Trường','increase_good','sum','derived','TRADE_02',2),
('TRADE','TRADE_03','Trường tổ chức hoạt động trong tháng','Trường','increase_good','sum','derived','TRADE_03',3),
('TRADE','TRADE_04','Số ngày Activation','Lượt','increase_good','sum','derived','TRADE_04',4),
('TRADE','TRADE_05','Số Workshop đã tổ chức','Lượt','increase_good','sum','derived','TRADE_05',5),
('TRADE','TRADE_06','Bài Social trên kênh trường/cộng đồng','Lượt','increase_good','sum','derived','TRADE_06',6),
('TRADE','TRADE_07','Reach từ hoạt động Trade','Lượt','increase_good','sum','derived','TRADE_07',7),
('TRADE','TRADE_08','Data thu về','Lượt','increase_good','sum','derived','TRADE_08',8),
('TRADE','TRADE_09','Ngân sách Trade','Triệu đồng','monitor','sum','derived','TRADE_09',9),
('TRADE','TRADE_10','Doanh thu từ Trade','Triệu đồng','increase_good','sum','derived','TRADE_10',10),
('TRADE','TRADE_11','Chi phí/Doanh thu','%','decrease_good','ratio_of_sums','derived','TRADE_11',11),
('TRAIN','DAO_01','Tổng học viên đang đào tạo','Người','increase_good','last_value','derived','DAO_01',1),
('TRAIN','DAO_02','Học viên mới','Người','increase_good','sum','derived','DAO_02',2),
('TRAIN','DAO_03','Học viên kết thúc khóa','Người','monitor','sum','derived','DAO_03',3),
('TRAIN','DAO_04','Tỷ lệ học viên đạt đầu ra','%','increase_good','ratio_of_sums','derived','DAO_04',4),
('TRAIN','DAO_05','Lớp học khai giảng','Lớp','increase_good','sum','derived','DAO_05',5),
('TRAIN','DAO_06','Lớp học đang đào tạo','Lớp','monitor','last_value','derived','DAO_06',6),
('TRAIN','DAO_07','Lớp học bế giảng','Lớp','monitor','sum','derived','DAO_07',7),
('TRAIN','DAO_08','Giáo viên Active','Người','monitor','last_value','manual',NULL,8),
('TRAIN','DAO_09','Doanh thu học lên','Triệu đồng','increase_good','sum','derived','DAO_09',9),
('PROD','SP_01','Số lượng đề thi thử được sản xuất','Sản phẩm','increase_good','sum','derived','SP_01',1),
('PROD','SP_02','Khóa tự học TOEIC ra mắt/điều chỉnh','Sản phẩm','increase_good','sum','derived','SP_02',2),
('PROD','SP_03','Khóa tự học TOEFL ra mắt/điều chỉnh','Sản phẩm','increase_good','sum','derived','SP_03',3),
('PROD','SP_04','Khóa trực tuyến ra mắt/điều chỉnh','Sản phẩm','increase_good','sum','derived','SP_04',4),
('PROD','SP_05','Hoạt động nghiên cứu/đánh giá khác','Hoạt động','monitor','sum','derived','SP_05',5)
)
UPDATE report_kpi_definitions d SET name=k.name,unit=k.unit,evaluation_direction=k.direction,
 aggregation_method=k.aggregation,input_mode=k.input_mode,formula_code=k.formula_code,
 display_order=k.display_order,is_active=TRUE,updated_at=CURRENT_TIMESTAMP
FROM kpi k JOIN report_teams t ON t.code=k.team_code WHERE d.team_id=t.id AND d.code=k.code;

WITH templates(team_code,row_code,row_name,row_group,section_key,display_order) AS (VALUES
('REV','REV_TOEIC_SELF_TEST_LR','Tự học + Thi thử TOEIC LR','Tự sản xuất','primary',1),
('REV','REV_TOEIC_SELF_TEST_SW','Tự học + Thi thử TOEIC SW','Tự sản xuất','primary',2),
('REV','REV_TOEIC_ONLINE_LR','Trực tuyến TOEIC LR','Tự sản xuất','primary',3),
('REV','REV_TOEIC_ONLINE_SW','Trực tuyến TOEIC SW','Tự sản xuất','primary',4),
('REV','REV_TOEFL_SELF_TEST','Tự học + Thi thử TOEFL','Tự sản xuất','primary',5),
('REV','REV_TOEFL_ONLINE','Trực tuyến TOEFL','Tự sản xuất','primary',6),
('REV','REV_IT_SELF_STUDY','Tự học Tin học','Tự sản xuất','primary',7),
('REV','REV_BUSINESS_ENGLISH','Giao tiếp BE','Tự sản xuất','primary',8),
('REV','REV_IBT_VOUCHER','Voucher iBT','Đối tác','primary',9),
('REV','REV_ENGLISH_TOOLS','Công cụ tiếng Anh (ELC, OLPC)','Đối tác','primary',10),
('REV','REV_IT_TOOLS','Công cụ tin học (GMetrix, Jasperactive)','Đối tác','primary',11),
('REV','REV_OTHER','Khác','Khác','primary',12),
('ADS','ADS_TRAFFIC_FACEBOOK','Facebook',NULL,'traffic',1),('ADS','ADS_TRAFFIC_GOOGLE','Google',NULL,'traffic',2),
('ADS','ADS_TRAFFIC_TIKTOK','TikTok',NULL,'traffic',3),('ADS','ADS_TRAFFIC_COC_COC','Cốc Cốc',NULL,'traffic',4),
('ADS','ADS_TRAFFIC_WEBSITE','Website',NULL,'traffic',5),('ADS','ADS_TRAFFIC_EMAIL','Email MKT',NULL,'traffic',6),
('ADS','ADS_TRAFFIC_THREADS','Threads',NULL,'traffic',7),('ADS','ADS_TRAFFIC_FLYERS','Flyers',NULL,'traffic',8),
('ADS','ADS_TRAFFIC_ZALO','Zalo',NULL,'traffic',9),('ADS','ADS_TRAFFIC_OTHER','Khác',NULL,'traffic',10),
('ADS','ADS_PRODUCT_TOEIC_SELF_TEST_LR','Tự học + Thi thử TOEIC LR','Tự sản xuất','products',1),
('ADS','ADS_PRODUCT_TOEIC_SELF_TEST_SW','Tự học + Thi thử TOEIC SW','Tự sản xuất','products',2),
('ADS','ADS_PRODUCT_TOEIC_ONLINE_LR','Trực tuyến TOEIC LR','Tự sản xuất','products',3),
('ADS','ADS_PRODUCT_TOEIC_ONLINE_SW','Trực tuyến TOEIC SW','Tự sản xuất','products',4),
('ADS','ADS_PRODUCT_TOEFL_SELF_TEST','Tự học + Thi thử TOEFL','Tự sản xuất','products',5),
('ADS','ADS_PRODUCT_TOEFL_ONLINE','Trực tuyến TOEFL','Tự sản xuất','products',6),
('ADS','ADS_PRODUCT_IT_SELF_STUDY','Tự học Tin học','Tự sản xuất','products',7),
('ADS','ADS_PRODUCT_BUSINESS_ENGLISH','Giao tiếp BE','Tự sản xuất','products',8),
('ADS','ADS_PRODUCT_IBT_VOUCHER','Voucher iBT','Đối tác','products',9),
('ADS','ADS_PRODUCT_ENGLISH_TOOLS','Công cụ tiếng Anh','Đối tác','products',10),
('ADS','ADS_PRODUCT_IT_TOOLS','Công cụ tin học','Đối tác','products',11),('ADS','ADS_PRODUCT_OTHER','Khác','Khác','products',12),
('COM','COM_TOEIC_VIETNAM','Fanpage TOEIC Vietnam',NULL,'primary',1),('COM','COM_IIG_VIETNAM','Fanpage IIG Vietnam',NULL,'primary',2),
('COM','COM_TOEFL_VIETNAM','Fanpage TOEFL Vietnam',NULL,'primary',3),('COM','COM_TOEIC_CLASS','Fanpage Lớp học TOEIC',NULL,'primary',4),
('COM','COM_COMMUNITY_GROUP','Group cộng đồng',NULL,'primary',5),('COM','COM_YOUTUBE','YouTube',NULL,'primary',6),
('COM','COM_TIKTOK','TikTok',NULL,'primary',7),('COM','COM_WEBSITE','Website',NULL,'primary',8),
('COM','COM_ZALO','Zalo',NULL,'primary',9),('COM','COM_OTHER','Khác (bao gồm email và các UTM khác)',NULL,'primary',10),
('TRAIN','TRAIN_TOEIC_LR','TOEIC LR',NULL,'primary',1),('TRAIN','TRAIN_TOEIC_SW','TOEIC SW',NULL,'primary',2),
('TRAIN','TRAIN_BUSINESS_ENGLISH','Business English',NULL,'primary',3),('TRAIN','TRAIN_TOEFL','TOEFL',NULL,'primary',4),
('TRAIN','TRAIN_IT','Tin học',NULL,'primary',5),('TRAIN','TRAIN_OTHER','Khác',NULL,'primary',6)
)
INSERT INTO report_detail_row_templates(team_id,row_code,row_name,row_group,section_key,display_order,is_required,is_active)
SELECT t.id,x.row_code,x.row_name,x.row_group,x.section_key,x.display_order,FALSE,TRUE
FROM templates x JOIN report_teams t ON t.code=x.team_code
ON CONFLICT(team_id,row_code) DO UPDATE SET row_name=EXCLUDED.row_name,row_group=EXCLUDED.row_group,
 section_key=EXCLUDED.section_key,display_order=EXCLUDED.display_order,is_required=FALSE,is_active=TRUE,updated_at=CURRENT_TIMESTAMP;
