-- Restore KPI definitions that may have been removed when report configuration was reset.
WITH kpi(team_code,code,name,unit,direction,aggregation,input_mode,formula_code,source_sheet,display_order) AS (VALUES
('REV','DT_01','Doanh thu thực hiện tháng','Tỷ đồng','increase_good','sum','derived','DT_01','02_Doanh_thu',1),
('REV','DT_02','Doanh thu lũy kế năm','Tỷ đồng','increase_good','ytd_last_value','manual',NULL,'02_Doanh_thu',2),
('REV','DT_03','Số đơn hàng','Đơn','increase_good','sum','derived','DT_03','02_Doanh_thu',3),
('REV','DT_04','Doanh thu trung bình/đơn hàng','Triệu đồng','increase_good','ratio_of_sums','derived','DT_04','02_Doanh_thu',4),
('REV','DT_05','Doanh thu trung bình/Sales','Triệu đồng','increase_good','ratio_of_sums','manual',NULL,'02_Doanh_thu',5),
('REV','DT_06','Số lượng Sales','Người','monitor','last_value','manual',NULL,'02_Doanh_thu',6),
('ADS','ADS_01','Doanh thu từ Ads','Tỷ đồng','increase_good','sum','derived','ADS_01','03_MKT_Ads',1),
('ADS','ADS_02','Số lượng data mang về','Lượt','increase_good','sum','derived','ADS_02','03_MKT_Ads',2),
('ADS','ADS_03','Số đơn hàng từ Ads','Đơn','increase_good','sum','derived','ADS_03','03_MKT_Ads',3),
('ADS','ADS_04','Tỷ lệ chốt (đơn/data)','%','increase_good','ratio_of_sums','derived','ADS_04','03_MKT_Ads',4),
('ADS','ADS_05','Ngân sách đã sử dụng','Tỷ đồng','monitor','sum','derived','ADS_05','03_MKT_Ads',5),
('ADS','ADS_06','Chi phí/Doanh thu (CPR)','%','decrease_good','ratio_of_sums','derived','ADS_06','03_MKT_Ads',6),
('ADS','ADS_07','Doanh thu trung bình/đơn Ads','Triệu đồng','increase_good','ratio_of_sums','derived','ADS_07','03_MKT_Ads',7),
('COM','TT_01','Tổng Followers','Lượt','increase_good','last_value','derived','TT_01','04_Truyen_thong',1),
('COM','TT_02','Tăng trưởng Followers','%','increase_good','ratio_of_sums','derived','TT_02','04_Truyen_thong',2),
('COM','TT_03','Tổng Reach','Lượt','increase_good','sum','derived','TT_03','04_Truyen_thong',3),
('COM','TT_04','Tỷ lệ tiếp cận Organic','%','increase_good','ratio_of_sums','derived','TT_04','04_Truyen_thong',4),
('COM','TT_05','Engagement Rate','%','increase_good','ratio_of_sums','derived','TT_05','04_Truyen_thong',5),
('COM','TT_06','Lượt xem Video','Lượt','increase_good','sum','derived','TT_06','04_Truyen_thong',6),
('COM','TT_07','Số lượng Data từ Content','Lượt','increase_good','sum','derived','TT_07','04_Truyen_thong',7),
('COM','TT_08','Ngân sách Content','Triệu đồng','monitor','sum','derived','TT_08','04_Truyen_thong',8),
('COM','TT_09','Doanh thu từ Content','Triệu đồng','increase_good','sum','derived','TT_09','04_Truyen_thong',9),
('TRADE','TRADE_01','Tổng số trường đã triển khai','Trường','increase_good','last_value','manual',NULL,'05_Trade',1),
('TRADE','TRADE_02','Trường ký kết triển khai mới','Trường','increase_good','sum','derived','TRADE_02','05_Trade',2),
('TRADE','TRADE_03','Trường tổ chức hoạt động trong tháng','Trường','increase_good','sum','derived','TRADE_03','05_Trade',3),
('TRADE','TRADE_04','Số ngày Activation','Lượt','increase_good','sum','derived','TRADE_04','05_Trade',4),
('TRADE','TRADE_05','Số Workshop đã tổ chức','Lượt','increase_good','sum','derived','TRADE_05','05_Trade',5),
('TRADE','TRADE_06','Bài Social trên kênh trường/cộng đồng','Lượt','increase_good','sum','derived','TRADE_06','05_Trade',6),
('TRADE','TRADE_07','Reach từ hoạt động Trade','Lượt','increase_good','sum','derived','TRADE_07','05_Trade',7),
('TRADE','TRADE_08','Data thu về','Lượt','increase_good','sum','derived','TRADE_08','05_Trade',8),
('TRADE','TRADE_09','Ngân sách Trade','Triệu đồng','monitor','sum','derived','TRADE_09','05_Trade',9),
('TRADE','TRADE_10','Doanh thu từ Trade','Triệu đồng','increase_good','sum','derived','TRADE_10','05_Trade',10),
('TRADE','TRADE_11','Chi phí/Doanh thu','%','decrease_good','ratio_of_sums','derived','TRADE_11','05_Trade',11),
('TRAIN','DAO_01','Tổng học viên đang đào tạo','Người','increase_good','last_value','derived','DAO_01','06_Dao_tao',1),
('TRAIN','DAO_02','Học viên mới','Người','increase_good','sum','derived','DAO_02','06_Dao_tao',2),
('TRAIN','DAO_03','Học viên kết thúc khóa','Người','monitor','sum','derived','DAO_03','06_Dao_tao',3),
('TRAIN','DAO_04','Tỷ lệ học viên đạt đầu ra','%','increase_good','ratio_of_sums','derived','DAO_04','06_Dao_tao',4),
('TRAIN','DAO_05','Lớp học khai giảng','Lớp','increase_good','sum','derived','DAO_05','06_Dao_tao',5),
('TRAIN','DAO_06','Lớp học đang đào tạo','Lớp','monitor','last_value','derived','DAO_06','06_Dao_tao',6),
('TRAIN','DAO_07','Lớp học bế giảng','Lớp','monitor','sum','derived','DAO_07','06_Dao_tao',7),
('TRAIN','DAO_08','Giáo viên Active','Người','monitor','last_value','manual',NULL,'06_Dao_tao',8),
('TRAIN','DAO_09','Doanh thu học lên','Triệu đồng','increase_good','sum','derived','DAO_09','06_Dao_tao',9),
('PROD','SP_01','Số lượng đề thi thử được sản xuất','Sản phẩm','increase_good','sum','derived','SP_01','07_San_pham',1),
('PROD','SP_02','Khóa tự học TOEIC ra mắt/điều chỉnh','Sản phẩm','increase_good','sum','derived','SP_02','07_San_pham',2),
('PROD','SP_03','Khóa tự học TOEFL ra mắt/điều chỉnh','Sản phẩm','increase_good','sum','derived','SP_03','07_San_pham',3),
('PROD','SP_04','Khóa trực tuyến ra mắt/điều chỉnh','Sản phẩm','increase_good','sum','derived','SP_04','07_San_pham',4),
('PROD','SP_05','Hoạt động nghiên cứu/đánh giá khác','Hoạt động','monitor','sum','derived','SP_05','07_San_pham',5)
)
INSERT INTO report_kpi_definitions(team_id,code,name,unit,evaluation_direction,aggregation_method,input_mode,formula_code,source_sheet,display_order,is_active)
SELECT t.id,k.code,k.name,k.unit,k.direction,k.aggregation,k.input_mode,k.formula_code,k.source_sheet,k.display_order,TRUE
FROM kpi k JOIN report_teams t ON t.code=k.team_code
ON CONFLICT(code) DO UPDATE SET team_id=EXCLUDED.team_id,name=EXCLUDED.name,unit=EXCLUDED.unit,
 evaluation_direction=EXCLUDED.evaluation_direction,aggregation_method=EXCLUDED.aggregation_method,
 input_mode=EXCLUDED.input_mode,formula_code=EXCLUDED.formula_code,source_sheet=EXCLUDED.source_sheet,
 display_order=EXCLUDED.display_order,is_active=TRUE,updated_at=CURRENT_TIMESTAMP;
