const crypto=require('crypto');const path=require('path');const HttpError=require('../../http/httpError');
const repository=require('./statementImportRepository');const storage=require('../../services/storageService');const {getParser}=require('./parsers/parserRegistry');const {extractPdf}=require('./parsers/pdfTextExtractor');const {fingerprint}=require('./transactionFingerprint');
const {repairTpBankExtraction}=require('./parsers/tpBankObfuscatedExtractor');
const {isoDate,normalizeDescription}=require('./parsers/parserUtils');
const {buildTransactionWorkbook}=require('./transactionExcelExport');
const BANKS=[{code:'TECHCOMBANK',name:'Techcombank',extensions:['.pdf']},{code:'TPBANK',name:'TPBank',extensions:['.pdf']},{code:'VPBANK',name:'VPBank',extensions:['.pdf']},{code:'VIB',name:'VIB',extensions:['.xlsx']}];
function fail(message,status,code,details){throw new HttpError(message,status,code,details);}
function prepareAccountNumber(value){const input=String(value||'').trim();if(!input)fail('Số tài khoản/thẻ là bắt buộc.',400,'STATEMENT_ACCOUNT_INVALID');if(/[x*•]/i.test(input)){const suffix=accountSuffix(input);if(suffix.length<4)fail('Số đã che cần giữ lại ít nhất 4 số cuối.',400,'STATEMENT_ACCOUNT_INVALID');return{masked:input.replace(/x/gi,'*'),hash:null};}const compact=input.replace(/[\s-]/g,'').toUpperCase();if(!/^[A-Z0-9]{8,34}$/.test(compact))fail('Số tài khoản/thẻ phải có từ 8 đến 34 ký tự chữ hoặc số.',400,'STATEMENT_ACCOUNT_INVALID');const visibleStart=compact.slice(0,Math.min(4,Math.max(2,compact.length-6))),visibleEnd=compact.slice(-4),mask='*'.repeat(Math.max(4,compact.length-visibleStart.length-visibleEnd.length));return{masked:`${visibleStart}${mask}${visibleEnd}`,hash:crypto.createHash('sha256').update(compact).digest('hex')};}
function accountSuffix(value){const digits=String(value||'').replace(/\D/g,'');return digits.length>=4?digits.slice(-4):digits;}
function normalizeDraftRows(rows){return rows.map((row,index)=>{const transactionDate=isoDate(row.transactionDate),postingDate=row.postingDate?isoDate(row.postingDate):null,description=String(row.description||'').trim(),debitAmount=Number(row.debitAmount||0),creditAmount=Number(row.creditAmount||0),feeAmount=Number(row.feeAmount||0),originalAmount=Number(row.originalAmount||0);if(!transactionDate||row.postingDate&&!postingDate)fail(`Ngày giao dịch không hợp lệ tại dòng ${index+1}.`,400,'STATEMENT_TRANSACTION_INVALID',{row:index+1});if(!description)fail(`Diễn giải không được để trống tại dòng ${index+1}.`,400,'STATEMENT_TRANSACTION_INVALID',{row:index+1});if([debitAmount,creditAmount,feeAmount,originalAmount].some(value=>!Number.isFinite(value)||value<0)||debitAmount>0&&creditAmount>0||!debitAmount&&!creditAmount)fail(`Số tiền không hợp lệ tại dòng ${index+1}.`,400,'STATEMENT_TRANSACTION_INVALID',{row:index+1});if(feeAmount>debitAmount)fail(`Phí lớn hơn số tiền ghi nợ tại dòng ${index+1}.`,400,'STATEMENT_TRANSACTION_INVALID',{row:index+1});return{...row,transactionDate,postingDate,description,normalizedDescription:normalizeDescription(description),debitAmount:debitAmount.toFixed(2),creditAmount:creditAmount.toFixed(2),feeAmount:feeAmount.toFixed(2),originalAmount:originalAmount.toFixed(2),originalCurrency:String(row.originalCurrency||'VND').toUpperCase()};});}
module.exports={
  async bootstrap(auth){return{banks:BANKS,accounts:await repository.accounts(),permissions:auth.permissions||[],limits:{maxBytes:15*1024*1024,maxPages:50,maxFiles:1}};},
  accounts(bankCode){return repository.accounts(String(bankCode||'').toUpperCase()||null);},
  async createAccount(body,userId){const bankCode=String(body.bankCode||'').toUpperCase();if(!BANKS.some(bank=>bank.code===bankCode))fail('Ngân hàng chưa được hỗ trợ.',400,'STATEMENT_BANK_UNSUPPORTED');if(!String(body.accountName||'').trim())fail('Tên tài khoản/thẻ là bắt buộc.',400,'STATEMENT_ACCOUNT_INVALID');const prepared=prepareAccountNumber(body.accountNumber||body.accountNumberMasked);return repository.createAccount({...body,bankCode,accountName:String(body.accountName).trim(),accountNumberMasked:prepared.masked,accountNumberHash:prepared.hash,userId});},
  list(query){return repository.list(query);},transactions(query){return repository.transactions(query);},async exportTransactions(query){const rows=await repository.exportTransactions(query);if(rows.length>100000)fail('Dữ liệu xuất vượt quá 100.000 giao dịch. Hãy thu hẹp bộ lọc.',400,'TRANSACTION_EXPORT_LIMIT');return{buffer:buildTransactionWorkbook(rows),filename:`giao-dich-ngan-hang_${new Date().toISOString().slice(0,10)}.xlsx`};},dashboard(query){return repository.dashboard(query);},detail(id){return repository.detail(id);},
  async upload({file,body,userId}){if(!body.bankCode)fail('Vui lòng chọn ngân hàng.',400,'STATEMENT_BANK_REQUIRED');if(!body.bankAccountId)fail('Vui lòng chọn tài khoản/thẻ.',400,'STATEMENT_ACCOUNT_REQUIRED');if(!file)fail('Vui lòng chọn file sao kê.',400,'STATEMENT_FILE_REQUIRED');if(!file.size||!file.buffer?.length)fail('File sao kê đang rỗng. Hãy chọn lại file hoặc gửi multipart bằng file=@đường_dẫn.',400,'STATEMENT_FILE_EMPTY');
    const bankCode=String(body.bankCode).toUpperCase(),bank=BANKS.find(x=>x.code===bankCode);if(!bank)fail('Ngân hàng chưa được hỗ trợ.',400,'STATEMENT_BANK_UNSUPPORTED');const ext=path.extname(file.originalname).toLowerCase();if(!bank.extensions.includes(ext))fail(`Ngân hàng ${bank.name} chỉ hỗ trợ ${bank.extensions.join(', ')}.`,400,'STATEMENT_FILE_TYPE_INVALID');
    const account=await repository.account(body.bankAccountId);if(!account||account.bank_code!==bankCode)fail('Tài khoản/thẻ không thuộc ngân hàng đã chọn.',400,'STATEMENT_ACCOUNT_MISMATCH');const checksum=crypto.createHash('sha256').update(file.buffer).digest('hex'),duplicate=await repository.duplicate(checksum);if(duplicate)fail('File sao kê này đã được import.',409,'STATEMENT_DUPLICATED',duplicate);
    let extracted=null,result;const parser=getParser(bankCode);try{if(ext==='.pdf'){if(!file.buffer.subarray(0,5).equals(Buffer.from('%PDF-')))fail('File PDF không hợp lệ.',400,'STATEMENT_FILE_TYPE_INVALID');extracted=await extractPdf(file.buffer);if(extracted.pageCount>50)fail('File vượt quá 50 trang.',400,'STATEMENT_PAGE_LIMIT_EXCEEDED');if(!extracted.text.trim())fail('PDF không có lớp chữ.',400,'STATEMENT_HAS_NO_TEXT_LAYER');if(bankCode==='TPBANK')extracted=await repairTpBankExtraction(file.buffer,extracted);result=await parser.parse(extracted);}else result=await parser.parse(file.buffer,body.password);}catch(error){if(error instanceof HttpError)throw error;fail(error.message||'Không thể parse sao kê an toàn.',422,error.code||'STATEMENT_PARSE_FAILED');}
    const hasError=result.warnings.some(w=>w.level==='error');const status=hasError?'parser_failed':result.reconciliation.isBalanced?'ready_for_review':'reconciliation_failed';let storageKey=null;if(storage.isR2Configured()){const now=new Date(),key=`expense-statements/${now.getUTCFullYear()}/${String(now.getUTCMonth()+1).padStart(2,'0')}/${checksum}/source${ext}`;try{storageKey=await storage.uploadBuffer(file.buffer,key,file.mimetype||'application/octet-stream');}catch(error){if(process.env.NODE_ENV==='production'||process.env.APP_ENV==='production')fail('Không thể lưu file sao kê lên kho bảo mật.',503,'STATEMENT_STORAGE_FAILED');result.warnings.push({level:'warning',code:'STATEMENT_SOURCE_NOT_STORED',message:'R2 local từ chối quyền ghi; dữ liệu preview vẫn được lưu nhưng file nguồn chưa được lưu trữ.'});}}else result.warnings.push({level:'warning',code:'STATEMENT_SOURCE_NOT_STORED',message:'R2 chưa được cấu hình; metadata được lưu nhưng file nguồn chưa được lưu trữ.'});const data={bankCode,bankAccountId:account.id,filename:file.originalname,storageKey,checksum,size:file.size,pageCount:extracted?.pageCount||1,status,parserVersion:result.parser.version,warnings:result.warnings,rawMetadata:{parser:result.parser,reconciliation:result.reconciliation,detectedAccountNumber:result.statement?.accountNumberMasked||null},note:body.note,userId,statement:result.statement,reconciliation:result.reconciliation,transactions:result.transactions};let record;try{record=await repository.createWithDrafts(data,result.transactions);}catch(error){if(storageKey){try{await storage.deleteFile(storageKey);}catch(cleanupError){console.error('[ExpenseImport] Cannot compensate R2 upload after DB failure:',cleanupError.message);}}throw error;}return repository.detail(record.id);},
  async sourceUrl(id){const item=await repository.detail(id);if(!item)fail('Không tìm thấy lần import.',404,'STATEMENT_NOT_FOUND');if(!item.storage_key)fail('File nguồn chưa được lưu trên R2.',404,'STATEMENT_SOURCE_NOT_STORED');return{url:await storage.getSignedUrl(item.storage_key)};},
  async sourceFile(id){const item=await repository.detail(id);if(!item)fail('Không tìm thấy lần import.',404,'STATEMENT_NOT_FOUND');if(!item.storage_key)fail('File nguồn chưa được lưu trên R2.',404,'STATEMENT_SOURCE_NOT_STORED');const source=await storage.downloadBuffer(item.storage_key);return{...source,filename:item.original_filename};},
  async updateDrafts(id,body,userId){if(!Array.isArray(body.transactions)||!body.transactions.length)fail('Danh sách giao dịch không hợp lệ.',400,'STATEMENT_TRANSACTIONS_INVALID');const rows=normalizeDraftRows(body.transactions);const result=await repository.replaceDrafts(id,rows,body.revision,userId);if(!result)fail('Không tìm thấy lần import.',404,'STATEMENT_NOT_FOUND');if(result.conflict)fail('Preview đã được sửa ở phiên khác.',409,'STATEMENT_REVISION_CONFLICT',result);if(result.invalid)fail(`Không thể sửa import ở trạng thái ${result.status}.`,409,'STATEMENT_STATUS_INVALID');return repository.detail(id);},
  async commit(id,body,userId,requestId){const result=await repository.commit(id,body.revision,userId,requestId,fingerprint);if(!result)fail('Không tìm thấy lần import.',404,'STATEMENT_NOT_FOUND');if(result.already)fail('Sao kê đã được xác nhận.',409,'STATEMENT_ALREADY_COMMITTED');if(result.conflict)fail('Preview đã được sửa ở phiên khác.',409,'STATEMENT_REVISION_CONFLICT',result);if(result.validation)fail('Giao dịch còn lỗi dữ liệu.',400,'STATEMENT_TRANSACTION_INVALID',result);if(result.reconciliation)fail('Dữ liệu đã thay đổi hoặc chưa có đủ tổng sao kê để đối soát. Hãy lưu và kiểm tra lại.',409,'STATEMENT_RECONCILIATION_REQUIRED',result);if(result.invalid)fail(result.status==='reconciliation_failed'?'Sao kê chưa cân đối. Hãy sửa dữ liệu và lưu lại trước khi xác nhận.':`Không thể commit ở trạng thái ${result.status}.`,409,'STATEMENT_STATUS_INVALID');return result;},
  async cancel(id,userId){const result=await repository.cancel(id,userId);if(!result)fail('Không thể hủy sao kê đã commit hoặc không tồn tại.',409,'STATEMENT_CANCEL_INVALID');return result;},
  async remove(id,userId){const result=await repository.remove(id,userId);if(!result)fail('Không tìm thấy lịch sử import.',404,'STATEMENT_NOT_FOUND');if(result.protected)fail('Sao kê đã xác nhận và tạo dữ liệu giao dịch nên không được phép xóa.',409,'STATEMENT_DELETE_COMMITTED_FORBIDDEN');let sourceDeleted=!result.storageKey;if(result.storageKey){try{await storage.deleteFile(result.storageKey);sourceDeleted=true;}catch(error){console.error('[ExpenseImport] Cannot delete R2 source after removing draft import:',error.message);}}return{id:result.id,deleted:true,sourceDeleted};}
};
