const db=require('../../config/db');
const {DETAIL_ROW_CONFIG}=require('./detailRowConfig');
const {DETAIL_CONFIG}=require('./manualReportConfig');

module.exports={
  async list(teamCode){const result=await db.query(`SELECT r.*,t.code team_code,t.name team_name FROM report_detail_row_templates r JOIN report_teams t ON t.id=r.team_id WHERE t.code=$1 ORDER BY r.is_active DESC,r.display_order,r.created_at`,[teamCode]);return result.rows;},
  async create({teamCode,rowCode,rowName,isRequired}){return db.transaction(async client=>{const team=await client.query('SELECT id FROM report_teams WHERE code=$1 AND is_active=TRUE FOR UPDATE',[teamCode]);if(!team.rows[0])return null;const order=await client.query('SELECT COALESCE(MAX(display_order),0)+1 value FROM report_detail_row_templates WHERE team_id=$1',[team.rows[0].id]);const result=await client.query(`INSERT INTO report_detail_row_templates(team_id,row_code,row_name,display_order,is_required) VALUES($1,$2,$3,$4,$5) RETURNING *`,[team.rows[0].id,rowCode,rowName,order.rows[0].value,isRequired]);return result.rows[0];});},
  async update(id,{rowName,isRequired,isActive}){const result=await db.query('UPDATE report_detail_row_templates SET row_name=$2,is_required=$3,is_active=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *',[id,rowName,isRequired,isActive]);return result.rows[0]||null;},
  async reorder(teamCode,ids){return db.transaction(async client=>{const team=await client.query('SELECT id FROM report_teams WHERE code=$1 FOR UPDATE',[teamCode]);if(!team.rows[0])return null;const owned=await client.query('SELECT id FROM report_detail_row_templates WHERE team_id=$1 AND is_active=TRUE',[team.rows[0].id]);const expected=new Set(owned.rows.map(row=>row.id));if(ids.length!==expected.size||ids.some(id=>!expected.has(id)))return{conflict:true};for(const [index,id]of ids.entries())await client.query('UPDATE report_detail_row_templates SET display_order=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$1',[id,index+1]);return{updated:ids.length};});},
  async createPeriodRows(client,versionId){for(const [teamCode,config]of Object.entries(DETAIL_ROW_CONFIG)){const [table,columns]=DETAIL_CONFIG[config.detailKey];const templates=await client.query(`SELECT r.* FROM report_detail_row_templates r JOIN report_teams t ON t.id=r.team_id WHERE t.code=$1 AND r.is_active=TRUE ORDER BY r.display_order`,[teamCode]);for(const row of templates.rows){const data={row_key:row.row_code,display_order:row.display_order,[config.codeField]:row.row_code,[config.nameField]:row.row_name};const values=[versionId,...columns.map(column=>data[column]??null)];await client.query(`INSERT INTO ${table}(version_id,${columns.join(',')}) VALUES(${values.map((_,index)=>`$${index+1}`).join(',')})`,values);}}}
};
