const HttpError=require('../../http/httpError');
const repository=require('./detailRowConfigRepository');
const {DETAIL_ROW_CONFIG}=require('./detailRowConfig');
const team=value=>{const result=String(value||'').toUpperCase();if(!DETAIL_ROW_CONFIG[result])throw new HttpError('Bộ phận không hợp lệ.',400,'REPORT_TEAM_INVALID');return result;};
const required=(value,label)=>{const result=String(value||'').trim();if(!result)throw new HttpError(`${label} là bắt buộc.`,400,'REPORT_DETAIL_ROW_INVALID');return result;};
const section=(teamCode,value)=>{if(teamCode!=='ADS')return'primary';const result=String(value||'traffic');if(!['traffic','products'].includes(result))throw new HttpError('Khối chi tiết Ads không hợp lệ.',400,'REPORT_ADS_SECTION_INVALID');return result;};
async function rowGroup(teamCode,sectionKey,value){if(teamCode==='REV'||(teamCode==='ADS'&&sectionKey==='products')){const input=required(value,'Nhóm sản phẩm');const result=await require('../../config/db').query(`SELECT label FROM report_lookup_values WHERE category='product_group' AND is_active=TRUE AND (UPPER(code)=UPPER($1) OR UPPER(label)=UPPER($1)) LIMIT 1`,[input]);if(!result.rows[0])throw new HttpError('Nhóm sản phẩm không thuộc danh mục đang dùng.',400,'REPORT_PRODUCT_GROUP_INVALID');return result.rows[0].label;}return null;}
module.exports={
  list:query=>repository.list(team(query?.team)),
  async create(body){const teamCode=team(body?.teamCode),sectionKey=section(teamCode,body?.sectionKey),rowCode=required(body?.rowCode,'Mã dòng').toUpperCase();if(!/^[A-Z0-9_-]{2,80}$/.test(rowCode))throw new HttpError('Mã dòng chỉ gồm chữ, số, gạch ngang hoặc gạch dưới.',400,'REPORT_DETAIL_ROW_CODE_INVALID');try{return await repository.create({teamCode,rowCode,rowName:required(body?.rowName,'Tên dòng'),rowGroup:await rowGroup(teamCode,sectionKey,body?.rowGroup),sectionKey,isRequired:Boolean(body?.isRequired)});}catch(error){if(error.code==='23505')throw new HttpError('Mã dòng đã tồn tại trong bộ phận.',409,'REPORT_DETAIL_ROW_DUPLICATE');throw error;}},
  async update(id,body){const current=await repository.find(id);if(!current)throw new HttpError('Không tìm thấy dòng mẫu.',404,'REPORT_DETAIL_ROW_NOT_FOUND');const sectionKey=section(current.team_code,body?.sectionKey||current.section_key);return repository.update(id,{rowName:required(body?.rowName,'Tên dòng'),rowGroup:await rowGroup(current.team_code,sectionKey,body?.rowGroup),sectionKey,isRequired:Boolean(body?.isRequired),isActive:body?.isActive!==false});},
  async reorder(body){const teamCode=team(body?.teamCode),sectionKey=section(teamCode,body?.sectionKey);const ids=Array.isArray(body?.ids)?body.ids.map(String):[];if(!ids.length)throw new HttpError('Danh sách dòng không hợp lệ.',400,'REPORT_DETAIL_ROW_ORDER_INVALID');const result=await repository.reorder(teamCode,sectionKey,ids);if(!result)throw new HttpError('Không tìm thấy bộ phận.',404,'REPORT_TEAM_NOT_FOUND');if(result.conflict)throw new HttpError('Danh sách dòng không khớp khối chi tiết hiện tại.',409,'REPORT_DETAIL_ROW_ORDER_CONFLICT');return result;}
};
