const TEAM_ENTRY_CONFIG = {
  REV:{detailKey:'revenue',title:'Doanh thu theo sản phẩm',instructions:['Mỗi sản phẩm một dòng; không nhập trùng sản phẩm.','Doanh thu và số đơn phải đối soát với nguồn bán hàng.'],fields:[
    ['product_group','Nhóm sản phẩm','select','product_group',true],['product_name','Sản phẩm','text',null,true],['order_count','Số đơn','number'],['revenue','Doanh thu','number'],['monthly_target','KH tháng','number'],['note','Ghi chú','text']]},
  ADS:{detailKey:'adsChannels',title:'Hiệu quả theo nguồn Ads',instructions:['Mỗi nguồn traffic một dòng.','Lead, đơn và doanh thu phải dùng cùng quy tắc attribution.'],fields:[
    ['traffic_source','Nguồn traffic','select','ads_source',true],['budget_target','KH ngân sách','number'],['budget_actual','NS thực hiện','number'],['lead_count','Lead / Data','number'],['order_count','Đơn hàng','number'],['revenue','Doanh thu','number'],['trend','Xu hướng','text'],['note','Ghi chú','text']]},
  COM:{detailKey:'social',title:'Hiệu quả theo kênh truyền thông',instructions:['Mỗi kênh một dòng; Followers và Reach kỳ trước tự lấy từ số kỳ này của cùng kênh ở tháng trước.','Engagement Rate nhập theo từng kênh; Tỷ lệ Organic và Ngân sách Content nhập tại KPI tổng hợp.'],fields:[
    ['channel_name','Kênh','select','social_channel',true],['followers_current','Followers kỳ này','number'],['followers_previous','Followers kỳ trước','computed','followers_previous'],['followers_growth','Tăng trưởng Followers','computed','followers_growth'],['reach_current','Reach kỳ này','number'],['reach_previous','Reach kỳ trước','computed','reach_previous'],['reach_growth','% vs TTr Reach','computed','reach_growth'],['video_views','View Video','number'],['engagement_rate','Engagement Rate','number'],['lead_count','Data','number'],['revenue','Doanh thu','number'],['note','Ghi chú','text']]},
  TRADE:{detailKey:'trade',title:'Chi tiết trường / sự kiện',instructions:['Ngày triển khai có thể là một ngày, một khoảng liên tục hoặc nhiều ngày rời rạc.','Số ngày là cột nhập tay; Workshop, Reach, Data, Ngân sách và Doanh thu được hệ thống tự cộng.'],fields:[
    ['organization_name','Trường / Đơn vị','text',null,true],['organization_type','Loại trường','select','school_type'],['region','Vùng miền','select','region'],['activity_date_text','Ngày triển khai','date_text'],['activity_days','Số ngày','number'],['workshop_count','Workshop','number'],['reach','Reach','number'],['lead_count','Data','number'],['budget','Ngân sách','number'],['revenue','Doanh thu','number'],['note','Ghi chú','text']]},
  TRAIN:{detailKey:'training',title:'Kết quả theo khóa học',instructions:['Mỗi khóa học một dòng.','Giáo viên Active không được cộng trùng giữa các khóa; cần đối soát trước khi gửi.'],fields:[
    ['course_name','Khóa học','text',null,true],['class_count','Số lớp','number'],['active_student_count','HV đang đào tạo','number'],['student_target','KH học viên','number'],['student_achievement','% HT KH','computed','student_achievement'],['new_student_count','HV mới','number'],['completed_student_count','HV kết thúc','number'],['teacher_count','Số giáo viên','number'],['output_rate','Tỷ lệ đạt đầu ra','number'],['upsell_revenue','Doanh thu học lên','number'],['status','Tình trạng','select','training_status'],['note','Ghi chú','text']]},
  PROD:{detailKey:'products',title:'Công việc / sản phẩm',instructions:['Mỗi đầu ra hoặc hoạt động một dòng.','Các KPI sản phẩm Phase 2.1 nhập trực tiếp; detail dùng để giải trình và đối soát.'],fields:[
    ['product_group','Nhóm sản phẩm','select','product_group'],['activity_name','Tên sản phẩm / hoạt động','text',null,true],['activity_type','Loại hoạt động','select','product_activity'],['owner_unit','Đơn vị phụ trách','text'],['cooperating_unit','Đơn vị phối hợp','text'],['next_action','Kế hoạch kỳ','text'],['implementation_result','Kết quả thực hiện','text'],['progress_status','Tiến độ','select','product_progress'],['actual_end_date','Ngày hoàn thành','date'],['output_url','Link tài liệu','text'],['note','Ghi chú','text']]}
};

const DETAIL_CONFIG = {
  revenue:['report_revenue_details',['row_key','display_order','product_group','product_code','product_name','order_count','revenue','monthly_target','previous_revenue','prior_year_revenue','note']],
  adsChannels:['report_ads_channel_details',['row_key','display_order','channel_code','traffic_source','budget_target','budget_actual','lead_count','order_count','revenue','previous_revenue','trend','note']],
  adsProducts:['report_ads_product_details',['row_key','display_order','product_group','product_code','product_name','ad_cost','revenue','lead_count','qualified_lead_count','order_count','note']],
  social:['report_social_details',['row_key','display_order','channel_code','channel_name','followers_current','followers_previous','reach_current','reach_previous','organic_reach','video_views','engagement_count','engagement_rate','lead_count','order_count','revenue','budget','note']],
  trade:['report_trade_details',['row_key','display_order','organization_code','organization_name','organization_type','region','activity_type','activity_date_text','activity_days','workshop_count','social_post_count','reach','lead_count','order_count','budget','revenue','is_new_contract','note']],
  training:['report_training_details',['row_key','display_order','course_code','course_name','class_count','active_student_count','student_target','new_student_count','completed_student_count','evaluated_student_count','qualified_student_count','output_rate','teacher_count','started_class_count','completed_class_count','upsell_revenue','upsell_revenue_target','status','note']],
  products:['report_product_details',['row_key','display_order','product_group','activity_code','activity_name','activity_type','kpi_code','contribution_value','progress_percent','owner_unit','cooperating_unit','planned_start_date','planned_end_date','actual_start_date','actual_end_date','target_quantity','actual_quantity','progress_status','output_url','implementation_result','evaluation_result','next_action','note']]
};

module.exports={TEAM_ENTRY_CONFIG,DETAIL_CONFIG};
