const HttpError=require('../../http/httpError');
const repository=require('./manualReportRepository');
const dashboardRepository=require('./reportRepository');
const {TEAM_ENTRY_CONFIG,DETAIL_CONFIG}=require('./manualReportConfig');
const {calculate,validateWorkspace,reconcileWorkspace}=require('./manualReportCalculator');
const workbookService=require('./manualReportWorkbook');
const {enrichRevenueDetails}=require('./reportRevenueMetrics');
const {enrichKpiHistory,enrichSocialHistory,applyComKpiFallback,rate}=require('./reportHistoryMetrics');
const {sendReportNotification}=require('../../services/emailService');
const {parseDeploymentDate}=require('./reportDateFormat');
const normalizedKey=value=>String(value||'').trim().toLowerCase().replace(/\s+/g,' ');
const FIXED_IDENTITIES={REV:['product_group','product_name'],ADS:['traffic_source'],COM:['channel_name'],TRAIN:['course_name']};
function preserveFixedRows(teamCode,currentRows,incomingRows,identityFields=FIXED_IDENTITIES[teamCode]){
  if(!identityFields)return incomingRows;
  const identity=row=>identityFields.map(field=>normalizedKey(row[field])).join('|');
  const currentByIdentity=new Map(currentRows.map(row=>[identity(row),row]));
  if(incomingRows.length!==currentRows.length||incomingRows.some(row=>!currentByIdentity.has(identity(row))))throw new HttpError('Danh sách dòng của phiếu đã được cố định theo cấu hình kỳ. Chỉ được cập nhật các cột nhập liệu.',409,'REPORT_DETAIL_ROWS_LOCKED');
  return incomingRows.map(row=>{const source=currentByIdentity.get(identity(row));return{...row,row_key:source.row_key,display_order:source.display_order,...Object.fromEntries(identityFields.map(field=>[field,source[field]]))};});
}
const appUrl=()=>String(process.env.APP_URL||'http://localhost:5173').replace(/\/$/,'');
async function notifyAssignee(context,eventName,message){if(!context?.email)return;try{await sendReportNotification({email:context.email,name:context.user_name,eventName,periodLabel:`Tháng ${context.month}/${context.year}`,teamName:context.team_name,deadline:context.submission_deadline,actionUrl:`${appUrl()}/reports/manage/${context.period_id}/${context.team_code}`,message});}catch(error){console.error('[Report email]',error.message);}}

const validPeriod=(year,month)=>{year=Number(year);month=Number(month);if(!Number.isInteger(year)||year<2000||year>2100||!Number.isInteger(month)||month<1||month>12)throw new HttpError('Kỳ báo cáo không hợp lệ.',400,'REPORT_PERIOD_INVALID');return{year,month};};
const numeric=value=>value===null||value===undefined||value===''?null:Number(value);
const decimal=value=>{
  if(value===null||value===undefined||value==='')return null;
  const text=String(value).trim();
  return /^-?\d+(?:\.\d+)?$/.test(text)&&Number.isFinite(Number(text))?text:null;
};
const direction=value=>['increase_good','decrease_good','monitor'].includes(value)?value:'monitor';
const DATE_COLUMNS=new Set(['planned_start_date','planned_end_date','actual_start_date','actual_end_date']);
const normalizeDate=(value,rowNumber,column)=>{
  if(value===null||value===undefined||value==='')return null;
  const text=String(value).trim();
  const iso=text.match(/^(\d{4}-\d{2}-\d{2})/);
  if(iso)return iso[1];
  const date=new Date(text);
  if(Number.isNaN(date.getTime()))throw new HttpError(`Dòng ${rowNumber}: ${column} không đúng định dạng ngày.`,400,'REPORT_DATE_INVALID');
  return date.toISOString().slice(0,10);
};
const evaluation=(target,actual,directionValue)=>target===null||actual===null?null:directionValue==='monitor'?'Theo dõi':directionValue==='increase_good'?(actual>=target?'Đạt':'Chưa đạt'):(actual<=target?'Đạt':'Chưa đạt');
const achievement=(target,actual,directionValue)=>target===null||actual===null||directionValue==='monitor'?null:directionValue==='decrease_good'?(actual<=0?1.2:target/actual):(target===0?(actual>0?1.2:null):actual/target);
function sanitizeRows(detailKey,rows) {
  const columns=new Set(DETAIL_CONFIG[detailKey][1]);
  return (Array.isArray(rows)?rows:[]).map((row,index)=>Object.fromEntries([...columns].map(key=>{const value=row?.[key]===''||row?.[key]===undefined?null:row[key];if(key==='activity_date_text'&&value!==null){const parsed=parseDeploymentDate(value);if(!parsed)throw new HttpError(`Dòng ${index+1}: Ngày triển khai phải là một ngày, một khoảng ngày hoặc danh sách ngày phân cách bằng dấu chấm phẩy.`,400,'REPORT_DATE_INVALID');return[key,parsed];}return[key,DATE_COLUMNS.has(key)?normalizeDate(value,index+1,key):value];})));
}
async function workspace(periodId,teamCode) {
  teamCode=String(teamCode||'').toUpperCase();const baseConfig=TEAM_ENTRY_CONFIG[teamCode];if(!baseConfig)throw new HttpError('Bộ phận không hợp lệ.',400,'REPORT_TEAM_INVALID');
  const base=await repository.getWorkspace(periodId,teamCode);if(!base)throw new HttpError('Không tìm thấy phiếu nhập liệu.',404,'REPORT_WORKSPACE_NOT_FOUND');
  const config={...baseConfig,fields:baseConfig.fields.map(([key,label,type,lookup,required=false])=>({key,label,type,lookup,required}))};
  let details=await repository.getDetails(base.version_id,config.detailKey);
  if(teamCode==='REV') {
    const history=await repository.getRevenueHistory(base.year,base.month,base.version_id);
    details=enrichRevenueDetails(details,history);
  }
  if(teamCode==='COM'){const history=await repository.getSocialHistory(base.year,base.month,base.version_id);details=enrichSocialHistory(details,history).map(row=>({...row,followers_growth:rate(numeric(row.followers_current),numeric(row.followers_previous)),reach_growth:rate(numeric(row.reach_current),numeric(row.reach_previous))}));}
  if(teamCode==='TRAIN')details=details.map(row=>({...row,student_achievement:numeric(row.student_target)?numeric(row.active_student_count)/numeric(row.student_target):null,output_rate:numeric(row.evaluated_student_count)?numeric(row.qualified_student_count)/numeric(row.evaluated_student_count):null}));
  let adsProducts=[];
  if(teamCode==='ADS')adsProducts=await repository.getDetails(base.version_id,'adsProducts');
  const history=await repository.getKpiHistory(base.year,base.month,teamCode,base.version_id);
  const kpiRows=teamCode==='COM'?applyComKpiFallback(base.kpis,details):base.kpis;
  const kpis=enrichKpiHistory(kpiRows.map(kpi=>({...kpi,team_code:teamCode})),history).map(kpi=>{const target=numeric(kpi.target_value),actual=numeric(kpi.actual_value);return{...kpi,achievement_rate:achievement(target,actual,kpi.evaluation_direction),evaluation:evaluation(target,actual,kpi.evaluation_direction)};});
  return {...base,kpis,config,details,adsProducts};
}

function canAccessAllForms(auth={}) {return ['reports.forms.view','reports.manage','reports.review','reports.assign','reports.publish'].some(key=>auth.permissions?.includes(key));}
function ensureFormAccess(current,auth,write=false) {
  if(!write&&canAccessAllForms(auth))return;
  if(write&&!current.assigned_user_id)throw new HttpError('Phiếu chưa được phân công người thực hiện.',409,'REPORT_SUBMISSION_UNASSIGNED');
  if(write&&current.submission_deadline&&new Date(current.submission_deadline)<new Date()&&!auth.permissions?.includes('reports.manage'))throw new HttpError('Đã quá hạn nhập liệu. Vui lòng liên hệ quản trị báo cáo để gia hạn.',409,'REPORT_SUBMISSION_DEADLINE_PASSED');
  if(!['reports.entry','reports.review','reports.manage'].some(key=>auth.permissions?.includes(key))||String(current.assigned_user_id||'')!==String(auth.userId||''))
    throw new HttpError(write?'Bạn chỉ được nhập phiếu đã được phân công.':'Bạn không được phân công xem phiếu này.',403,'REPORT_SUBMISSION_NOT_ASSIGNED');
}

module.exports={
  async list(query,auth){const year=query?.year?Number(query.year):null;if(year&&(!Number.isInteger(year)||year<2000||year>2100))throw new HttpError('Năm báo cáo không hợp lệ.',400,'REPORT_YEAR_INVALID');const status=query?.status?String(query.status):null;return repository.listPeriods({year,status,assignedUserId:canAccessAllForms(auth)?null:auth?.userId});},
  async create(body,userId){const {year,month}=validPeriod(body?.year,body?.month);const deadline=body?.deadline?new Date(body.deadline):null;if(deadline&&Number.isNaN(deadline.getTime()))throw new HttpError('Hạn nhập liệu không hợp lệ.',400,'REPORT_DEADLINE_INVALID');const result=await repository.createPeriod({year,month,deadline,userId,copyTargets:body?.copyTargets!==false});if(result.locked)throw new HttpError('Kỳ báo cáo đã khóa, cần mở lại kỳ trước khi tạo phiên nhập liệu.',409,'REPORT_PERIOD_LOCKED');if(result.conflict)throw new HttpError('Kỳ này đã có phiên nhập liệu đang mở.',409,'REPORT_MANUAL_DRAFT_EXISTS');return result;},
  async find(query,auth){const {year,month}=validPeriod(query.year,query.month);const result=await repository.findPeriod(year,month);if(!result)throw new HttpError('Kỳ báo cáo chưa được tạo.',404,'REPORT_PERIOD_NOT_FOUND');if(!canAccessAllForms(auth)){result.submissions=(result.submissions||[]).filter(item=>String(item.assignedUserId||'')===String(auth?.userId||''));if(!result.submissions.length)throw new HttpError('Bạn chưa được phân công phiếu trong kỳ báo cáo này.',403,'REPORT_SUBMISSION_NOT_ASSIGNED');}return result;},
  async get(periodId,auth){const result=await repository.getPeriod(periodId);if(!result)throw new HttpError('Không tìm thấy kỳ báo cáo.',404,'REPORT_PERIOD_NOT_FOUND');if(!canAccessAllForms(auth))result.submissions=(result.submissions||[]).filter(item=>String(item.assignedUserId||'')===String(auth?.userId||''));return result;},
  async workspace(periodId,teamCode,auth){const current=await workspace(periodId,teamCode);ensureFormAccess(current,auth);const isAssignee=String(current.assigned_user_id||'')===String(auth?.userId||''),deadlineOpen=!current.submission_deadline||new Date(current.submission_deadline)>=new Date()||auth?.permissions?.includes('reports.manage');return{...current,capabilities:{canEdit:Boolean(current.assigned_user_id&&isAssignee&&deadlineOpen&&['reports.entry','reports.review','reports.manage'].some(key=>auth?.permissions?.includes(key))),deadlinePassed:Boolean(current.submission_deadline&&new Date(current.submission_deadline)<new Date()),canReview:['reports.review','reports.manage'].some(key=>auth?.permissions?.includes(key)),canPublish:['reports.publish','reports.manage'].some(key=>auth?.permissions?.includes(key))}};},
  async exportTemplate(periodId,teamCode,auth){const current=await workspace(periodId,teamCode);ensureFormAccess(current,auth);current.masterData=await repository.getMasterData();return{buffer:workbookService.buildTemplate(current),fileName:`Bao_cao_${current.team_code}_Thang_${current.month}_${current.year}.xlsx`};},
  async importTemplate(periodId,teamCode,body,auth){const current=await workspace(periodId,teamCode);ensureFormAccess(current,auth,true);if(!['draft','editing','returned'].includes(current.submission_status))throw new HttpError('Phiếu nhập liệu không còn ở trạng thái chỉnh sửa.',409,'REPORT_SUBMISSION_LOCKED');const encoded=String(body?.fileBase64||'').replace(/^data:.*?;base64,/,'');if(!encoded)throw new HttpError('Vui lòng chọn file Excel.',400,'REPORT_TEMPLATE_FILE_REQUIRED');current.masterData=await repository.getMasterData();const parsed=workbookService.parseTemplate(Buffer.from(encoded,'base64'),current);try{parsed.details=preserveFixedRows(current.team_code,current.details,parsed.details);if(current.team_code==='ADS')parsed.adsProducts=preserveFixedRows('ADS',current.adsProducts,parsed.adsProducts,['product_group','product_name']);}catch(error){if(error.code==='REPORT_DETAIL_ROWS_LOCKED')parsed.errors.push(error.message);else throw error;}return parsed;},
  async save(periodId,teamCode,body,userId,auth){const current=await workspace(periodId,teamCode);ensureFormAccess(current,auth,true);const config={detailKey:current.config.detailKey,fields:current.config.fields.map(field=>[field.key,field.label,field.type,field.lookup,field.required])};if(!['draft','editing','returned'].includes(current.submission_status))throw new HttpError('Phiếu nhập liệu không còn ở trạng thái chỉnh sửa.',409,'REPORT_SUBMISSION_LOCKED');
    let rows=sanitizeRows(config.detailKey,body?.details);rows=preserveFixedRows(current.team_code,current.details,rows);if(current.team_code==='COM')rows=enrichSocialHistory(rows,await repository.getSocialHistory(current.year,current.month,current.version_id));let adsProducts=current.team_code==='ADS'?sanitizeRows('adsProducts',body?.adsProducts):[];if(current.team_code==='ADS')adsProducts=preserveFixedRows('ADS',current.adsProducts,adsProducts,['product_group','product_name']);const incomingRows=Array.isArray(body?.kpis)?body.kpis:[];const incoming=new Map(incomingRows.map(item=>[String(item.code||'').trim().toUpperCase(),item]));
    const expectedCodes=current.kpis.map(item=>item.code);const incomingCodes=incomingRows.map(item=>String(item.code||'').trim().toUpperCase());
    if(incomingCodes.length!==expectedCodes.length||expectedCodes.some(code=>!incoming.has(code)))throw new HttpError('Bộ KPI của phiếu đã được cố định theo cấu hình kỳ báo cáo.',409,'REPORT_KPI_SET_LOCKED');
    const derived=calculate(current.team_code,rows,{});
    const kpis=current.kpis.map(kpi=>{const item=incoming.get(kpi.code)||{};const directionValue=direction(kpi.evaluation_direction);const target=decimal(item.target_value);const manualActual=decimal(item.actual_value);const formulaCode=kpi.formula_code||kpi.code;const actual=kpi.input_mode==='derived'&&Object.hasOwn(derived,formulaCode)?decimal(derived[formulaCode]):manualActual;return{...kpi,target_value:target,actual_value:actual,evaluation:evaluation(numeric(target),numeric(actual),directionValue),note:item.note||null};});
    const validation=validateWorkspace(kpis,rows,config.fields),reconciliation=reconcileWorkspace(current.team_code,kpis,rows,adsProducts);validation.errors.push(...reconciliation.errors);validation.warnings.push(...reconciliation.warnings);validation.errors=[...new Set(validation.errors)];validation.warnings=[...new Set(validation.warnings)];const result=await repository.saveWorkspace({base:current,detailKey:config.detailKey,rows,extraDetails:current.team_code==='ADS'?{detailKey:'adsProducts',rows:adsProducts}:null,kpis,note:body?.note||{},validation,userId,expectedRevision:body?.revision,auditAction:body?.auditAction==='save_draft'?'draft_saved':null});if(!result)throw new HttpError('Không tìm thấy phiếu nhập liệu.',404,'REPORT_WORKSPACE_NOT_FOUND');if(result.conflict)throw new HttpError(`Phiếu đang ở trạng thái ${result.status}.`,409,'REPORT_SUBMISSION_STATE_INVALID');if(result.stale)throw new HttpError('Phiếu đã được cập nhật ở cửa sổ khác. Hãy tải lại trước khi tiếp tục.',409,'REPORT_REVISION_CONFLICT',{revision:result.revision});return workspace(periodId,teamCode);},
  async transition(periodId,teamCode,body,userId,auth){const action=String(body?.action||'');const note=String(body?.note||'').trim();teamCode=String(teamCode).toUpperCase();if(['return','recall'].includes(action)&&note.length<5)throw new HttpError('Vui lòng nhập lý do thu hồi/trả lại phiếu (ít nhất 5 ký tự).',400,'REPORT_RETURN_REASON_REQUIRED');const current=await workspace(periodId,teamCode);if(action==='submit')ensureFormAccess(current,auth,true);if(['approve','return','recall'].includes(action)&&!['reports.review','reports.manage'].some(key=>auth.permissions?.includes(key)))throw new HttpError('Bạn không có quyền duyệt báo cáo.',403,'PERMISSION_DENIED');const result=await repository.transition({periodId,teamCode,action,note,userId});if(!result)throw new HttpError('Không tìm thấy phiếu nhập liệu.',404,'REPORT_WORKSPACE_NOT_FOUND');if(result.conflict)throw new HttpError(`Không thể ${action} khi phiếu ở trạng thái ${result.status}.`,409,'REPORT_SUBMISSION_STATE_INVALID');if(result.validation)throw new HttpError('Phiếu còn lỗi dữ liệu, chưa thể gửi duyệt.',400,'REPORT_VALIDATION_FAILED',result.validation);if(['return','recall'].includes(action)){const context=await repository.notificationContext(periodId,teamCode);if(context){context.period_id=periodId;await notifyAssignee(context,action==='recall'?'Phiếu báo cáo được thu hồi để sửa':'Phiếu báo cáo được trả lại',`Phiếu cần được cập nhật lại. Lý do: ${note}`);}}return result;},
  async assignees(){return repository.listAssignees();},
  async assign(periodId,teamCode,body,actorId){const userId=body?.userId||null;teamCode=String(teamCode).toUpperCase();const result=await repository.assignSubmission({periodId,teamCode,userId,actorId});if(!result)throw new HttpError('Không tìm thấy phiếu đang mở để phân công.',404,'REPORT_WORKSPACE_NOT_FOUND');if(result.invalidUser)throw new HttpError('Người được chọn không hoạt động hoặc chưa có quyền nhập/duyệt báo cáo.',400,'REPORT_ASSIGNEE_INVALID');if(result.locked)throw new HttpError('Không thể đổi người thực hiện khi phiếu đang chờ duyệt hoặc đã duyệt.',409,'REPORT_ASSIGNMENT_LOCKED');if(userId){const context=await repository.notificationContext(periodId,teamCode,userId);if(context){context.period_id=periodId;await notifyAssignee(context,'Bạn được phân công phiếu báo cáo','Bạn đã được phân công nhập dữ liệu cho phiếu báo cáo này.');}}return repository.getPeriod(periodId);},
  async updateDeadline(periodId,body,actorId){const deadline=body?.deadline?new Date(body.deadline):null;if(body?.deadline&&Number.isNaN(deadline.getTime()))throw new HttpError('Hạn nhập liệu không hợp lệ.',400,'REPORT_DEADLINE_INVALID');const result=await repository.updateDeadline(periodId,deadline,actorId);if(!result)throw new HttpError('Không tìm thấy kỳ báo cáo.',404,'REPORT_PERIOD_NOT_FOUND');if(result.protected)throw new HttpError('Không thể thay đổi hạn của kỳ đã publish hoặc đã khóa.',409,'REPORT_DEADLINE_LOCKED');return result;},
  async audit(periodId,query,auth){const limit=Math.min(100,Math.max(1,Number(query?.limit)||50)),teamCode=query?.teamCode?String(query.teamCode).toUpperCase():null;if(!canAccessAllForms(auth)){if(!teamCode)throw new HttpError('Vui lòng chọn phiếu cần xem lịch sử.',400,'REPORT_TEAM_REQUIRED');const current=await workspace(periodId,teamCode);ensureFormAccess(current,auth);}return repository.listAudit(periodId,{teamCode,limit});},
  async checklist(periodId){return repository.publishChecklist(periodId);},
  async preview(periodId,teamCode,auth){const current=await workspace(periodId,teamCode);ensureFormAccess(current,auth);const result=await dashboardRepository.getDashboard({periodId,draft:true,teamCode:String(teamCode).toUpperCase()});if(!result)throw new HttpError('Chưa có dữ liệu nháp để xem trước.',404,'REPORT_PREVIEW_NOT_FOUND');return{...result,preview:true};},
  async publish(periodId,userId){const result=await repository.publish(periodId,userId);if(!result)throw new HttpError('Không tìm thấy kỳ báo cáo.',404,'REPORT_PERIOD_NOT_FOUND');if(result.noDraft)throw new HttpError('Kỳ không có phiên nhập liệu để publish.',409,'REPORT_MANUAL_DRAFT_NOT_FOUND');if(result.unassigned)throw new HttpError(`Còn ${result.unassigned} phiếu chưa được phân công.`,409,'REPORT_TEAMS_UNASSIGNED');if(result.pending)throw new HttpError(`Còn ${result.pending} bộ phận chưa được duyệt.`,409,'REPORT_TEAMS_PENDING');return result;},
  async reopen(periodId,userId,body){const reason=String(body?.reason||'').trim();if(reason.length<5)throw new HttpError('Vui lòng nhập lý do thu hồi báo cáo (ít nhất 5 ký tự).',400,'REPORT_REOPEN_REASON_REQUIRED');const result=await repository.reopen(periodId,userId,reason);if(!result)throw new HttpError('Không tìm thấy kỳ báo cáo.',404,'REPORT_PERIOD_NOT_FOUND');if(result.conflict)throw new HttpError('Chỉ có thể thu hồi kỳ đã publish.',409,'REPORT_PERIOD_NOT_PUBLISHED');if(result.draftExists)throw new HttpError('Kỳ báo cáo đã có phiên chỉnh sửa đang mở.',409,'REPORT_MANUAL_DRAFT_EXISTS');return result;},
  async remove(periodId){const result=await repository.deletePeriod(periodId);if(!result)throw new HttpError('Không tìm thấy kỳ báo cáo.',404,'REPORT_PERIOD_NOT_FOUND');if(result.protected)throw new HttpError('Không thể xóa kỳ đã publish hoặc đã khóa.',409,'REPORT_PERIOD_DELETE_PROTECTED');return result;}
};
