const HttpError=require('../../http/httpError');
const repo=require('./examEventRepository');
const media=require('./examEventMediaService');
const {validateExamEventInput,validateMediaUpload,validateEventId,validateListFilters}=require('./examEventValidator');
function persistenceError(error){if(error?.code==='23505')return new HttpError('Mã kỳ thi đã tồn tại.',409,'EVENT_CODE_EXISTS');if(error?.code==='23503')return new HttpError('Dữ liệu liên kết của kỳ thi không hợp lệ.',409,'EXAM_EVENT_REFERENCE_CONFLICT');return error;}
function sameDate(left,right){return new Date(left).getTime()===new Date(right).getTime();}
function assertLifecycleUpdate(current,data){
  if(!['IN_PROGRESS','COMPLETED'].includes(current.lifecycleStatus))return;
  const changed=(key)=>data[key]!==undefined&&data[key]!==current[key];
  const examChanged=data.examId!==undefined&&data.examId!==current.exam?.id;
  const structuralChanged=examChanged||changed('status')||(data.startAt!==undefined&&!sameDate(data.startAt,current.startAt))||(data.endAt!==undefined&&!sameDate(data.endAt,current.endAt));
  if(structuralChanged)throw new HttpError(current.lifecycleStatus==='IN_PROGRESS'?'Không thể đổi đề thi, lịch thi hoặc trạng thái khi kỳ thi đang diễn ra.':'Không thể đổi đề thi, lịch thi hoặc trạng thái của kỳ thi đã kết thúc.',409,'EXAM_EVENT_LIFECYCLE_LOCKED');
}
async function formatEventOutput(event){if(!event)return event;const {imageStorageKey,bannerStorageKey,...safe}=event;return {...safe,imageUrl:await media.getSignedMediaUrl(imageStorageKey),bannerUrl:await media.getSignedMediaUrl(bannerStorageKey)};}
async function list(filters){validateListFilters(filters);const result=await repo.list(filters);return {...result,data:await Promise.all(result.data.map(formatEventOutput))};}
async function get(id){validateEventId(id);const event=await repo.findById(id);if(!event)throw new HttpError('Không tìm thấy kỳ thi.',404,'EXAM_EVENT_NOT_FOUND');return formatEventOutput(event);}
async function ensureExam(id){const exam=await repo.findExamById(id);if(!exam)throw new HttpError('Không tìm thấy đề thi áp dụng.',404,'EXAM_NOT_FOUND');if(exam.status!=='ACTIVE')throw new HttpError('Chỉ có thể sử dụng đề thi đang hoạt động.',409,'EXAM_NOT_ACTIVE');return exam;}
async function ensureSchool(name){const school=await repo.findSchoolByName(String(name||'').trim());if(!school)throw new HttpError('Trường đã chọn không tồn tại trong danh mục.',409,'SCHOOL_NOT_FOUND');return school;}
async function createExamEvent(data,userId){validateExamEventInput(data);await Promise.all([ensureExam(data.examId),ensureSchool(data.schoolName)]);try{return formatEventOutput(await repo.create(data,userId));}catch(error){throw persistenceError(error);}}
async function updateExamEvent(id,data,userId){validateEventId(id);const current=await repo.findById(id);if(!current)throw new HttpError('Không tìm thấy kỳ thi.',404,'EXAM_EVENT_NOT_FOUND');assertLifecycleUpdate(current,data);const merged={...current,examId:current.exam?.id,...data};validateExamEventInput(merged);if(data.eventCode!==undefined&&!String(data.eventCode).trim())throw new HttpError('Mã kỳ thi không được để trống.',400,'INVALID_EVENT_CODE');const checks=[];if(data.examId!==undefined)checks.push(ensureExam(data.examId));if(data.schoolName!==undefined)checks.push(ensureSchool(data.schoolName));await Promise.all(checks);try{return formatEventOutput(await repo.update(id,data,userId));}catch(error){throw persistenceError(error);}}
async function createSchool(data,userId){const name=String(data?.name||'').trim();if(!name)throw new HttpError('Tên trường là bắt buộc.',400,'SCHOOL_NAME_REQUIRED');if(name.length>240)throw new HttpError('Tên trường không được vượt quá 240 ký tự.',400,'SCHOOL_NAME_TOO_LONG');const existing=await repo.findSchoolByName(name);if(existing)return existing;try{return await repo.createSchool(name,userId);}catch(error){if(error?.code==='23505')return repo.findSchoolByName(name);throw persistenceError(error);}}
async function removeExamEvent(id){validateEventId(id);const event=await repo.findById(id);if(!event)throw new HttpError('Không tìm thấy kỳ thi.',404,'EXAM_EVENT_NOT_FOUND');if(event.lifecycleStatus==='IN_PROGRESS')throw new HttpError('Không thể xóa kỳ thi đang diễn ra.',409,'EXAM_EVENT_IN_PROGRESS');if(event.candidateCount>0)throw new HttpError('Không thể xóa kỳ thi đã có thí sinh.',409,'EXAM_EVENT_HAS_CANDIDATES');const deleted=await repo.removeIfAllowed(id);if(!deleted.rows[0])throw new HttpError('Kỳ thi vừa thay đổi và hiện không thể xóa.',409,'EXAM_EVENT_DELETE_CONFLICT');}
async function uploadMedia(id,kind,file){validateEventId(id);if(!['image','banner'].includes(kind))throw new HttpError('Loại ảnh không hợp lệ.',400,'INVALID_MEDIA_KIND');validateMediaUpload(file);const current=await repo.findById(id);if(!current)throw new HttpError('Không tìm thấy kỳ thi.',404,'EXAM_EVENT_NOT_FOUND');const oldKey=kind==='banner'?current.bannerStorageKey:current.imageStorageKey;const storageKey=await media.uploadEventMedia(id,kind,file);let updated;try{updated=await repo.updateMedia(id,kind,{storageKey,mimeType:file.mimetype,fileSize:file.size});}catch(error){await media.removeEventMedia(storageKey).catch(cleanupError=>console.error('[ExamEventMedia] Cannot compensate upload:',cleanupError.message));throw persistenceError(error);}if(oldKey&&oldKey!==storageKey)await media.removeEventMedia(oldKey).catch(error=>console.error('[ExamEventMedia] Cannot remove replaced file:',error.message));return formatEventOutput(updated);}
async function removeMedia(id,kind){validateEventId(id);if(!['image','banner'].includes(kind))throw new HttpError('Loại ảnh không hợp lệ.',400,'INVALID_MEDIA_KIND');const current=await repo.findById(id);if(!current)throw new HttpError('Không tìm thấy kỳ thi.',404,'EXAM_EVENT_NOT_FOUND');const oldKey=kind==='banner'?current.bannerStorageKey:current.imageStorageKey;const updated=await repo.clearMedia(id,kind);if(oldKey)await media.removeEventMedia(oldKey).catch(error=>console.error('[ExamEventMedia] Cannot remove file:',error.message));return formatEventOutput(updated);}
module.exports={list,get,createExamEvent,updateExamEvent,removeExamEvent,uploadMedia,removeMedia,schools:repo.schools,createSchool,formatEventOutput};
