const STATUSES=['DRAFT','PUBLISHED','ARCHIVED'];
const LIFECYCLE_STATUSES=['DRAFT','UPCOMING','IN_PROGRESS','COMPLETED','ARCHIVED'];
const ALLOWED_IMAGE_MIME_TYPES=['image/jpeg','image/png','image/webp'];
const MAX_IMAGE_FILE_SIZE=10*1024*1024;
const PAGINATION={DEFAULT_PAGE:1,DEFAULT_LIMIT:20,MAX_LIMIT:100};
module.exports={STATUSES,LIFECYCLE_STATUSES,ALLOWED_IMAGE_MIME_TYPES,MAX_IMAGE_FILE_SIZE,PAGINATION};
