const crypto=require('crypto');
const db=require('../../config/db');
const {PAGINATION}=require('./examEventConstants');
const lifecycleSql=`CASE WHEN ee.status='DRAFT' THEN 'DRAFT' WHEN ee.status='ARCHIVED' THEN 'ARCHIVED' WHEN ee.end_at<NOW() THEN 'COMPLETED' WHEN ee.start_at>NOW() THEN 'UPCOMING' ELSE 'IN_PROGRESS' END`;
function mapExamEvent(row){if(!row)return null;const schools=Array.isArray(row.schools)?row.schools:[];return {id:row.id,eventCode:row.event_code,name:row.name,description:row.description||'',schools,schoolName:schools.map(s=>s.name).join(', ')||row.school_name||null,internalNote:row.internal_note||'',imageStorageKey:row.image_storage_key||null,imageMimeType:row.image_mime_type||null,imageFileSize:row.image_file_size==null?null:Number(row.image_file_size),bannerStorageKey:row.banner_storage_key||null,bannerMimeType:row.banner_mime_type||null,bannerFileSize:row.banner_file_size==null?null:Number(row.banner_file_size),startAt:row.start_at,endAt:row.end_at,status:row.status,lifecycleStatus:row.lifecycle_status,candidateCount:Number(row.candidate_count||0),createdBy:row.created_by,updatedBy:row.updated_by,createdAt:row.created_at,updatedAt:row.updated_at,exam:row.e_id?{id:row.e_id,title:row.e_title,status:row.e_status,durationSeconds:Number(row.e_duration_minutes||0)*60+Number(row.e_duration_seconds||0),totalQuestions:Number(row.e_total_questions||0),scoreScale:Number(row.e_score_scale||100)}:null};}
const schoolSelect=`COALESCE((SELECT jsonb_agg(jsonb_build_object('id',school.id,'name',school.name) ORDER BY school.name) FROM exam_event_school_assignments assignment JOIN exam_event_schools school ON school.id=assignment.school_id WHERE assignment.exam_event_id=ee.id),'[]'::jsonb) schools`;
const baseSelect=`SELECT ee.*,${schoolSelect},${lifecycleSql} lifecycle_status,e.id e_id,e.title e_title,e.status e_status,e.duration_minutes e_duration_minutes,e.duration_seconds e_duration_seconds,e.score_scale e_score_scale,COUNT(DISTINCT sq.id)::int e_total_questions,COUNT(DISTINCT ec.id)::int candidate_count FROM exam_events ee JOIN exams e ON e.id=ee.exam_id LEFT JOIN exam_parts ep ON ep.exam_id=e.id LEFT JOIN exam_part_questions epq ON epq.part_id=ep.id LEFT JOIN question_bank_sub_questions sq ON sq.question_id=epq.question_id LEFT JOIN exam_candidates ec ON ec.exam_event_id=ee.id`;
async function list(filters={}){const page=Math.max(Number(filters.page)||PAGINATION.DEFAULT_PAGE,1);const limit=Math.min(Math.max(Number(filters.limit)||PAGINATION.DEFAULT_LIMIT,1),PAGINATION.MAX_LIMIT);const params=[];const where=[];if(filters.search){params.push(`%${String(filters.search).trim()}%`);where.push(`(ee.name ILIKE $${params.length} OR ee.event_code ILIKE $${params.length} OR EXISTS(SELECT 1 FROM exam_event_school_assignments esa JOIN exam_event_schools es ON es.id=esa.school_id WHERE esa.exam_event_id=ee.id AND es.name ILIKE $${params.length}))`);}const selectedSchools=String(filters.schoolName||'').split(',').map(value=>value.trim()).filter(Boolean);if(selectedSchools.length){params.push(selectedSchools);where.push(`EXISTS(SELECT 1 FROM exam_event_school_assignments esa JOIN exam_event_schools es ON es.id=esa.school_id WHERE esa.exam_event_id=ee.id AND es.name=ANY($${params.length}::text[]))`);}const selectedStatuses=String(filters.status||'').split(',').map(value=>value.trim()).filter(Boolean);if(selectedStatuses.length){params.push(selectedStatuses);where.push(`${lifecycleSql}=ANY($${params.length}::text[])`);}const clause=where.length?`WHERE ${where.join(' AND ')}`:'';const count=await db.query(`SELECT COUNT(*)::int total FROM exam_events ee ${clause}`,params);params.push(limit,(page-1)*limit);const rows=await db.query(`${baseSelect} ${clause} GROUP BY ee.id,e.id ORDER BY ee.updated_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);const total=count.rows[0].total;return {data:rows.rows.map(mapExamEvent),meta:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}};}
async function findById(id){const r=await db.query(`${baseSelect} WHERE ee.id=$1 GROUP BY ee.id,e.id`,[id]);return mapExamEvent(r.rows[0]);}
async function findExamById(id){const r=await db.query('SELECT id,title,status FROM exams WHERE id=$1',[id]);return r.rows[0]||null;}
async function replaceSchools(client,id,schoolIds){await client.query('DELETE FROM exam_event_school_assignments WHERE exam_event_id=$1',[id]);if(schoolIds.length)await client.query('INSERT INTO exam_event_school_assignments(exam_event_id,school_id) SELECT $1,UNNEST($2::uuid[])',[id,schoolIds]);}
async function create(data,userId){const id=crypto.randomUUID();const code=String(data.eventCode||'').trim().toUpperCase()||`EV-${id.replaceAll('-','').slice(0,10).toUpperCase()}`;await db.transaction(async client=>{await client.query(`INSERT INTO exam_events(id,event_code,name,description,school_name,start_at,end_at,exam_id,status,internal_note,created_by,updated_by) VALUES($1,$2,$3,$4,NULL,$5,$6,$7,$8,$9,$10,$10)`,[id,code,data.name.trim(),String(data.description||'').trim()||null,data.startAt,data.endAt,data.examId,data.status||'DRAFT',String(data.internalNote||'').trim()||null,userId||null]);await replaceSchools(client,id,[...new Set(data.schoolIds)]);});return findById(id);}
async function update(id,data,userId){await db.transaction(async client=>{const fields=[];const values=[id];for(const [key,column,transform] of [['name','name',v=>v.trim()],['description','description',v=>String(v||'').trim()||null],['eventCode','event_code',v=>v.trim().toUpperCase()],['startAt','start_at',v=>v],['endAt','end_at',v=>v],['examId','exam_id',v=>v],['status','status',v=>v],['internalNote','internal_note',v=>String(v||'').trim()||null]])if(data[key]!==undefined){values.push(transform(data[key]));fields.push(`${column}=$${values.length}`);}values.push(userId||null);fields.push(`updated_by=$${values.length}`,'updated_at=CURRENT_TIMESTAMP');await client.query(`UPDATE exam_events SET ${fields.join(',')} WHERE id=$1`,values);if(data.schoolIds!==undefined)await replaceSchools(client,id,[...new Set(data.schoolIds)]);});return findById(id);}
async function updateMedia(id,kind,media){const prefix=kind==='banner'?'banner':'image';await db.query(`UPDATE exam_events SET ${prefix}_storage_key=$2,${prefix}_mime_type=$3,${prefix}_file_size=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[id,media.storageKey,media.mimeType,media.fileSize]);return findById(id);}
async function clearMedia(id,kind){const prefix=kind==='banner'?'banner':'image';await db.query(`UPDATE exam_events SET ${prefix}_storage_key=NULL,${prefix}_mime_type=NULL,${prefix}_file_size=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[id]);return findById(id);}
async function remove(id){return db.query('DELETE FROM exam_events WHERE id=$1 RETURNING id',[id]);}
async function removeIfAllowed(id){return db.query(`DELETE FROM exam_events ee WHERE ee.id=$1 AND NOT (${lifecycleSql}='IN_PROGRESS') AND NOT EXISTS(SELECT 1 FROM exam_candidates ec WHERE ec.exam_event_id=ee.id) RETURNING id`,[id]);}
async function schools(){const r=await db.query("SELECT id,name FROM exam_event_schools WHERE status='ACTIVE' ORDER BY name");return r.rows;}
async function findSchoolByName(name){const r=await db.query("SELECT id,name FROM exam_event_schools WHERE status='ACTIVE' AND LOWER(BTRIM(name))=LOWER(BTRIM($1))",[name]);return r.rows[0]||null;}
async function findSchoolsByIds(ids){if(!ids.length)return[];const r=await db.query("SELECT id,name FROM exam_event_schools WHERE status='ACTIVE' AND id=ANY($1::uuid[])",[ids]);return r.rows;}
async function createSchool(name,userId){const r=await db.query("INSERT INTO exam_event_schools(name,created_by) VALUES(BTRIM($1),$2) RETURNING id,name",[name,userId||null]);return r.rows[0];}
module.exports={mapExamEvent,list,findById,findExamById,create,update,updateMedia,clearMedia,remove,removeIfAllowed,schools,findSchoolByName,findSchoolsByIds,createSchool};
