const express=require('express');
const multer=require('multer');
const asyncHandler=require('../http/asyncHandler');
const {requirePermission}=require('../middleware/authenticate');
const service=require('../modules/content-sources/contentSourceService');
const trends=require('../modules/content-sources/trendClusterService');
const materialSettings=require('../modules/content-sources/materialSettingService');
const blueprints=require('../modules/content-sources/materialBlueprintService');
const generatedMaterials=require('../modules/content-sources/generatedMaterialService');
const router=express.Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:10}});

router.get('/',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,...await service.list(req.auth.userId,req.query)})));
router.get('/trends',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,...await trends.list(req.auth.userId,req.query)})));
router.post('/trends/rebuild',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,...await trends.rebuild(req.auth.userId,req.body)})));
router.put('/trends/selection',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await trends.select(req.auth.userId,req.body)})));
router.get('/material-settings',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await materialSettings.get(req.auth.userId)})));
router.put('/material-settings',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await materialSettings.save(req.auth.userId,req.body)})));
router.get('/material-settings/preview',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,...await materialSettings.preview(req.auth.userId)})));
router.get('/blueprints',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,...await blueprints.list(req.auth.userId)})));
router.post('/blueprints',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await blueprints.generate(req.auth.userId,req.body)})));
router.get('/blueprints/:id',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await blueprints.detail(req.auth.userId,req.params.id)})));
router.put('/blueprints/:id',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await blueprints.update(req.auth.userId,req.params.id,req.body)})));
router.patch('/blueprints/:id/status',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await blueprints.setStatus(req.auth.userId,req.params.id,req.body)})));
router.get('/blueprints/:blueprintId/items/:itemId/materials',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,...await generatedMaterials.list(req.auth.userId,req.params.blueprintId,req.params.itemId)})));
router.post('/blueprints/:blueprintId/items/:itemId/materials',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await generatedMaterials.generate(req.auth.userId,req.params.blueprintId,req.params.itemId)})));
router.get('/generated-materials/:id',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await generatedMaterials.detail(req.auth.userId,req.params.id)})));
router.put('/generated-materials/:id',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await generatedMaterials.update(req.auth.userId,req.params.id,req.body)})));
router.patch('/generated-materials/:id/status',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await generatedMaterials.review(req.auth.userId,req.params.id,req.body)})));
router.post('/detect',requirePermission('content_sources.create'),upload.fields([{name:'file',maxCount:1},{name:'files',maxCount:10}]),asyncHandler(async(req,res)=>{const files=[...(req.files?.file||[]),...(req.files?.files||[])];return res.status(201).json({success:true,data:files.length>1?await service.ingestBatch({files,userId:req.auth.userId}):await service.ingest({file:files[0],text:req.body?.text,userId:req.auth.userId})});}));
router.get('/:id',requirePermission('content_sources.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await service.detail({sourceId:req.params.id,userId:req.auth.userId})})));
router.post('/:id/analyze',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await service.analyze({sourceId:req.params.id,text:req.body?.text,userId:req.auth.userId})})));
router.delete('/:id',requirePermission('content_sources.create'),asyncHandler(async(req,res)=>{const data=await service.remove({sourceId:req.params.id,userId:req.auth.userId});await trends.rebuild(req.auth.userId);res.json({success:true,data});}));
router.patch('/analyses/:analysisId/review',requirePermission('content_sources.analyze'),asyncHandler(async(req,res)=>res.json({success:true,data:await service.review({analysisId:req.params.analysisId,label:req.body?.label,note:req.body?.note,userId:req.auth.userId})})));
module.exports=router;
