const express=require('express');const multer=require('multer');const asyncHandler=require('../http/asyncHandler');const {requirePermission}=require('../middleware/authenticate');const c=require('../controllers/examEventController');const r=express.Router();const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}});
r.get('/',requirePermission('exam_events.view'),asyncHandler(c.list));
r.get('/schools',requirePermission('exam_events.view'),asyncHandler(c.schools));
r.post('/schools',requirePermission('exam_events.manage'),asyncHandler(c.createSchool));
r.post('/',requirePermission('exam_events.manage'),asyncHandler(c.create));
r.get('/:eventId',requirePermission('exam_events.view'),asyncHandler(c.detail));
r.put('/:eventId',requirePermission('exam_events.manage'),asyncHandler(c.update));
r.post('/:eventId/media/:kind',requirePermission('exam_events.manage'),upload.single('file'),asyncHandler(c.uploadMedia));
r.delete('/:eventId/media/:kind',requirePermission('exam_events.manage'),asyncHandler(c.removeMedia));
r.delete('/:eventId',requirePermission('exam_events.manage'),asyncHandler(c.remove));
module.exports=r;
