const express=require('express');const asyncHandler=require('../http/asyncHandler');const {requirePermission}=require('../middleware/authenticate');const c=require('../controllers/questionBankV3Controller');
const content=require('../controllers/questionContentV3Controller');
const subQuestion=require('../controllers/questionSubQuestionV3Controller');
const media=require('../controllers/questionMediaV3Controller');
const multer=require('multer');const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:100*1024*1024}}).single('file');
const groups=require('../controllers/questionGroupController');
const router=express.Router();
router.get('/groups',requirePermission('question_bank.view'),asyncHandler(async(req,res)=>{const r=await require('../config/db').query("SELECT id,code,title AS name,description,status FROM question_groups WHERE status='ACTIVE' ORDER BY title");res.json({success:true,data:r.rows});}));
router.get('/question-groups',requirePermission('question_bank.view'),asyncHandler(groups.list));
router.get('/question-groups/next-code',requirePermission('question_bank.taxonomy_manage'),asyncHandler(groups.previewNextCode));
router.get('/question-groups/:id',requirePermission('question_bank.view'),asyncHandler(groups.detail));
router.post('/question-groups',requirePermission('question_bank.taxonomy_manage'),asyncHandler(groups.create));
router.put('/question-groups/:id',requirePermission('question_bank.taxonomy_manage'),asyncHandler(groups.update));
router.delete('/question-groups/:id',requirePermission('question_bank.taxonomy_manage'),asyncHandler(groups.remove));
router.get('/tags',requirePermission('question_bank.view'),asyncHandler(async(req,res)=>{const r=await require('../config/db').query('SELECT id,name FROM question_bank_tags ORDER BY name');res.json({success:true,data:r.rows});}));
router.get('/questions/filter-options',requirePermission('question_bank.view'),asyncHandler(c.filterOptions));
router.post('/tags',requirePermission('question_bank.manage'),asyncHandler(async(req,res)=>{const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({success:false,error:'Tên Tag là bắt buộc.'});if(name.length>100)return res.status(400).json({success:false,error:'Tên Tag không được vượt quá 100 ký tự.'});const r=await require('../config/db').query('INSERT INTO question_bank_tags(name) VALUES($1) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id,name',[name]);return res.status(201).json({success:true,data:r.rows[0]});}));
router.post('/contents/:contentId/media',requirePermission('question_bank.media_manage'),upload,asyncHandler(media.upload('CONTENT')));
router.get('/contents/:contentId/media',requirePermission('question_bank.view'),asyncHandler(media.list('CONTENT')));
router.post('/sub-questions/:subQuestionId/media',requirePermission('question_bank.media_manage'),upload,asyncHandler(media.upload('SUB_QUESTION')));
router.get('/sub-questions/:subQuestionId/media',requirePermission('question_bank.view'),asyncHandler(media.list('SUB_QUESTION')));
router.post('/sample-answers/:sampleAnswerId/media',requirePermission('question_bank.media_manage'),upload,asyncHandler(media.upload('SAMPLE_ANSWER')));
router.get('/sample-answers/:sampleAnswerId/media',requirePermission('question_bank.view'),asyncHandler(media.list('SAMPLE_ANSWER')));
router.delete('/media/:mediaId',requirePermission('question_bank.media_manage'),asyncHandler(media.remove));
router.get('/media/:mediaId/url',requirePermission('question_bank.view'),asyncHandler(media.url));
router.get('/questions/:questionId/sub-questions',requirePermission('question_bank.view'),asyncHandler(subQuestion.list));
router.post('/questions/:questionId/sub-questions',requirePermission('question_bank.manage'),asyncHandler(subQuestion.create));
router.put('/questions/:questionId/sub-questions/reorder',requirePermission('question_bank.manage'),asyncHandler(subQuestion.reorder));
router.put('/questions/:questionId/sub-questions/:subQuestionId',requirePermission('question_bank.manage'),asyncHandler(subQuestion.update));
router.delete('/questions/:questionId/sub-questions/:subQuestionId',requirePermission('question_bank.manage'),asyncHandler(subQuestion.remove));
router.get('/questions/:questionId/contents',requirePermission('question_bank.view'),asyncHandler(content.list));
router.post('/questions/:questionId/contents',requirePermission('question_bank.manage'),asyncHandler(content.create));
router.put('/questions/:questionId/contents/reorder',requirePermission('question_bank.manage'),asyncHandler(content.reorder));
router.put('/questions/:questionId/contents/:contentId',requirePermission('question_bank.manage'),asyncHandler(content.update));
router.delete('/questions/:questionId/contents/:contentId',requirePermission('question_bank.manage'),asyncHandler(content.remove));
router.get('/questions',requirePermission('question_bank.view'),asyncHandler(c.list));
router.get('/questions/:id',requirePermission('question_bank.view'),asyncHandler(c.detail));
router.post('/questions',requirePermission('question_bank.manage'),asyncHandler(c.create));
router.put('/questions/:id',requirePermission('question_bank.manage'),asyncHandler(c.update));
router.delete('/questions/:id',requirePermission('question_bank.manage'),asyncHandler(c.remove));
module.exports=router;
