const express = require('express');
const asyncHandler = require('../http/asyncHandler');
const controller = require('../controllers/reportController');
const { requirePermission } = require('../middleware/authenticate');
const router = express.Router();
router.get('/bootstrap',requirePermission('reports.view','reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.bootstrap));
router.get('/dashboard',requirePermission('reports.view'),asyncHandler(controller.dashboard));
router.get('/overview',requirePermission('reports.view'),asyncHandler(controller.overview));
router.get('/trend',requirePermission('reports.view'),asyncHandler(controller.trend));
router.get('/manual/periods',requirePermission('reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.listManualPeriods));
router.get('/manual/assignees',requirePermission('reports.assign','reports.manage'),asyncHandler(controller.listManualAssignees));
router.get('/manual/periods/find',requirePermission('reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.findManualPeriod));
router.post('/manual/periods',requirePermission('reports.manage'),asyncHandler(controller.createManualPeriod));
router.get('/manual/periods/:periodId',requirePermission('reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.getManualPeriod));
router.patch('/manual/periods/:periodId/deadline',requirePermission('reports.manage'),asyncHandler(controller.updateManualDeadline));
router.get('/manual/periods/:periodId/audit',requirePermission('reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.manualAuditTimeline));
router.get('/manual/periods/:periodId/publish-checklist',requirePermission('reports.publish','reports.manage'),asyncHandler(controller.manualPublishChecklist));
router.get('/manual/periods/:periodId/preview/:teamCode',requirePermission('reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.manualPreview));
router.delete('/manual/periods/:periodId',requirePermission('reports.manage'),asyncHandler(controller.deleteManualPeriod));
router.patch('/manual/periods/:periodId/teams/:teamCode/assignee',requirePermission('reports.assign','reports.manage'),asyncHandler(controller.assignManualSubmission));
router.get('/manual/periods/:periodId/teams/:teamCode',requirePermission('reports.forms.view','reports.entry','reports.review','reports.assign','reports.publish','reports.manage'),asyncHandler(controller.manualWorkspace));
router.get('/manual/periods/:periodId/teams/:teamCode/template',requirePermission('reports.forms.view','reports.entry','reports.review','reports.manage'),asyncHandler(controller.exportManualTemplate));
router.post('/manual/periods/:periodId/teams/:teamCode/template/import',requirePermission('reports.entry','reports.review','reports.manage'),asyncHandler(controller.importManualTemplate));
router.put('/manual/periods/:periodId/teams/:teamCode',requirePermission('reports.entry','reports.review','reports.manage'),asyncHandler(controller.saveManualWorkspace));
router.post('/manual/periods/:periodId/teams/:teamCode/workflow',requirePermission('reports.entry','reports.review','reports.manage'),asyncHandler(controller.manualTransition));
router.post('/manual/periods/:periodId/publish',requirePermission('reports.publish','reports.manage'),asyncHandler(controller.publishManualPeriod));
router.post('/manual/periods/:periodId/reopen',requirePermission('reports.publish','reports.manage'),asyncHandler(controller.reopenManualPeriod));
router.get('/kpi-config',requirePermission('reports.manage'),asyncHandler(controller.listKpiConfig));
router.post('/kpi-config',requirePermission('reports.manage'),asyncHandler(controller.createKpiConfig));
router.put('/kpi-config/order',requirePermission('reports.manage'),asyncHandler(controller.reorderKpiConfig));
router.put('/kpi-config/:id',requirePermission('reports.manage'),asyncHandler(controller.updateKpiConfig));
router.get('/detail-row-config',requirePermission('reports.manage'),asyncHandler(controller.listDetailRows));
router.post('/detail-row-config',requirePermission('reports.manage'),asyncHandler(controller.createDetailRow));
router.put('/detail-row-config/order',requirePermission('reports.manage'),asyncHandler(controller.reorderDetailRows));
router.put('/detail-row-config/:id',requirePermission('reports.manage'),asyncHandler(controller.updateDetailRow));
module.exports = router;
