const express = require('express');
const asyncHandler = require('../http/asyncHandler');
const controller = require('../controllers/reportController');
const { requirePermission } = require('../middleware/authenticate');
const router = express.Router();
router.get('/bootstrap',requirePermission('reports.view'),asyncHandler(controller.bootstrap));
router.get('/dashboard',requirePermission('reports.view'),asyncHandler(controller.dashboard));
router.get('/overview',requirePermission('reports.view'),asyncHandler(controller.overview));
router.get('/trend',requirePermission('reports.view'),asyncHandler(controller.trend));
router.get('/manual/periods',requirePermission('reports.view'),asyncHandler(controller.listManualPeriods));
router.get('/manual/periods/find',requirePermission('reports.view'),asyncHandler(controller.findManualPeriod));
router.post('/manual/periods',requirePermission('reports.manage'),asyncHandler(controller.createManualPeriod));
router.get('/manual/periods/:periodId',requirePermission('reports.view'),asyncHandler(controller.getManualPeriod));
router.delete('/manual/periods/:periodId',requirePermission('reports.manage'),asyncHandler(controller.deleteManualPeriod));
router.get('/manual/periods/:periodId/teams/:teamCode',requirePermission('reports.view'),asyncHandler(controller.manualWorkspace));
router.put('/manual/periods/:periodId/teams/:teamCode',requirePermission('reports.upload'),asyncHandler(controller.saveManualWorkspace));
router.post('/manual/periods/:periodId/teams/:teamCode/workflow',requirePermission('reports.upload','reports.manage'),asyncHandler(controller.manualTransition));
router.post('/manual/periods/:periodId/publish',requirePermission('reports.manage'),asyncHandler(controller.publishManualPeriod));
router.post('/manual/periods/:periodId/reopen',requirePermission('reports.manage'),asyncHandler(controller.reopenManualPeriod));
router.get('/kpi-config',requirePermission('reports.manage'),asyncHandler(controller.listKpiConfig));
router.post('/kpi-config',requirePermission('reports.manage'),asyncHandler(controller.createKpiConfig));
router.put('/kpi-config/order',requirePermission('reports.manage'),asyncHandler(controller.reorderKpiConfig));
router.put('/kpi-config/:id',requirePermission('reports.manage'),asyncHandler(controller.updateKpiConfig));
module.exports = router;
