import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {BarChart3,Check,CircleDollarSign,GraduationCap,GripVertical,Handshake,Info,Megaphone,Package,PenLine,Plus,Power,RefreshCw,RotateCcw,Settings2,X} from 'lucide-react';
import api from '../../../services/api';
import {useDialog} from '../../../components/feedback/dialogContext';
import './KpiConfigurationPage.css';
import './KpiConfigurationPage.layout.css';
import './KpiConfigurationPage.drag.css';
import './KpiConfigurationPage.toolbar.css';

const TEAMS=[['REV','Doanh thu',CircleDollarSign],['ADS','Marketing Ads',BarChart3],['COM','Truyền thông',Megaphone],['TRADE','Trade',Handshake],['TRAIN','Đào tạo',GraduationCap],['PROD','Sản phẩm',Package]];
const DIRECTIONS=[['increase_good','Tăng tốt'],['decrease_good','Giảm tốt'],['monitor','Theo dõi']];
const FORMULAS={REV:['DT_01','DT_03','DT_04'],ADS:['ADS_01','ADS_02','ADS_03','ADS_04','ADS_05','ADS_06','ADS_07'],COM:['TT_01','TT_02','TT_03','TT_04','TT_05','TT_06','TT_07','TT_08','TT_09'],TRADE:['TRADE_03','TRADE_04','TRADE_05','TRADE_07','TRADE_08','TRADE_09','TRADE_10','TRADE_11'],TRAIN:['DAO_01','DAO_02','DAO_03','DAO_04','DAO_05','DAO_06','DAO_07','DAO_09'],PROD:['SP_01','SP_02','SP_03','SP_04','SP_05']};
const TEMPLATE_ROW_TEAMS=new Set(['REV','ADS','COM','TRAIN']);
const SOURCE_LABEL={manual:'Nhập tay',derived:'Công thức',previous_period:'Lấy kỳ trước',formula:'Công thức'};
const empty={name:'',unit:'',evaluationDirection:'increase_good',inputMode:'manual',formulaCode:''};

export default function KpiConfigurationPage({showMsg}){
  const {confirm:confirmDialog}=useDialog();
  const notify=useRef(showMsg);const [team,setTeam]=useState('REV');const [items,setItems]=useState([]);const [detailItems,setDetailItems]=useState([]);const [master,setMaster]=useState({});const [loading,setLoading]=useState(true);const [editing,setEditing]=useState(null);const [detailEditing,setDetailEditing]=useState(null);const [form,setForm]=useState(empty);const [detailForm,setDetailForm]=useState(null);const [busy,setBusy]=useState(false);const [dragging,setDragging]=useState(null);const [dragOver,setDragOver]=useState(null);const [detailDragging,setDetailDragging]=useState(null);const [detailDragOver,setDetailDragOver]=useState(null);
  useEffect(()=>{notify.current=showMsg;},[showMsg]);
  const load=useCallback(async()=>{setLoading(true);try{const [config,details,base]=await Promise.all([api.get('/reports/kpi-config',{params:{team}}),api.get('/reports/detail-row-config',{params:{team}}),api.get('/reports/bootstrap')]);setItems(config.data.data||[]);setDetailItems(details.data.data||[]);setMaster(base.data.data.masterData||{});}catch(error){notify.current(error.response?.data?.error||'Không thể tải cấu hình báo cáo.','error');}finally{setLoading(false);}},[team]);
  useEffect(()=>{load();},[load]);
  const active=useMemo(()=>items.filter(item=>item.is_active),[items]);
  const inactiveCount=items.length-active.length;
  const openCreate=()=>{setEditing('new');setForm(empty);};
  const openEdit=item=>{setEditing(item);setForm({name:item.name,unit:item.unit,evaluationDirection:item.evaluation_direction,inputMode:item.input_mode||'manual',formulaCode:item.formula_code||'',isActive:item.is_active});};
  const save=async event=>{event.preventDefault();setBusy(true);try{if(editing==='new')await api.post('/reports/kpi-config',{teamCode:team,...form});else await api.put(`/reports/kpi-config/${editing.id}`,form);notify.current(editing==='new'?'Đã tạo KPI mới. Cấu hình áp dụng từ kỳ tạo tiếp theo.':'Đã cập nhật cấu hình KPI.');setEditing(null);await load();}catch(error){notify.current(error.response?.data?.error||'Không thể lưu cấu hình KPI.','error');}finally{setBusy(false);}};
  const toggle=async item=>{if(item.is_active&&!await confirmDialog({title:'Ngừng sử dụng KPI?',message:`KPI ${item.code} sẽ bị ngừng sử dụng. Các kỳ đã tạo không bị thay đổi.`,confirmText:'Ngừng sử dụng'}))return;setBusy(true);try{await api.put(`/reports/kpi-config/${item.id}`,{name:item.name,unit:item.unit,evaluationDirection:item.evaluation_direction,inputMode:item.input_mode||'manual',formulaCode:item.formula_code||'',isActive:!item.is_active});await load();}catch(error){notify.current(error.response?.data?.error||'Không thể cập nhật trạng thái KPI.','error');}finally{setBusy(false);}};
  const openDetail=item=>{setDetailEditing(item||'new');setDetailForm(item?{rowCode:item.row_code,rowName:item.row_name,rowGroup:item.row_group||'',sectionKey:item.section_key||'traffic',isRequired:item.is_required,isActive:item.is_active}:{rowCode:'',rowName:'',rowGroup:'',sectionKey:team==='ADS'?'traffic':'primary',isRequired:false,isActive:true});};
  const saveDetail=async event=>{event.preventDefault();setBusy(true);try{if(detailEditing==='new')await api.post('/reports/detail-row-config',{teamCode:team,...detailForm});else await api.put(`/reports/detail-row-config/${detailEditing.id}`,detailForm);notify.current(detailEditing==='new'?'Đã tạo dòng chi tiết.':'Đã cập nhật dòng chi tiết.');setDetailEditing(null);await load();}catch(error){notify.current(error.response?.data?.error||'Không thể lưu dòng chi tiết.','error');}finally{setBusy(false);}};
  const reorder=async(sourceId,targetId)=>{if(!sourceId||sourceId===targetId)return;const from=active.findIndex(item=>item.id===sourceId);const to=active.findIndex(item=>item.id===targetId);if(from<0||to<0)return;const ordered=[...active];const [moved]=ordered.splice(from,1);ordered.splice(to,0,moved);setItems([...ordered,...items.filter(item=>!item.is_active)]);try{await api.put('/reports/kpi-config/order',{teamCode:team,ids:ordered.map(item=>item.id)});}catch(error){notify.current(error.response?.data?.error||'Không thể đổi thứ tự KPI.','error');await load();}};
  const drop=async targetId=>{const sourceId=dragging;setDragging(null);setDragOver(null);await reorder(sourceId,targetId);};
  const detailSections=useMemo(()=>team==='ADS'?[{key:'traffic',title:'II. Chi tiết theo nguồn Traffic',description:'Thứ tự nguồn traffic trong phiếu nhập liệu.'},{key:'products',title:'III. Tỷ trọng Ads theo sản phẩm',description:'Thứ tự sản phẩm trong khối phân bổ Ads.'}]:[{key:'primary',title:null,description:null}],[team]);
  const sectionItems=key=>detailItems.filter(item=>(item.section_key||'primary')===key).sort((a,b)=>Number(b.is_active)-Number(a.is_active)||Number(a.display_order)-Number(b.display_order));
  const reorderDetail=async(sourceId,targetId,sectionKey)=>{if(!sourceId||sourceId===targetId)return;const activeRows=sectionItems(sectionKey).filter(item=>item.is_active);const from=activeRows.findIndex(item=>item.id===sourceId),to=activeRows.findIndex(item=>item.id===targetId);if(from<0||to<0)return;const ordered=[...activeRows];const [moved]=ordered.splice(from,1);ordered.splice(to,0,moved);const rank=new Map(ordered.map((item,index)=>[item.id,index]));setDetailItems(current=>current.map(item=>rank.has(item.id)?{...item,display_order:rank.get(item.id)+1}:item));try{await api.put('/reports/detail-row-config/order',{teamCode:team,sectionKey,ids:ordered.map(item=>item.id)});}catch(error){notify.current(error.response?.data?.error||'Không thể đổi thứ tự dòng chi tiết.','error');await load();}};
  const dropDetail=async(targetId,sectionKey)=>{const sourceId=detailDragging;setDetailDragging(null);setDetailDragOver(null);await reorderDetail(sourceId,targetId,sectionKey);};
  return <div className="kpi-config-page">
    <header className="kpi-config-header"><div><span>CẤU HÌNH BÁO CÁO</span><h1>Danh mục chỉ số KPI</h1><p>Quản lý bộ chỉ số chuẩn dùng để sinh phiếu báo cáo cho từng bộ phận.</p></div></header>
    <section className="kpi-config-notice"><Info/><div><b>Thay đổi chỉ áp dụng cho kỳ báo cáo được tạo mới</b><span>KPI trong các kỳ đã tạo được giữ nguyên để bảo toàn dữ liệu so sánh và lịch sử báo cáo.</span></div></section>
    <nav className="kpi-team-tabs" aria-label="Chọn bộ phận">{TEAMS.map(([code,name,Icon])=><button key={code} className={team===code?'active':''} onClick={()=>setTeam(code)}><Icon/><b>{name}</b>{team===code&&<em>{active.length}</em>}</button>)}</nav>
    <main className="kpi-config-panel"><header className="kpi-panel-toolbar"><div className="department-heading"><span>BỘ CHỈ SỐ ĐANG ÁP DỤNG</span><div><h2>{TEAMS.find(item=>item[0]===team)?.[1]}</h2><em>{active.length} KPI đang dùng{inactiveCount?` · ${inactiveCount} đã ngừng`:''}</em></div></div><div className="panel-actions"><button className="refresh" onClick={load} disabled={loading} aria-label="Làm mới dữ liệu"><RefreshCw className={loading?'spin':''}/><span>Làm mới</span></button><button className="add" onClick={openCreate}><Plus/>Thêm KPI</button></div></header>
      <section className="kpi-lock-hint compact"><Settings2/><span><b>Khóa cấu trúc theo kỳ:</b> chỉ cập nhật kế hoạch, thực hiện và dữ liệu chi tiết.</span></section>
      <div className="kpi-config-table-wrap"><div className="kpi-config-table"><div className="kpi-config-row head"><span>Sắp xếp</span><span>Mã KPI</span><span>Tên chỉ số</span><span>Đơn vị</span><span>Chiều đánh giá</span><span>Nguồn dữ liệu</span><span>Trạng thái</span><span aria-label="Thao tác"/></div>{items.map(item=><div className={`kpi-config-row${item.is_active?'':' inactive'}${dragging===item.id?' dragging':''}${dragOver===item.id?' drag-over':''}`} draggable={item.is_active} onDragStart={event=>{setDragging(item.id);event.dataTransfer.effectAllowed='move';}} onDragEnter={()=>item.is_active&&setDragOver(item.id)} onDragOver={event=>{if(item.is_active){event.preventDefault();event.dataTransfer.dropEffect='move';}}} onDrop={event=>{event.preventDefault();drop(item.id);}} onDragEnd={()=>{setDragging(null);setDragOver(null);}} key={item.id}><span className="order" title={item.is_active?'Giữ và kéo để thay đổi thứ tự':'KPI đã ngừng sử dụng'}><GripVertical/><span className="order-number">{item.is_active?active.findIndex(x=>x.id===item.id)+1:'—'}</span></span><code>{item.code}</code><strong title={item.name}>{item.name}</strong><span>{item.unit}</span><span>{DIRECTIONS.find(x=>x[0]===item.evaluation_direction)?.[1]}</span><span className={`mode ${item.input_mode==='derived'?'derived':'manual'}`}>{SOURCE_LABEL[item.input_mode]||'Nhập tay'}</span><span className={`state ${item.is_active?'active':'off'}`}>{item.is_active?'Đang dùng':'Đã ngừng'}</span><span className="actions"><button title="Chỉnh sửa KPI" aria-label={`Chỉnh sửa ${item.code}`} onClick={()=>openEdit(item)}><PenLine/></button><button className={item.is_active?'danger':'restore'} title={item.is_active?'Ngừng sử dụng':'Kích hoạt lại'} aria-label={`${item.is_active?'Ngừng sử dụng':'Kích hoạt lại'} ${item.code}`} onClick={()=>toggle(item)} disabled={busy}>{item.is_active?<Power/>:<RotateCcw/>}</button></span></div>)}{!loading&&!items.length&&<div className="kpi-config-empty"><Settings2/><b>Chưa có KPI cho bộ phận này</b><span>Chọn “Thêm KPI” để bắt đầu cấu hình bộ chỉ số.</span></div>}</div></div>
    </main>
    <main className="kpi-config-panel"><header><div><span>02 · DỮ LIỆU CHI TIẾT</span><h2>{TEMPLATE_ROW_TEAMS.has(team)?'Danh sách dòng mẫu':'Dòng phát sinh theo kỳ'}</h2><p>{TEMPLATE_ROW_TEAMS.has(team)?'Bộ cột được cố định theo loại báo cáo; kéo thả để sắp xếp các dòng trong từng khối.':'Loại báo cáo này dùng dòng nghiệp vụ phát sinh, không sinh sẵn danh sách dòng cố định.'}</p></div>{TEMPLATE_ROW_TEAMS.has(team)&&<div className="panel-actions"><button className="add" onClick={()=>openDetail(null)}><Plus/>Thêm dòng</button></div>}</header>{TEMPLATE_ROW_TEAMS.has(team)&&<div className="detail-section-list">{detailSections.map(section=>{const rows=sectionItems(section.key);const activeRows=rows.filter(item=>item.is_active);return <section className="detail-section" key={section.key}>{section.title&&<header><div><b>{section.title}</b><span>{section.description}</span></div><em>{activeRows.length} dòng đang dùng</em></header>}<div className={`detail-config-table${team==='REV'?' revenue-rows':team==='ADS'?' ads-rows':''}`}><div className="detail-config-row head"><span>Sắp xếp</span><span>Tên dòng</span><span>Mã dòng</span>{(team==='REV'||team==='ADS')&&<span>Nhóm sản phẩm</span>}<span>Bắt buộc</span><span>Trạng thái</span><span/></div>{rows.map(item=><div className={`detail-config-row${item.is_active?'':' inactive'}${detailDragging===item.id?' dragging':''}${detailDragOver===item.id?' drag-over':''}`} draggable={item.is_active} onDragStart={event=>{setDetailDragging(item.id);event.dataTransfer.effectAllowed='move';}} onDragEnter={()=>item.is_active&&setDetailDragOver(item.id)} onDragOver={event=>{if(item.is_active){event.preventDefault();event.dataTransfer.dropEffect='move';}}} onDrop={event=>{event.preventDefault();dropDetail(item.id,section.key);}} onDragEnd={()=>{setDetailDragging(null);setDetailDragOver(null);}} key={item.id}><span className="order" title={item.is_active?'Giữ và kéo để thay đổi thứ tự':'Dòng đã ngừng sử dụng'}><GripVertical/><span className="order-number">{item.is_active?activeRows.findIndex(row=>row.id===item.id)+1:'—'}</span></span><strong>{item.row_name}</strong><code>{item.row_code}</code>{(team==='REV'||team==='ADS')&&<span>{item.row_group||'—'}</span>}<span>{item.is_required?'Có':'Không'}</span><span className={`state ${item.is_active?'active':'off'}`}>{item.is_active?'Đang dùng':'Đã ngừng'}</span><span className="actions"><button onClick={()=>openDetail(item)} aria-label={`Sửa dòng ${item.row_name}`}><PenLine/></button></span></div>)}</div></section>;})}</div>}</main>
    {editing&&<div className="kpi-config-modal"><form onSubmit={save}><header><div><span>{editing==='new'?'KPI MỚI':'CHỈNH SỬA KPI'}</span><h2>{editing==='new'?'Tạo chỉ số KPI':editing.code}</h2></div><button type="button" onClick={()=>setEditing(null)}><X/></button></header>{editing==='new'&&<div className="generated-id"><Check/><span>ID KPI được hệ thống tự sinh theo bộ phận.</span></div>}<label>Tên KPI<input autoFocus required maxLength="255" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nhập tên chỉ số"/></label><div className="form-grid"><label>Đơn vị<select required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value="">Chọn đơn vị</option>{(master.unit||[]).map(item=><option key={item.code} value={item.label}>{item.label}</option>)}</select></label><label>Chiều đánh giá<select value={form.evaluationDirection} onChange={e=>setForm({...form,evaluationDirection:e.target.value})}>{DIRECTIONS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Nguồn dữ liệu<select value={form.inputMode} onChange={e=>setForm({...form,inputMode:e.target.value,formulaCode:e.target.value==='manual'?'':form.formulaCode})}><option value="manual">Nhập tay</option><option value="derived" disabled={!FORMULAS[team].length}>Công thức từ chi tiết</option></select></label>{form.inputMode==='derived'&&<label>Công thức<select required value={form.formulaCode} onChange={e=>setForm({...form,formulaCode:e.target.value})}><option value="">Chọn công thức</option>{FORMULAS[team].map(code=><option key={code} value={code}>{code}</option>)}</select></label>}</div><footer><button type="button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary" disabled={busy}>{busy?'Đang lưu…':'Lưu cấu hình'}</button></footer></form></div>}
    {detailEditing&&<div className="kpi-config-modal"><form onSubmit={saveDetail}><header><div><span>DÒNG DỮ LIỆU CHI TIẾT</span><h2>{detailEditing==='new'?'Thêm dòng mẫu':detailEditing.row_code}</h2></div><button type="button" onClick={()=>setDetailEditing(null)}><X/></button></header><label>Tên dòng<input required value={detailForm.rowName} onChange={e=>setDetailForm({...detailForm,rowName:e.target.value})} placeholder={team==='REV'||(team==='ADS'&&detailForm.sectionKey==='products')?'Ví dụ: TOEIC LR':'Ví dụ: Facebook Ads'}/></label><div className="form-grid"><label>Mã dòng<input required disabled={detailEditing!=='new'} value={detailForm.rowCode} onChange={e=>setDetailForm({...detailForm,rowCode:e.target.value.toUpperCase()})} placeholder="Ví dụ: ADS_FB hoặc ADS_TOEIC_LR"/></label>{team==='ADS'&&<label>Khối chi tiết<select value={detailForm.sectionKey} onChange={e=>setDetailForm({...detailForm,sectionKey:e.target.value,rowGroup:e.target.value==='products'?detailForm.rowGroup:''})}><option value="traffic">II. Chi tiết theo nguồn Traffic</option><option value="products">III. Tỷ trọng Ads theo sản phẩm</option></select></label>}{(team==='REV'||(team==='ADS'&&detailForm.sectionKey==='products'))&&<label>Nhóm sản phẩm<select required value={detailForm.rowGroup} onChange={e=>setDetailForm({...detailForm,rowGroup:e.target.value})}><option value="">Chọn nhóm sản phẩm</option>{(master.product_group||[]).map(item=><option key={item.code} value={item.label}>{item.label}</option>)}</select></label>}<label>Bắt buộc<select value={detailForm.isRequired?'yes':'no'} onChange={e=>setDetailForm({...detailForm,isRequired:e.target.value==='yes'})}><option value="no">Không</option><option value="yes">Có</option></select></label>{detailEditing!=='new'&&<label>Trạng thái<select value={detailForm.isActive?'yes':'no'} onChange={e=>setDetailForm({...detailForm,isActive:e.target.value==='yes'})}><option value="yes">Đang dùng</option><option value="no">Ngừng dùng</option></select></label>}</div><footer><button type="button" onClick={()=>setDetailEditing(null)}>Hủy</button><button className="primary" disabled={busy}>{busy?'Đang lưu…':'Lưu dòng'}</button></footer></form></div>}
  </div>;
}
