import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {BarChart3,Check,CircleDollarSign,GraduationCap,GripVertical,Handshake,Info,Megaphone,Package,PenLine,Plus,Power,RefreshCw,RotateCcw,Settings2,X} from 'lucide-react';
import api from '../../../services/api';
import './KpiConfigurationPage.css';
import './KpiConfigurationPage.layout.css';
import './KpiConfigurationPage.drag.css';
import './KpiConfigurationPage.toolbar.css';

const TEAMS=[['REV','Doanh thu',CircleDollarSign],['ADS','Marketing Ads',BarChart3],['COM','Truyền thông',Megaphone],['TRADE','Trade',Handshake],['TRAIN','Đào tạo',GraduationCap],['PROD','Sản phẩm',Package]];
const DIRECTIONS=[['increase_good','Tăng tốt'],['decrease_good','Giảm tốt'],['monitor','Theo dõi']];
const empty={name:'',unit:'',evaluationDirection:'increase_good'};

export default function KpiConfigurationPage({showMsg}){
  const notify=useRef(showMsg);const [team,setTeam]=useState('REV');const [items,setItems]=useState([]);const [master,setMaster]=useState({});const [loading,setLoading]=useState(true);const [editing,setEditing]=useState(null);const [form,setForm]=useState(empty);const [busy,setBusy]=useState(false);const [dragging,setDragging]=useState(null);const [dragOver,setDragOver]=useState(null);
  useEffect(()=>{notify.current=showMsg;},[showMsg]);
  const load=useCallback(async()=>{setLoading(true);try{const [config,base]=await Promise.all([api.get('/reports/kpi-config',{params:{team}}),api.get('/reports/bootstrap')]);setItems(config.data.data||[]);setMaster(base.data.data.masterData||{});}catch(error){notify.current(error.response?.data?.error||'Không thể tải cấu hình KPI.','error');}finally{setLoading(false);}},[team]);
  useEffect(()=>{load();},[load]);
  const active=useMemo(()=>items.filter(item=>item.is_active),[items]);
  const inactiveCount=items.length-active.length;
  const openCreate=()=>{setEditing('new');setForm(empty);};
  const openEdit=item=>{setEditing(item);setForm({name:item.name,unit:item.unit,evaluationDirection:item.evaluation_direction,isActive:item.is_active});};
  const save=async event=>{event.preventDefault();setBusy(true);try{if(editing==='new')await api.post('/reports/kpi-config',{teamCode:team,...form});else await api.put(`/reports/kpi-config/${editing.id}`,form);notify.current(editing==='new'?'Đã tạo KPI mới. Cấu hình áp dụng từ kỳ tạo tiếp theo.':'Đã cập nhật cấu hình KPI.');setEditing(null);await load();}catch(error){notify.current(error.response?.data?.error||'Không thể lưu cấu hình KPI.','error');}finally{setBusy(false);}};
  const toggle=async item=>{if(item.is_active&&!window.confirm(`Ngừng sử dụng KPI ${item.code}? Các kỳ đã tạo không bị thay đổi.`))return;setBusy(true);try{await api.put(`/reports/kpi-config/${item.id}`,{name:item.name,unit:item.unit,evaluationDirection:item.evaluation_direction,isActive:!item.is_active});await load();}catch(error){notify.current(error.response?.data?.error||'Không thể cập nhật trạng thái KPI.','error');}finally{setBusy(false);}};
  const reorder=async(sourceId,targetId)=>{if(!sourceId||sourceId===targetId)return;const from=active.findIndex(item=>item.id===sourceId);const to=active.findIndex(item=>item.id===targetId);if(from<0||to<0)return;const ordered=[...active];const [moved]=ordered.splice(from,1);ordered.splice(to,0,moved);setItems([...ordered,...items.filter(item=>!item.is_active)]);try{await api.put('/reports/kpi-config/order',{teamCode:team,ids:ordered.map(item=>item.id)});}catch(error){notify.current(error.response?.data?.error||'Không thể đổi thứ tự KPI.','error');await load();}};
  const drop=async targetId=>{const sourceId=dragging;setDragging(null);setDragOver(null);await reorder(sourceId,targetId);};
  return <div className="kpi-config-page">
    <header className="kpi-config-header"><div><span>CẤU HÌNH BÁO CÁO</span><h1>Danh mục chỉ số KPI</h1><p>Quản lý bộ chỉ số chuẩn dùng để sinh phiếu báo cáo cho từng bộ phận.</p></div></header>
    <section className="kpi-config-notice"><Info/><div><b>Thay đổi chỉ áp dụng cho kỳ báo cáo được tạo mới</b><span>KPI trong các kỳ đã tạo được giữ nguyên để bảo toàn dữ liệu so sánh và lịch sử báo cáo.</span></div></section>
    <nav className="kpi-team-tabs" aria-label="Chọn bộ phận">{TEAMS.map(([code,name,Icon])=><button key={code} className={team===code?'active':''} onClick={()=>setTeam(code)}><Icon/><b>{name}</b>{team===code&&<em>{active.length}</em>}</button>)}</nav>
    <main className="kpi-config-panel"><header className="kpi-panel-toolbar"><div className="department-heading"><span>BỘ CHỈ SỐ ĐANG ÁP DỤNG</span><div><h2>{TEAMS.find(item=>item[0]===team)?.[1]}</h2><em>{active.length} KPI đang dùng{inactiveCount?` · ${inactiveCount} đã ngừng`:''}</em></div></div><div className="panel-actions"><button className="refresh" onClick={load} disabled={loading} aria-label="Làm mới dữ liệu"><RefreshCw className={loading?'spin':''}/><span>Làm mới</span></button><button className="add" onClick={openCreate}><Plus/>Thêm KPI</button></div></header>
      <section className="kpi-lock-hint compact"><Settings2/><span><b>Khóa cấu trúc theo kỳ:</b> chỉ cập nhật kế hoạch, thực hiện và dữ liệu chi tiết.</span></section>
      <div className="kpi-config-table-wrap"><div className="kpi-config-table"><div className="kpi-config-row head"><span>Sắp xếp</span><span>Mã KPI</span><span>Tên chỉ số</span><span>Đơn vị</span><span>Chiều đánh giá</span><span>Nguồn dữ liệu</span><span>Trạng thái</span><span aria-label="Thao tác"/></div>{items.map(item=><div className={`kpi-config-row${item.is_active?'':' inactive'}${dragging===item.id?' dragging':''}${dragOver===item.id?' drag-over':''}`} draggable={item.is_active} onDragStart={event=>{setDragging(item.id);event.dataTransfer.effectAllowed='move';}} onDragEnter={()=>item.is_active&&setDragOver(item.id)} onDragOver={event=>{if(item.is_active){event.preventDefault();event.dataTransfer.dropEffect='move';}}} onDrop={event=>{event.preventDefault();drop(item.id);}} onDragEnd={()=>{setDragging(null);setDragOver(null);}} key={item.id}><span className="order" title={item.is_active?'Giữ và kéo để thay đổi thứ tự':'KPI đã ngừng sử dụng'}><GripVertical/><span className="order-number">{item.is_active?active.findIndex(x=>x.id===item.id)+1:'—'}</span></span><code>{item.code}</code><strong title={item.name}>{item.name}</strong><span>{item.unit}</span><span>{DIRECTIONS.find(x=>x[0]===item.evaluation_direction)?.[1]}</span><span className="mode manual">Nhập thủ công</span><span className={`state ${item.is_active?'active':'off'}`}>{item.is_active?'Đang dùng':'Đã ngừng'}</span><span className="actions"><button title="Chỉnh sửa KPI" aria-label={`Chỉnh sửa ${item.code}`} onClick={()=>openEdit(item)}><PenLine/></button><button className={item.is_active?'danger':'restore'} title={item.is_active?'Ngừng sử dụng':'Kích hoạt lại'} aria-label={`${item.is_active?'Ngừng sử dụng':'Kích hoạt lại'} ${item.code}`} onClick={()=>toggle(item)} disabled={busy}>{item.is_active?<Power/>:<RotateCcw/>}</button></span></div>)}{!loading&&!items.length&&<div className="kpi-config-empty"><Settings2/><b>Chưa có KPI cho bộ phận này</b><span>Chọn “Thêm KPI” để bắt đầu cấu hình bộ chỉ số.</span></div>}</div></div>
    </main>
    {editing&&<div className="kpi-config-modal"><form onSubmit={save}><header><div><span>{editing==='new'?'KPI MỚI':'CHỈNH SỬA KPI'}</span><h2>{editing==='new'?'Tạo chỉ số KPI':editing.code}</h2></div><button type="button" onClick={()=>setEditing(null)}><X/></button></header>{editing==='new'&&<div className="generated-id"><Check/><span>ID KPI được hệ thống tự sinh theo bộ phận.</span></div>}<label>Tên KPI<input autoFocus required maxLength="255" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nhập tên chỉ số"/></label><div className="form-grid"><label>Đơn vị<select required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value="">Chọn đơn vị</option>{(master.unit||[]).map(item=><option key={item.code} value={item.label}>{item.label}</option>)}</select></label><label>Chiều đánh giá<select value={form.evaluationDirection} onChange={e=>setForm({...form,evaluationDirection:e.target.value})}>{DIRECTIONS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><footer><button type="button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary" disabled={busy}>{busy?'Đang lưu…':'Lưu cấu hình'}</button></footer></form></div>}
  </div>;
}
