import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {AlertCircle,ArrowLeft,Check,Download,Eye,FileSpreadsheet,Plus,RefreshCw,RotateCcw,Save,Send,Trash2,Upload,X} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import api from '../../../services/api';
import {formatVietnameseNumber,parseVietnameseNumber} from '../utils/vietnameseNumber';
import './ManualReportPage.css';

const now=new Date();
const STATUS={draft:'Chưa nhập',editing:'Đang nhập',submitted:'Chờ duyệt',returned:'Cần chỉnh sửa',approved:'Đã duyệt'};
const PERIOD_STATUS={draft:'Bản nháp',open:'Chưa nhập',in_progress:'Đang thực hiện',submitted:'Chờ duyệt',approved:'Đã duyệt',published:'Đã publish',locked:'Đã khóa',reopened:'Mở lại'};
const AUDIT_ACTION={period_created:'Tạo kỳ báo cáo',assignee_changed:'Thay đổi người thực hiện',draft_saved:'Lưu nháp',submit:'Gửi duyệt',return:'Trả lại phiếu',recall:'Thu hồi phiếu để sửa',approve:'Duyệt phiếu',published:'Publish dashboard',reopened:'Thu hồi báo cáo',deadline_changed:'Thay đổi hạn nhập liệu'};
const emptyNote={highlights:'',issues:'',risks:'',proposals:'',next_month_plan:''};
const valueOf=value=>value===null||value===undefined?'':value;
const dateValueOf=value=>{
  if(value===null||value===undefined||value==='')return '';
  const text=String(value);
  const iso=text.match(/^(\d{4}-\d{2}-\d{2})/);
  if(iso)return iso[1];
  const date=new Date(value);
  return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10);
};
const displayNumber=value=>value===null||value===undefined||value===''?'—':formatInputNumber(value);
const displayCurrency=value=>value===null||value===undefined||value===''||!Number.isFinite(Number(value))?'—':Math.round(Number(value)).toLocaleString('vi-VN',{maximumFractionDigits:0});
const displayPercent=value=>value===null||value===undefined||!Number.isFinite(Number(value))?'—':`${(Number(value)*100).toLocaleString('vi-VN',{maximumFractionDigits:1})}%`;
const completionRate=kpi=>{const target=Number(kpi.target_value),actual=Number(kpi.actual_value);if(kpi.target_value===null||kpi.target_value===undefined||kpi.target_value===''||kpi.actual_value===null||kpi.actual_value===undefined||kpi.actual_value===''||!Number.isFinite(target)||!Number.isFinite(actual))return null;if(kpi.evaluation_direction==='monitor')return target===0?null:actual/target;if(kpi.evaluation_direction==='decrease_good')return actual<=0?1.2:target/actual;return target===0?(actual>0?1.2:null):actual/target;};
const DIRECTION_OPTIONS=[['increase_good','Tăng tốt'],['decrease_good','Giảm tốt'],['monitor','Theo dõi']];
const LONG_TEXT_FIELDS=new Set(['note','trend','next_action','implementation_result','output_url','owner_unit','cooperating_unit']);
const toDisplayDate=value=>{if(!value)return '';const [year,month,day]=value.split('-');return day&&month&&year?`${day}/${month}/${year}`:'';};
const toInputDate=value=>{const match=String(value||'').trim().match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return match?`${match[3]}-${match[2]}-${match[1]}`:'';};
const validInputDate=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const [year,month,day]=value.split('-').map(Number),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day;};
const parseDisplayDate=value=>{const iso=toInputDate(value);return validInputDate(iso)?iso:'';};
const maskDateDigits=value=>{const digits=String(value||'').replace(/\D/g,'').slice(0,8);return [digits.slice(0,2),digits.slice(2,4),digits.slice(4,8)].filter(Boolean).join('/');};
const deploymentValue=value=>{const text=String(value||'').trim();if(text.includes(';'))return{mode:'multiple',dates:text.split(';').map(toInputDate).filter(Boolean)};if(text.includes(' - ')){const [start,end]=text.split(' - ');return{mode:'range',dates:[toInputDate(start),toInputDate(end)]};}return{mode:'single',dates:[toInputDate(text)]};};
const deploymentCount=(mode,dates)=>{const valid=dates.filter(Boolean);if(mode==='range'&&valid.length===2){const start=new Date(`${valid[0]}T00:00:00Z`),end=new Date(`${valid[1]}T00:00:00Z`);return end>=start?Math.floor((end-start)/86400000)+1:null;}return mode==='multiple'?new Set(valid).size:valid.length?1:null;};

const formatInputNumber=formatVietnameseNumber;
const performanceClass=(value,threshold=1)=>value===null||value===undefined||!Number.isFinite(Number(value))?'':Number(value)>=threshold?'formula-good':'formula-bad';

function NumericInput({value,onChange,disabled,placeholder,ariaLabel}){
  const [draft,setDraft]=useState(()=>formatInputNumber(value));const [focused,setFocused]=useState(false);const [invalid,setInvalid]=useState(false);
  useEffect(()=>{if(!focused){setDraft(formatInputNumber(value));setInvalid(false);}},[value,focused]);
  return <input disabled={disabled} inputMode="decimal" aria-label={ariaLabel} aria-invalid={invalid} className={invalid?'number-invalid':''} title={invalid?'Dùng dấu chấm cho hàng nghìn (đủ 3 số) và một dấu phẩy cho phần thập phân.':undefined} placeholder={placeholder} value={draft} onFocus={()=>setFocused(true)} onChange={event=>{const raw=event.target.value;setDraft(raw);if(!raw.trim()){setInvalid(false);onChange(null);return;}const parsed=parseVietnameseNumber(raw,{allowIncomplete:true});setInvalid(typeof parsed!=='string');if(typeof parsed==='string')onChange(parsed);}} onBlur={()=>{setFocused(false);const parsed=parseVietnameseNumber(draft);setInvalid(parsed===null);if(typeof parsed==='string')setDraft(formatInputNumber(parsed));}}/>;
}

function CompactTextArea({value,onChange,disabled,placeholder,ariaLabel}){
  return <textarea disabled={disabled} aria-label={ariaLabel} rows="2" placeholder={placeholder} value={valueOf(value)} onChange={event=>onChange(event.target.value)}/>;
}

function MaskedDateInput({value,onChange,disabled,label='Ngày triển khai'}){
  const [draft,setDraft]=useState(()=>toDisplayDate(value));const [focused,setFocused]=useState(false);const [touched,setTouched]=useState(false);const parsed=parseDisplayDate(draft);const invalid=Boolean(draft)&&((draft.length===10&&!parsed)||(!focused&&touched&&!parsed));
  useEffect(()=>{if(!focused)setDraft(toDisplayDate(value));},[value,focused]);
  return <input disabled={disabled} inputMode="numeric" aria-label={label} aria-invalid={invalid} className={invalid?'date-invalid deployment-date-invalid':''} placeholder="DD/MM/YYYY" value={draft} onFocus={()=>setFocused(true)} onChange={event=>{const next=maskDateDigits(event.target.value);setDraft(next);const date=parseDisplayDate(next);if(date)onChange(date);else if(!next)onChange('');}} onBlur={()=>{setFocused(false);setTouched(true);}}/>;
}

function ReportDateInput({value,onChange,disabled,label='Ngày'}){
  const normalized=dateValueOf(value);const [draft,setDraft]=useState(()=>toDisplayDate(normalized));const [focused,setFocused]=useState(false);const [touched,setTouched]=useState(false);const parsed=parseDisplayDate(draft);const invalid=Boolean(draft)&&((draft.length===10&&!parsed)||(!focused&&touched&&!parsed));
  useEffect(()=>{if(!focused)setDraft(toDisplayDate(dateValueOf(value)));},[value,focused]);
  return <input disabled={disabled} inputMode="numeric" aria-label={label} aria-invalid={invalid} className={invalid?'report-date-invalid':''} title={invalid?'Nhập ngày hợp lệ theo định dạng DD/MM/YYYY.':undefined} placeholder="DD/MM/YYYY" value={draft} onFocus={()=>setFocused(true)} onChange={event=>{const next=maskDateDigits(event.target.value);setDraft(next);const date=parseDisplayDate(next);if(date)onChange(date);else if(!next)onChange('');}} onBlur={()=>{setFocused(false);setTouched(true);}}/>;
}

function RangeDateInput({dates,onChange,disabled}){
  const start=dates[0]||'',end=dates[1]||'';const invalid=Boolean(start&&end&&end<start);
  const choose=(index,next)=>{const values=[start,end];values[index]=next;if(index===0&&values[1]&&values[1]<next)values[1]='';onChange(values);};
  return <div className={`range-date-control ${invalid?'deployment-date-invalid':''}`}><div className="range-date-fields"><label><span>Từ ngày</span><input type="date" disabled={disabled} value={start} aria-label="Từ ngày triển khai" onChange={event=>choose(0,event.target.value)}/></label><i>→</i><label><span>Đến ngày</span><input type="date" disabled={disabled} min={start||undefined} value={end} aria-label="Đến ngày triển khai" onChange={event=>choose(1,event.target.value)}/></label></div>{invalid&&<small>Đến ngày phải bằng hoặc sau Từ ngày.</small>}</div>;
}

function DeploymentDateInput({value,onChange,disabled}){
  const initial=deploymentValue(value);const [mode,setMode]=useState(initial.mode);const [dates,setDates]=useState(initial.dates);const emittedValue=useRef(null);const editingSchedule=useRef(false);
  useEffect(()=>{const incoming=String(value||'');if(emittedValue.current===incoming){emittedValue.current=null;if(incoming)editingSchedule.current=false;return;}if(editingSchedule.current&&!incoming)return;const next=deploymentValue(value);setMode(next.mode);setDates(next.dates);},[value]);
  const emit=(nextMode,nextDates)=>{let output=null;if(nextMode==='single'&&nextDates[0])output=toDisplayDate(nextDates[0]);else if(nextMode==='range'&&nextDates[0]&&nextDates[1]&&deploymentCount(nextMode,nextDates)!==null)output=`${toDisplayDate(nextDates[0])} - ${toDisplayDate(nextDates[1])}`;else if(nextMode==='multiple'&&nextDates.every(Boolean)){const unique=[...new Set(nextDates)].sort();if(unique.length===nextDates.length)output=unique.map(toDisplayDate).join('; ');}if(output!==null){emittedValue.current=output;onChange(output);}};
  const changeMode=next=>{const empty=['range','multiple'].includes(next)?['','']:[''];editingSchedule.current=true;setMode(next);setDates(empty);emittedValue.current='';onChange('');};
  const updateDate=(index,next)=>{editingSchedule.current=true;const values=[...dates];values[index]=next;setDates(values);emit(mode,values);};
  const addDate=()=>{editingSchedule.current=true;setDates(items=>[...items,'']);};
  const removeDate=index=>{if(dates.length<=2)return;editingSchedule.current=true;const values=dates.filter((_,i)=>i!==index);setDates(values);if(values.every(Boolean)){const output=[...new Set(values)].sort().map(toDisplayDate).join('; ');emittedValue.current=output;onChange(output);}};
  const invalidRange=mode==='range'&&((Boolean(dates[0])!==Boolean(dates[1]))||(dates[0]&&dates[1]&&deploymentCount(mode,dates)===null));
  const selectedDates=dates.filter(Boolean);const duplicateMultiple=mode==='multiple'&&selectedDates.length!==new Set(selectedDates).size;const incompleteMultiple=mode==='multiple'&&selectedDates.length>0&&selectedDates.length!==dates.length;
  return <div className={`deployment-date-input ${invalidRange||duplicateMultiple||incompleteMultiple?'deployment-date-invalid':''}`}><select disabled={disabled} value={mode} onChange={event=>changeMode(event.target.value)} aria-label="Loại ngày triển khai"><option value="single">Một ngày</option><option value="range">Khoảng ngày</option><option value="multiple">Nhiều ngày</option></select><div className="deployment-date-values">{mode==='range'?<RangeDateInput disabled={disabled} dates={dates} onChange={values=>{setDates(values);emit(mode,values);}}/>:dates.map((date,index)=><div key={index}><MaskedDateInput disabled={disabled} value={date} label={mode==='multiple'?`Ngày ${index+1}`:'Ngày triển khai'} onChange={next=>updateDate(index,next)}/>{mode==='multiple'&&dates.length>2&&<button type="button" disabled={disabled} onClick={()=>removeDate(index)} aria-label={`Xóa ngày ${index+1}`}><X/></button>}</div>)}</div>{mode==='multiple'&&<button type="button" className="add-deployment-date" disabled={disabled} onClick={addDate}><Plus/>Thêm ngày</button>}{duplicateMultiple&&<small>Không được chọn trùng ngày.</small>}{incompleteMultiple&&<small>Vui lòng chọn đủ các ô ngày đã thêm.</small>}</div>;
}

function FieldInput({field,value,onChange,lookups,disabled}){
  if(field.type==='computed'){const previousField=['followers_previous','reach_previous'].includes(field.key);return <div className="derived-value detail-derived"><span>{previousField?displayNumber(value):displayPercent(value)}</span><em>{previousField?'Từ tháng trước':'Tự tính'}</em></div>;}
  if(field.type==='select')return <select disabled={disabled} value={valueOf(value)} onChange={e=>onChange(e.target.value)}><option value="">Chọn...</option>{(lookups[field.lookup]||[]).map(item=><option key={item.code} value={item.label}>{item.label}</option>)}</select>;
  if(field.type==='boolean')return <input disabled={disabled} type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>;
  if(field.type==='number')return <NumericInput disabled={disabled} value={value} onChange={onChange}/>;
  if(field.type==='date_text')return <DeploymentDateInput disabled={disabled} value={value} onChange={onChange}/>;
  if(LONG_TEXT_FIELDS.has(field.key))return <CompactTextArea disabled={disabled} value={value} onChange={onChange} placeholder={field.label}/>;
  if(field.type==='date')return <ReportDateInput disabled={disabled} value={value} label={field.label} onChange={onChange}/>;
  return <input disabled={disabled} type="text" value={valueOf(value)} onChange={e=>onChange(e.target.value)}/>;
}

const detailFieldValue=(row,field)=>{
  if(field.key==='student_achievement'){
    const target=Number(row.student_target),actual=Number(row.active_student_count);
    return row.student_target!==null&&row.student_target!==undefined&&row.student_target!==''&&Number.isFinite(target)&&target!==0&&Number.isFinite(actual)?actual/target:null;
  }
  return row[field.key];
};

function RevenueDetailTable({details,editable,masterData,updateRow,removeRow}){
  const totalRevenue=details.reduce((sum,row)=>sum+(Number(row.revenue)||0),0);const totalOrders=details.reduce((sum,row)=>sum+(Number(row.order_count)||0),0);const totalTarget=details.reduce((sum,row)=>sum+(Number(row.monthly_target)||0),0);const totalPrevious=details.reduce((sum,row)=>sum+(Number(row.previous_revenue)||0),0);const totalPrior=details.reduce((sum,row)=>sum+(Number(row.prior_year_revenue)||0),0);
  const pct=(value,base)=>base?value/base:null;const change=(value,base)=>base?(value-base)/base:null;
  return <div className="detail-entry-table revenue-detail-table"><table><thead><tr><th>#</th><th>Nhóm sản phẩm</th><th>Sản phẩm</th><th>Số đơn</th><th>Doanh thu</th><th>Tỷ trọng</th><th>KH tháng</th><th>% HT KH</th><th>DT tháng trước</th><th>% vs TTr</th><th>Cùng kỳ</th><th>% vs CK</th><th>Ghi chú</th><th/></tr></thead><tbody>{details.map((row,index)=>{const revenue=Number(row.revenue)||0,previous=Number(row.previous_revenue)||0,prior=Number(row.prior_year_revenue)||0;return <tr key={row.row_key||row.id||index}><td>{index+1}</td><td><select disabled={!editable} value={valueOf(row.product_group)} onChange={e=>updateRow(index,'product_group',e.target.value)}><option value="">Chọn nhóm</option>{(masterData.product_group||[]).map(x=><option key={x.code} value={x.label}>{x.label}</option>)}</select></td><td><input disabled={!editable} value={valueOf(row.product_name)} placeholder="Tên sản phẩm" onChange={e=>updateRow(index,'product_name',e.target.value)}/></td><td><NumericInput disabled={!editable} value={row.order_count} onChange={value=>updateRow(index,'order_count',value)}/></td><td><NumericInput disabled={!editable} value={row.revenue} onChange={value=>updateRow(index,'revenue',value)}/></td><td className="formula-cell">{displayPercent(totalRevenue?revenue/totalRevenue:null)}</td><td><NumericInput disabled={!editable} value={row.monthly_target} onChange={value=>updateRow(index,'monthly_target',value)}/></td><td className={`formula-cell ${performanceClass(pct(revenue,Number(row.monthly_target)||0))}`}>{displayPercent(pct(revenue,Number(row.monthly_target)||0))}</td><td>{displayNumber(previous)}</td><td className="formula-cell">{displayPercent(change(revenue,previous))}</td><td>{displayNumber(prior)}</td><td className="formula-cell">{displayPercent(change(revenue,prior))}</td><td><CompactTextArea disabled={!editable} value={row.note} onChange={value=>updateRow(index,'note',value)} placeholder="Ghi chú"/></td><td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>})}<tr className="revenue-total-row"><td colSpan="3">TỔNG</td><td>{displayNumber(totalOrders)}</td><td>{displayNumber(totalRevenue)}</td><td>100%</td><td>{displayNumber(totalTarget)}</td><td>{displayPercent(pct(totalRevenue,totalTarget))}</td><td>{displayNumber(totalPrevious)}</td><td>{displayPercent(change(totalRevenue,totalPrevious))}</td><td>{displayNumber(totalPrior)}</td><td>{displayPercent(change(totalRevenue,totalPrior))}</td><td colSpan="2"/></tr></tbody></table>{!details.length&&<div className="no-rows">Chưa có sản phẩm. Chọn “Thêm dòng” để bắt đầu.</div>}</div>;
}

function AdsTrafficTable({details,editable,masterData,updateRow,removeRow}){
  const sum=key=>details.reduce((total,row)=>total+(Number(row[key])||0),0);const totalTarget=sum('budget_target'),totalActual=sum('budget_actual'),totalLead=sum('lead_count'),totalOrder=sum('order_count'),totalRevenue=sum('revenue');const ratio=(value,base)=>base?value/base:null;
  return <div className="detail-entry-table ads-traffic-table"><table><thead><tr><th>#</th><th>Nguồn traffic</th><th>KH ngân sách</th><th>NS thực hiện</th><th>% HT NS</th><th>Data</th><th>Đơn hàng</th><th>Doanh thu</th><th>Tỷ lệ chốt</th><th>DT/đơn</th><th>CPR</th><th>Xu hướng</th><th>Ghi chú</th><th/></tr></thead><tbody>{details.map((row,index)=>{const target=Number(row.budget_target)||0,actual=Number(row.budget_actual)||0,lead=Number(row.lead_count)||0,orders=Number(row.order_count)||0,revenue=Number(row.revenue)||0;return <tr key={row.row_key||row.id||index}><td>{index+1}</td><td><select disabled={!editable} value={valueOf(row.traffic_source)} onChange={e=>updateRow(index,'traffic_source',e.target.value)}><option value="">Chọn nguồn</option>{(masterData.ads_source||[]).map(x=><option key={x.code} value={x.label}>{x.label}</option>)}</select></td>{[['budget_target',target],['budget_actual',actual]].map(([key])=><td key={key}><NumericInput disabled={!editable} value={row[key]} onChange={value=>updateRow(index,key,value)}/></td>)}<td className={`formula-cell ${performanceClass(ratio(actual,target))}`}>{displayPercent(ratio(actual,target))}</td>{['lead_count','order_count','revenue'].map(key=><td key={key}><NumericInput disabled={!editable} value={row[key]} onChange={value=>updateRow(index,key,value)}/></td>)}<td className="formula-cell">{displayPercent(ratio(orders,lead))}</td><td className="formula-cell">{displayCurrency(ratio(revenue,orders))}</td><td className="formula-cell">{displayPercent(ratio(actual,revenue))}</td><td><input disabled={!editable} value={valueOf(row.trend)} placeholder="Xu hướng" onChange={e=>updateRow(index,'trend',e.target.value)}/></td><td><input disabled={!editable} value={valueOf(row.note)} placeholder="Ghi chú" onChange={e=>updateRow(index,'note',e.target.value)}/></td><td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>})}<tr className="revenue-total-row"><td colSpan="2">TỔNG</td><td>{displayNumber(totalTarget)}</td><td>{displayNumber(totalActual)}</td><td>{displayPercent(ratio(totalActual,totalTarget))}</td><td>{displayNumber(totalLead)}</td><td>{displayNumber(totalOrder)}</td><td>{displayNumber(totalRevenue)}</td><td>{displayPercent(ratio(totalOrder,totalLead))}</td><td>{displayCurrency(ratio(totalRevenue,totalOrder))}</td><td>{displayPercent(ratio(totalActual,totalRevenue))}</td><td colSpan="3"/></tr></tbody></table>{!details.length&&<div className="no-rows compact">Chưa có nguồn traffic. Chọn “Thêm dòng” để bắt đầu.</div>}</div>;
}

function AdsProductTable({rows,editable,masterData,updateRow,removeRow}){
  const totalCost=rows.reduce((sum,row)=>sum+(Number(row.ad_cost)||0),0),totalRevenue=rows.reduce((sum,row)=>sum+(Number(row.revenue)||0),0);
  return <div className="detail-entry-table ads-product-table"><table><thead><tr><th>#</th><th>Nhóm sản phẩm</th><th>Sản phẩm</th><th>Chi phí Ads</th><th>Tỷ trọng Ads</th><th>Doanh thu</th><th>Tỷ trọng DT</th><th>Ghi chú</th><th/></tr></thead><tbody>{rows.map((row,index)=>{const cost=Number(row.ad_cost)||0,revenue=Number(row.revenue)||0;return <tr key={row.row_key||row.id||index}><td>{index+1}</td><td><select disabled={!editable} value={valueOf(row.product_group)} onChange={e=>updateRow(index,'product_group',e.target.value)}><option value="">Chọn nhóm</option>{(masterData.product_group||[]).map(x=><option key={x.code} value={x.label}>{x.label}</option>)}</select></td><td><input disabled={!editable} value={valueOf(row.product_name)} placeholder="Tên sản phẩm" onChange={e=>updateRow(index,'product_name',e.target.value)}/></td><td><NumericInput disabled={!editable} value={row.ad_cost} onChange={value=>updateRow(index,'ad_cost',value)}/></td><td className="formula-cell">{displayPercent(totalCost?cost/totalCost:null)}</td><td><NumericInput disabled={!editable} value={row.revenue} onChange={value=>updateRow(index,'revenue',value)}/></td><td className="formula-cell">{displayPercent(totalRevenue?revenue/totalRevenue:null)}</td><td><input disabled={!editable} value={valueOf(row.note)} placeholder="Ghi chú" onChange={e=>updateRow(index,'note',e.target.value)}/></td><td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>})}<tr className="revenue-total-row"><td colSpan="3">TỔNG</td><td>{displayNumber(totalCost)}</td><td>{displayPercent(totalCost?1:null)}</td><td>{displayNumber(totalRevenue)}</td><td>{displayPercent(totalRevenue?1:null)}</td><td colSpan="2"/></tr></tbody></table>{!rows.length&&<div className="no-rows compact">Chưa có sản phẩm. Chọn “Thêm dòng” để bắt đầu.</div>}</div>;
}

function CommunicationTotalRow({details,fields,kpis}){
  const sum=key=>details.reduce((total,row)=>total+(Number(row[key])||0),0);
  const followersCurrent=sum('followers_current'),followersPrevious=sum('followers_previous');
  const reachCurrent=sum('reach_current'),reachPrevious=sum('reach_previous');
  const engagementRate=kpis.find(kpi=>kpi.code==='TT_05')?.actual_value;
  const value=key=>({
    followers_current:displayNumber(followersCurrent),followers_previous:displayNumber(followersPrevious),followers_growth:displayPercent(followersPrevious?(followersCurrent-followersPrevious)/followersPrevious:null),
    reach_current:displayNumber(reachCurrent),reach_previous:displayNumber(reachPrevious),reach_growth:displayPercent(reachPrevious?(reachCurrent-reachPrevious)/reachPrevious:null),
    video_views:displayNumber(sum('video_views')),engagement_rate:displayPercent(engagementRate),lead_count:displayNumber(sum('lead_count')),revenue:displayNumber(sum('revenue')),note:''
  })[key]??'—';
  return <tr className="revenue-total-row communication-total-row"><td colSpan="2">TỔNG</td>{fields.slice(1).map(field=><td key={field.key}>{value(field.key)}</td>)}<td/></tr>;
}

function GenericDetailTotalRow({team,details,fields}){
  const sum=key=>details.reduce((total,row)=>total+(Number(row[key])||0),0);const present=key=>details.filter(row=>row[key]!==null&&row[key]!==undefined&&row[key]!=='');
  const value=field=>{if(team==='TRAIN'&&field.key==='student_achievement')return displayPercent(sum('student_target')?sum('active_student_count')/sum('student_target'):null);if(team==='TRAIN'&&field.key==='output_rate'){const rows=present(field.key);return rows.length?displayPercent(rows.reduce((total,row)=>total+Number(row[field.key]),0)/rows.length):'—';}if(team==='PROD'&&field.key==='progress_percent'){const rows=present(field.key);return rows.length?displayNumber(rows.reduce((total,row)=>total+Number(row[field.key]),0)/rows.length):'—';}return field.type==='number'?displayNumber(sum(field.key)):'';};
  return <tr className="revenue-total-row generic-detail-total-row"><td colSpan="2">TỔNG</td>{fields.slice(1).map(field=><td key={field.key}>{value(field)}</td>)}<td/></tr>;
}

export default function ManualReportPage({currentUser,showMsg}){
  const navigate=useNavigate();const {periodId,teamCode}=useParams();const team=(teamCode||'REV').toUpperCase();const permissions=currentUser?.permissions||[];const canEdit=permissions.includes('reports.entry')||permissions.includes('reports.review')||permissions.includes('reports.manage');const canReview=permissions.includes('reports.review')||permissions.includes('reports.manage');const canPublish=permissions.includes('reports.publish')||permissions.includes('reports.manage');const canManage=permissions.includes('reports.manage');
  const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [deadline,setDeadline]=useState('');const [bootstrap,setBootstrap]=useState({teams:[],masterData:{}});
  const [period,setPeriod]=useState(null);const [workspace,setWorkspace]=useState(null);const [kpis,setKpis]=useState([]);const [details,setDetails]=useState([]);const [adsProducts,setAdsProducts]=useState([]);const [note,setNote]=useState(emptyNote);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false);const saveTimer=useRef(null);const loadedRef=useRef(false);const showMsgRef=useRef(showMsg);
  const [templateBusy,setTemplateBusy]=useState(false);const [templateReview,setTemplateReview]=useState(null);const templateInput=useRef(null);
  const [audit,setAudit]=useState([]);const [auditOpen,setAuditOpen]=useState(false);
  const toggleAudit=async()=>{const next=!auditOpen;setAuditOpen(next);if(next&&period?.id)try{const r=await api.get(`/reports/manual/periods/${period.id}/audit`,{params:{teamCode:team,limit:30}});setAudit(r.data.data||[]);}catch{setAudit([]);}};

  useEffect(()=>{showMsgRef.current=showMsg;},[showMsg]);
  useEffect(()=>{api.get('/reports/bootstrap').then(r=>setBootstrap(r.data.data)).catch(()=>showMsgRef.current('Không thể tải master báo cáo.','error'));},[]);
  const findPeriod=useCallback(async()=>{setLoading(true);setWorkspace(null);try{const r=periodId?await api.get(`/reports/manual/periods/${periodId}`):await api.get('/reports/manual/periods/find',{params:{year,month}});const data=r.data.data;setPeriod(data);setYear(Number(data.year));setMonth(Number(data.month));const selected=data.submissions?.find(s=>s.teamCode===team)||data.submissions?.[0];if(selected&&selected.teamCode!==team)navigate(`/reports/manage/${data.id}/${selected.teamCode}`,{replace:true});else if(selected&&!teamCode)navigate(`/reports/manage/${data.id}/${selected.teamCode}`,{replace:true});}catch(error){if(error.response?.status===404)setPeriod(null);else showMsgRef.current(error.response?.data?.error||'Không thể tải kỳ báo cáo.','error');}finally{setLoading(false);}},[periodId,year,month,team,teamCode,navigate]);
  useEffect(()=>{findPeriod();},[periodId,teamCode]); // eslint-disable-line react-hooks/exhaustive-deps
  const loadWorkspace=useCallback(async()=>{if(!period?.id)return;setLoading(true);loadedRef.current=false;try{const r=await api.get(`/reports/manual/periods/${period.id}/teams/${team}`);const data=r.data.data;setWorkspace(data);setKpis(data.kpis||[]);setDetails(data.details||[]);setAdsProducts(data.adsProducts||[]);setNote({...emptyNote,...data.note});setDirty(false);setTimeout(()=>{loadedRef.current=true;},0);}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể tải phiếu nhập liệu.','error');}finally{setLoading(false);}},[period?.id,team]);
  useEffect(()=>{loadWorkspace();},[loadWorkspace]);
  useEffect(()=>{if(!period?.id)return;api.get(`/reports/manual/periods/${period.id}/audit`,{params:{teamCode:team,limit:30}}).then(r=>setAudit(r.data.data||[])).catch(()=>setAudit([]));},[period?.id,team,workspace?.updated_at]);

  const createPeriod=async()=>{setSaving(true);try{await api.post('/reports/manual/periods',{year,month,deadline:deadline||null,copyTargets:true});showMsgRef.current(`Đã tạo kỳ tháng ${month}/${year}.`);await findPeriod();}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể tạo kỳ.','error');}finally{setSaving(false);}};
  const editable=canEdit&&workspace?.capabilities?.canEdit!==false&&['draft','editing','returned'].includes(workspace?.submission_status);
  const markDirty=()=>{if(loadedRef.current)setDirty(true);};
  const save=useCallback(async(silent=false)=>{if(!workspace||!editable||saving)return null;if(document.querySelector('.manual-report-page input.number-invalid')){if(!silent)showMsgRef.current('Có số chưa đúng định dạng: dấu chấm phải phân nhóm đủ 3 số và chỉ dùng một dấu phẩy thập phân.','error');return null;}if(document.querySelector('.manual-report-page .deployment-date-invalid')){if(!silent)showMsgRef.current('Khoảng ngày triển khai phải có đủ từ ngày, đến ngày và ngày kết thúc không được trước ngày bắt đầu.','error');return null;}const incompleteDynamicKpi=kpis.some(kpi=>!String(kpi.code||'').trim()||!String(kpi.name||'').trim()||!String(kpi.unit||'').trim()||!String(kpi.evaluation_direction||'').trim());if(incompleteDynamicKpi){if(!silent)showMsgRef.current('Vui lòng nhập đủ mã KPI, tên chỉ số, đơn vị và chiều đánh giá.','error');return null;}setSaving(true);try{const r=await api.put(`/reports/manual/periods/${period.id}/teams/${team}`,{kpis,details,adsProducts,note,revision:workspace.revision,auditAction:silent?null:'save_draft'});const data=r.data.data;setWorkspace(data);setKpis(data.kpis||[]);setDetails(data.details||[]);setAdsProducts(data.adsProducts||[]);setNote({...emptyNote,...data.note});setDirty(false);if(!silent)showMsgRef.current('Đã lưu dữ liệu báo cáo.');return data;}catch(error){if(error.response?.data?.code==='REPORT_REVISION_CONFLICT')showMsgRef.current('Dữ liệu đã được cập nhật ở cửa sổ khác. Vui lòng bấm Làm mới.','error');else if(!silent)showMsgRef.current(error.response?.data?.error||'Không thể lưu dữ liệu.','error');return null;}finally{setSaving(false);}},[workspace,editable,saving,period?.id,team,kpis,details,adsProducts,note]);
  useEffect(()=>{if(!dirty||!editable)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>save(true),1500);return()=>clearTimeout(saveTimer.current);},[dirty,editable,save]);
  const updateKpi=(index,key,value)=>{setKpis(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));markDirty();};
  const updateRow=(index,key,value)=>{setDetails(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));markDirty();};
  const updateAdsProduct=(index,key,value)=>{setAdsProducts(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));markDirty();};
  const addRow=()=>{setDetails(items=>[...items,{row_key:crypto.randomUUID()}]);markDirty();};
  const addAdsProduct=()=>{setAdsProducts(items=>[...items,{row_key:crypto.randomUUID()}]);markDirty();};
  const removeRow=index=>{setDetails(items=>items.filter((_,i)=>i!==index));markDirty();};
  const removeAdsProduct=index=>{setAdsProducts(items=>items.filter((_,i)=>i!==index));markDirty();};
  const updateNote=(key,value)=>{setNote(item=>({...item,[key]:value}));markDirty();};
  const downloadTemplate=async()=>{if(!period?.id)return;setTemplateBusy(true);try{const response=await api.get(`/reports/manual/periods/${period.id}/teams/${team}/template`,{responseType:'blob'});const disposition=response.headers['content-disposition']||'';const encoded=disposition.match(/filename\*=UTF-8''([^;]+)/i)?.[1];const name=encoded?decodeURIComponent(encoded):`Bao_cao_${team}_Thang_${month}_${year}.xlsx`;const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể tải template báo cáo.','error');}finally{setTemplateBusy(false);}};
  const importTemplate=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!/\.xlsx$/i.test(file.name)){showMsgRef.current('Chỉ hỗ trợ file .xlsx được tải từ hệ thống.','error');return;}if(file.size>10*1024*1024){showMsgRef.current('File Excel không được vượt quá 10 MB.','error');return;}setTemplateBusy(true);try{const fileBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const response=await api.post(`/reports/manual/periods/${period.id}/teams/${team}/template/import`,{fileName:file.name,fileBase64});setTemplateReview({...response.data.data,fileName:file.name});}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể đọc template báo cáo.','error');}finally{setTemplateBusy(false);}};
  const applyTemplate=()=>{if(!templateReview||templateReview.errors?.length)return;setKpis(templateReview.kpis||[]);setDetails(templateReview.details||[]);setAdsProducts(templateReview.adsProducts||[]);setNote({...emptyNote,...templateReview.note});setTemplateReview(null);markDirty();showMsgRef.current('Đã áp dụng dữ liệu từ template. Hệ thống sẽ tự động lưu bản nháp.');};
  const transition=async(action)=>{if(action==='submit'){if(document.querySelector('.manual-report-page input.number-invalid')){showMsgRef.current('Vui lòng sửa các ô số đang sai định dạng trước khi gửi duyệt.','error');return;}const saved=await save(true);if(!saved)return;}const needsReason=['return','recall'].includes(action);const note=needsReason?window.prompt(action==='recall'?'Nhập lý do thu hồi riêng phiếu này để sửa (bắt buộc):':'Nhập lý do trả lại phiếu (bắt buộc):',''):'';if(needsReason&&note===null)return;try{await api.post(`/reports/manual/periods/${period.id}/teams/${team}/workflow`,{action,note});showMsgRef.current(action==='submit'?'Đã gửi bộ phận duyệt.':action==='approve'?'Đã duyệt bộ phận.':action==='recall'?'Đã thu hồi riêng phiếu này để chỉnh sửa.':'Đã trả lại phiếu nhập liệu.');await findPeriod();await loadWorkspace();}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể cập nhật trạng thái.','error');}};
  const preview=async()=>{if(dirty&&editable){const saved=await save(true);if(!saved)return;}window.open(`/reports/kpi?previewPeriodId=${period.id}&team=${team}`,'_blank','noopener,noreferrer');};
  const publish=async()=>{try{await api.post(`/reports/manual/periods/${period.id}/publish`);showMsgRef.current('Đã publish dữ liệu lên dashboard.');navigate('/reports/manage');}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể publish báo cáo.','error');}};
  const reopen=async()=>{const reason=window.prompt(`Nhập lý do thu hồi báo cáo tháng ${month}/${year} để cập nhật:`, '');if(reason===null)return;setSaving(true);try{await api.post(`/reports/manual/periods/${period.id}/reopen`,{reason});showMsgRef.current('Đã mở phiên chỉnh sửa mới từ bản đã publish.');await findPeriod();}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể thu hồi báo cáo.','error');}finally{setSaving(false);}};
  const validation=workspace?.validation_result||{errors:[],warnings:[]};
  const approvedCount=useMemo(()=>period?.submissions?.filter(s=>s.status==='approved').length||0,[period]);
  const progress=useMemo(()=>{const total=period?.submissions?.length||0;return total?Math.round(approvedCount/total*100):0;},[period,approvedCount]);
  const dynamicKpi=true;

  return <div className="manual-report-page">
    <header className="manual-header"><div><button className="back" onClick={()=>navigate('/reports/manage')} title="Quay lại danh sách kỳ"><ArrowLeft/></button><div><span>PHIẾU BÁO CÁO · {workspace?.team_code||team}</span><h1>{workspace?.team_name||'Chi tiết phiếu báo cáo'}</h1><p>Kỳ tháng {month}/{year} · Hoàn thiện dữ liệu, kiểm tra và gửi duyệt.</p></div></div>{period&&<div className="period-progress"><div><span>TIẾN ĐỘ TOÀN KỲ</span><strong>{approvedCount}/{period.submissions?.length||6} bộ phận</strong></div><i><b style={{width:`${progress}%`}}/></i>{canPublish&&period.version_status==='draft'&&<button onClick={publish} disabled={progress<100}>Publish dashboard</button>}</div>}</header>
    <section className="manual-period-bar"><div><strong>Kỳ tháng {month}/{year}</strong><span className={`period-state ${period?.status||''}`}>{PERIOD_STATUS[period?.status]||period?.status||'—'}</span></div><div>{period?.status==='published'&&canPublish?<button className="reopen-period" onClick={reopen} disabled={saving}><RotateCcw/>Thu hồi để cập nhật</button>:<span>Cập nhật dữ liệu và tiến độ mới nhất</span>}<button onClick={findPeriod}><RefreshCw/>Làm mới</button></div></section>
    {loading&&!workspace?<div className="manual-empty"><RefreshCw className="spin"/>Đang tải dữ liệu…</div>:!period?<section className="create-period-card"><span>01</span><h2>Chưa tạo kỳ báo cáo</h2><p>Tạo kỳ sẽ sinh phiếu nhập liệu và danh sách KPI cho toàn bộ sáu bộ phận.</p>{canManage?<div><label>Hạn nhập liệu<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button onClick={createPeriod} disabled={saving}><Plus/>Tạo kỳ tháng {month}/{year}</button></div>:<small>Liên hệ quản trị báo cáo để tạo kỳ.</small>}</section>:<div className="manual-layout">
      {workspace&&<main className="entry-workspace">{period?.status==='published'&&<section className="published-readonly"><Eye/><div><b>Đang xem dữ liệu đã publish</b><span>Phiếu được khóa chỉnh sửa. Chọn “Thu hồi để cập nhật” để tạo phiên bản mới.</span></div></section>}<section className="workspace-title"><div><div className="workspace-code">{workspace.team_code}</div><div><h2>{workspace.team_name}</h2><p>Phiên bản {workspace.version_no}<span className={`submission-state ${workspace.submission_status}`}>{STATUS[workspace.submission_status]}</span></p></div></div><div><span className={`save-state ${saving?'saving':dirty?'dirty':'saved'}`}>{saving?'Đang lưu…':dirty?'Có thay đổi chưa lưu':period?.status==='published'?'Chỉ xem':'Đã đồng bộ'}</span><div className="template-actions"><button onClick={preview} disabled={saving}><Eye/>Preview dashboard</button><button onClick={downloadTemplate} disabled={templateBusy}><Download/>Tải form Excel</button>{editable&&<><button onClick={()=>templateInput.current?.click()} disabled={templateBusy}><Upload/>Import form</button><input ref={templateInput} type="file" accept=".xlsx" hidden onChange={importTemplate}/></>}</div><button className="save-draft" onClick={()=>save(false)} disabled={!editable||saving}><Save/>Lưu nháp</button></div></section>
        {(validation.errors?.length>0||validation.warnings?.length>0)&&<section className="validation-panel"><AlertCircle/><div>{validation.errors?.map(x=><p className="error" key={x}>{x}</p>)}{validation.warnings?.map(x=><p key={x}>{x}</p>)}</div></section>}
        <section className="entry-section kpi-section"><header><div><span>01 · KPI TỔNG HỢP</span><h3>Kế hoạch và kết quả</h3></div><div className="kpi-legend"><span><i/>Bộ KPI theo cấu hình kỳ</span><span><i/>Không được thêm hoặc xóa tại phiếu</span></div></header><div className="kpi-entry-table revenue-kpi-table"><table><thead><tr><th>Mã KPI</th><th>Chỉ số KPI</th><th>Đơn vị</th><th>Chiều đánh giá</th><th>Kế hoạch</th><th>Thực hiện</th><th>% Kết quả</th><th>Tháng trước</th><th>% vs TTr</th><th>Cùng kỳ</th><th>% vs CK</th><th>Ghi chú</th></tr></thead><tbody>{kpis.map((kpi,index)=><tr key={kpi.code} className={kpi.input_mode==='derived'?'derived-row':'manual-row'}><td><code className="locked-kpi-code">{kpi.code}</code></td><td><strong className="locked-kpi-name">{kpi.name}</strong></td><td><span className="unit-pill">{kpi.unit}</span></td><td><span className="direction-pill">{DIRECTION_OPTIONS.find(item=>item[0]===kpi.evaluation_direction)?.[1]||'Theo dõi'}</span></td><td><NumericInput ariaLabel={`Kế hoạch ${kpi.name}`} disabled={!editable} placeholder="Kế hoạch" value={kpi.target_value} onChange={value=>updateKpi(index,'target_value',value)}/></td><td>{kpi.input_mode==='derived'?<div className="derived-value"><span>{displayNumber(kpi.actual_value)}</span><em>Tự tính từ chi tiết</em></div>:<NumericInput ariaLabel={`Thực hiện ${kpi.name}`} disabled={!editable} placeholder="Thực hiện" value={kpi.actual_value} onChange={value=>updateKpi(index,'actual_value',value)}/>}</td><td className="formula-cell" title={kpi.evaluation_direction==='monitor'?'Tỷ lệ Thực hiện/Kế hoạch; không dùng để đánh giá hoàn thành.':'Tỷ lệ hoàn thành theo chiều đánh giá.'}>{displayPercent(completionRate(kpi))}</td><td><strong className="previous-value">{displayNumber(kpi.previous_value)}</strong></td><td className="formula-cell">{displayPercent(kpi.previous_change)}</td><td>{displayNumber(kpi.prior_year_value)}</td><td className="formula-cell">{displayPercent(kpi.prior_year_change)}</td><td><input aria-label={`Ghi chú ${kpi.name}`} disabled={!editable} placeholder="Ghi chú…" value={valueOf(kpi.note)} onChange={e=>updateKpi(index,'note',e.target.value)}/></td></tr>)}</tbody></table></div></section>
        <section className="entry-section"><header><div><span>02 · DỮ LIỆU CHI TIẾT</span><h3>{workspace.config.title}</h3></div><button onClick={addRow} disabled={!editable}><Plus/>Thêm dòng</button></header><div className="entry-guide">{workspace.config.instructions.map(item=><p key={item}><Check/>{item}</p>)}</div>{team==='REV'?<RevenueDetailTable details={details} editable={editable} masterData={bootstrap.masterData||{}} updateRow={updateRow} removeRow={removeRow}/>:team==='ADS'?<AdsTrafficTable details={details} editable={editable} masterData={bootstrap.masterData||{}} updateRow={updateRow} removeRow={removeRow}/>:<div className={`detail-entry-table ${team.toLowerCase()}-detail-table`}><table><thead><tr><th>#</th>{workspace.config.fields.map(field=><th className={`field-${field.type} field-${field.key}`} key={field.key}>{field.label}{field.required&&<b>*</b>}</th>)}<th/></tr></thead><tbody>{details.map((row,index)=><tr key={row.row_key||row.id||index}><td>{index+1}</td>{workspace.config.fields.map(field=><td className={`field-${field.type} field-${field.key}`} key={field.key}><FieldInput field={field} value={detailFieldValue(row,field)} onChange={value=>updateRow(index,field.key,value)} lookups={bootstrap.masterData||{}} disabled={!editable}/></td>)}<td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>)}{team==='COM'&&details.length>0&&<CommunicationTotalRow details={details} fields={workspace.config.fields} kpis={kpis}/>} {['TRADE','TRAIN','PROD'].includes(team)&&details.length>0&&<GenericDetailTotalRow team={team} details={details} fields={workspace.config.fields}/>}</tbody></table>{!details.length&&<div className="no-rows compact">Chưa có dữ liệu. Chọn “Thêm dòng” để bắt đầu.</div>}</div>}</section>
        {team==='ADS'&&<section className="entry-section"><header><div><span>03 · PHÂN BỔ NGÂN SÁCH</span><h3>Tỷ trọng Ads theo sản phẩm</h3></div><button onClick={addAdsProduct} disabled={!editable}><Plus/>Thêm dòng</button></header><div className="entry-guide"><p><Check/>Chi phí Ads và doanh thu được nhập theo từng sản phẩm.</p><p><Check/>Tỷ trọng được hệ thống tự tính trên tổng dữ liệu đã nhập.</p></div><AdsProductTable rows={adsProducts} editable={editable} masterData={bootstrap.masterData||{}} updateRow={updateAdsProduct} removeRow={removeAdsProduct}/></section>}
        <section className={`entry-section notes-entry ${dynamicKpi?'revenue-notes':''}`}><header><div><span>{team==='ADS'?'04':'03'} · NHẬN XÉT</span><h3>Nhận xét và đề xuất điều hành</h3></div><small>Thông tin phục vụ tổng hợp và điều hành kỳ báo cáo</small></header><div>{(dynamicKpi?[['highlights','Điểm nổi bật','Kết quả tích cực, cột mốc hoặc thay đổi đáng chú ý'],['issues','Nguyên nhân / vấn đề','Nguyên nhân ảnh hưởng đến kết quả thực hiện'],['risks','Rủi ro / vướng mắc','Rủi ro hiện tại và vấn đề cần hỗ trợ'],['proposals','Đề xuất / kế hoạch tháng tới','Hành động, người phụ trách và kế hoạch tiếp theo']]:[['highlights','Điểm nổi bật','Kết quả tích cực và thay đổi đáng chú ý'],['issues','Nguyên nhân / vấn đề','Nguyên nhân ảnh hưởng đến kết quả'],['risks','Rủi ro / vướng mắc','Rủi ro và vấn đề cần hỗ trợ'],['proposals','Đề xuất','Giải pháp và đề xuất điều hành'],['next_month_plan','Kế hoạch tháng tới','Hành động ưu tiên trong kỳ tiếp theo']]).map(([key,label,hint])=><label key={key}><span>{label}</span><small>{hint}</small><textarea disabled={!editable} placeholder={`Nhập ${label.toLowerCase()}…`} value={note[key]||''} onChange={e=>updateNote(key,e.target.value)}/><em>{(note[key]||'').length} ký tự</em></label>)}</div></section>
        <section className="entry-section audit-timeline"><header><div><span>LỊCH SỬ PHIẾU</span><h3>Hoạt động và thay đổi</h3></div><button onClick={toggleAudit}>{auditOpen?'Thu gọn':`Xem ${audit.length} hoạt động`}</button></header>{auditOpen&&<div className="audit-list">{audit.map(item=><article key={item.id}><i/><div><b>{AUDIT_ACTION[item.action]||item.action}</b><span>{item.actor_name||item.actor_email||'Hệ thống'} · {new Date(item.created_at).toLocaleString('vi-VN')}</span>{item.change_summary?.reason&&<p>Lý do: {item.change_summary.reason}</p>}{item.action==='assignee_changed'&&<p>{item.change_summary?.assignedUserId?'Đã cập nhật người phụ trách':'Đã bỏ phân công'}</p>}</div></article>)}{!audit.length&&<p className="audit-empty">Chưa có hoạt động được ghi nhận.</p>}</div>}</section>
        <footer className="workflow-actions"><div><span className={`autosave-dot ${saving?'saving':dirty?'dirty':'saved'}`}/><span>{saving?'Đang tự động lưu…':dirty?'Đang chờ tự động lưu':'Mọi thay đổi đã được lưu'}</span></div><div><button onClick={preview} disabled={saving}><Eye/>Preview</button>{workspace.submission_status==='approved'&&canReview&&period?.version_status==='draft'&&<button className="return" onClick={()=>transition('recall')}><RotateCcw/>Thu hồi phiếu để sửa</button>}{workspace.submission_status==='submitted'&&canReview&&<><button className="return" onClick={()=>transition('return')}>Trả lại</button><button className="approve" onClick={()=>transition('approve')}><Check/>Duyệt bộ phận</button></>}{['editing','returned'].includes(workspace.submission_status)&&canEdit&&<button className="submit" onClick={()=>transition('submit')}><Send/>Gửi duyệt</button>}</div></footer>
      </main>}
    </div>}
    {templateReview&&<div className="template-review-backdrop"><section className="template-review-modal"><header><span><FileSpreadsheet/></span><div><small>IMPORT TEMPLATE BÁO CÁO</small><h2>Kiểm tra dữ liệu trước khi áp dụng</h2><p>{templateReview.fileName}</p></div><button onClick={()=>setTemplateReview(null)}><X/></button></header><div className="template-review-summary"><article><b>{templateReview.summary?.kpis||0}</b><span>KPI</span></article><article><b>{templateReview.summary?.details||0}</b><span>Dòng chi tiết</span></article>{team==='ADS'&&<article><b>{templateReview.summary?.adsProducts||0}</b><span>Dòng sản phẩm Ads</span></article>}<article><b>{templateReview.summary?.notes||0}/4</b><span>Nhận xét</span></article></div>{templateReview.errors?.length>0&&<div className="template-review-messages error"><strong>Không thể áp dụng</strong>{templateReview.errors.map(item=><p key={item}><AlertCircle/>{item}</p>)}</div>}{templateReview.warnings?.length>0&&<div className="template-review-messages warning"><strong>Cảnh báo</strong>{templateReview.warnings.map(item=><p key={item}><AlertCircle/>{item}</p>)}</div>}<div className="template-review-note"><Check/><span>Import chỉ cập nhật dữ liệu trên phiếu hiện tại. Các công thức và chỉ số tự tính sẽ được hệ thống tính lại sau khi lưu.</span></div><footer><button onClick={()=>setTemplateReview(null)}>Hủy</button><button className="apply" onClick={applyTemplate} disabled={templateReview.errors?.length>0}><Upload/>Áp dụng vào phiếu</button></footer></section></div>}
  </div>;
}
