import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {AlertCircle,ArrowLeft,Check,Eye,Plus,RefreshCw,RotateCcw,Save,Send,Trash2} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import api from '../../../services/api';
import './ManualReportPage.css';

const now=new Date();
const STATUS={draft:'Chưa nhập',editing:'Đang nhập',submitted:'Chờ duyệt',returned:'Cần chỉnh sửa',approved:'Đã duyệt'};
const PERIOD_STATUS={draft:'Bản nháp',open:'Chưa nhập',in_progress:'Đang thực hiện',submitted:'Chờ duyệt',approved:'Đã duyệt',published:'Đã publish',locked:'Đã khóa',reopened:'Mở lại'};
const emptyNote={highlights:'',issues:'',risks:'',proposals:'',next_month_plan:''};
const valueOf=value=>value===null||value===undefined?'':value;
const displayNumber=value=>value===null||value===undefined||value===''?'—':Number(value).toLocaleString('vi-VN',{maximumFractionDigits:2});
const displayPercent=value=>value===null||value===undefined||!Number.isFinite(Number(value))?'—':`${(Number(value)*100).toLocaleString('vi-VN',{maximumFractionDigits:1})}%`;
const DIRECTION_OPTIONS=[['increase_good','Tăng tốt'],['decrease_good','Giảm tốt'],['monitor','Theo dõi']];

function FieldInput({field,value,onChange,lookups,disabled}){
  if(field.type==='computed')return <div className="derived-value detail-derived"><span>{displayPercent(value)}</span><em>Tự tính</em></div>;
  if(field.type==='select')return <select disabled={disabled} value={valueOf(value)} onChange={e=>onChange(e.target.value)}><option value="">Chọn...</option>{(lookups[field.lookup]||[]).map(item=><option key={item.code} value={item.label}>{item.label}</option>)}</select>;
  if(field.type==='boolean')return <input disabled={disabled} type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>;
  return <input disabled={disabled} type={field.type==='number'?'number':field.type==='date'?'date':'text'} step={field.type==='number'?'any':undefined} value={valueOf(value)} onChange={e=>onChange(field.type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>;
}

function RevenueDetailTable({details,editable,masterData,updateRow,removeRow}){
  const totalRevenue=details.reduce((sum,row)=>sum+(Number(row.revenue)||0),0);const totalOrders=details.reduce((sum,row)=>sum+(Number(row.order_count)||0),0);const totalTarget=details.reduce((sum,row)=>sum+(Number(row.monthly_target)||0),0);const totalPrevious=details.reduce((sum,row)=>sum+(Number(row.previous_revenue)||0),0);const totalPrior=details.reduce((sum,row)=>sum+(Number(row.prior_year_revenue)||0),0);
  const pct=(value,base)=>base?value/base:null;const change=(value,base)=>base?(value-base)/base:null;
  return <div className="detail-entry-table revenue-detail-table"><table><thead><tr><th>#</th><th>Nhóm sản phẩm</th><th>Sản phẩm</th><th>Số đơn</th><th>Doanh thu</th><th>Tỷ trọng</th><th>KH tháng</th><th>% HT KH</th><th>DT tháng trước</th><th>% vs TTr</th><th>Cùng kỳ</th><th>% vs CK</th><th>Ghi chú</th><th/></tr></thead><tbody>{details.map((row,index)=>{const revenue=Number(row.revenue)||0,previous=Number(row.previous_revenue)||0,prior=Number(row.prior_year_revenue)||0;return <tr key={row.row_key||row.id||index}><td>{index+1}</td><td><select disabled={!editable} value={valueOf(row.product_group)} onChange={e=>updateRow(index,'product_group',e.target.value)}><option value="">Chọn nhóm</option>{(masterData.product_group||[]).map(x=><option key={x.code} value={x.label}>{x.label}</option>)}</select></td><td><input disabled={!editable} value={valueOf(row.product_name)} placeholder="Tên sản phẩm" onChange={e=>updateRow(index,'product_name',e.target.value)}/></td><td><input disabled={!editable} type="number" value={valueOf(row.order_count)} onChange={e=>updateRow(index,'order_count',e.target.value===''?null:Number(e.target.value))}/></td><td><input disabled={!editable} type="number" value={valueOf(row.revenue)} onChange={e=>updateRow(index,'revenue',e.target.value===''?null:Number(e.target.value))}/></td><td className="formula-cell">{displayPercent(totalRevenue?revenue/totalRevenue:null)}</td><td><input disabled={!editable} type="number" value={valueOf(row.monthly_target)} onChange={e=>updateRow(index,'monthly_target',e.target.value===''?null:Number(e.target.value))}/></td><td className="formula-cell">{displayPercent(pct(revenue,Number(row.monthly_target)||0))}</td><td>{displayNumber(previous)}</td><td className="formula-cell">{displayPercent(change(revenue,previous))}</td><td>{displayNumber(prior)}</td><td className="formula-cell">{displayPercent(change(revenue,prior))}</td><td><input disabled={!editable} value={valueOf(row.note)} onChange={e=>updateRow(index,'note',e.target.value)}/></td><td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>})}<tr className="revenue-total-row"><td colSpan="3">TỔNG</td><td>{displayNumber(totalOrders)}</td><td>{displayNumber(totalRevenue)}</td><td>100%</td><td>{displayNumber(totalTarget)}</td><td>{displayPercent(pct(totalRevenue,totalTarget))}</td><td>{displayNumber(totalPrevious)}</td><td>{displayPercent(change(totalRevenue,totalPrevious))}</td><td>{displayNumber(totalPrior)}</td><td>{displayPercent(change(totalRevenue,totalPrior))}</td><td colSpan="2"/></tr></tbody></table>{!details.length&&<div className="no-rows">Chưa có sản phẩm. Chọn “Thêm dòng” để bắt đầu.</div>}</div>;
}

function AdsTrafficTable({details,editable,masterData,updateRow,removeRow}){
  const sum=key=>details.reduce((total,row)=>total+(Number(row[key])||0),0);const totalTarget=sum('budget_target'),totalActual=sum('budget_actual'),totalLead=sum('lead_count'),totalOrder=sum('order_count'),totalRevenue=sum('revenue');const ratio=(value,base)=>base?value/base:null;
  return <div className="detail-entry-table ads-traffic-table"><table><thead><tr><th>#</th><th>Nguồn traffic</th><th>KH ngân sách</th><th>NS thực hiện</th><th>% HT NS</th><th>Data</th><th>Đơn hàng</th><th>Doanh thu</th><th>Tỷ lệ chốt</th><th>DT/đơn</th><th>CPR</th><th>Xu hướng</th><th>Ghi chú</th><th/></tr></thead><tbody>{details.map((row,index)=>{const target=Number(row.budget_target)||0,actual=Number(row.budget_actual)||0,lead=Number(row.lead_count)||0,orders=Number(row.order_count)||0,revenue=Number(row.revenue)||0;return <tr key={row.row_key||row.id||index}><td>{index+1}</td><td><select disabled={!editable} value={valueOf(row.traffic_source)} onChange={e=>updateRow(index,'traffic_source',e.target.value)}><option value="">Chọn nguồn</option>{(masterData.ads_source||[]).map(x=><option key={x.code} value={x.label}>{x.label}</option>)}</select></td>{[['budget_target',target],['budget_actual',actual]].map(([key])=><td key={key}><input disabled={!editable} type="number" value={valueOf(row[key])} onChange={e=>updateRow(index,key,e.target.value===''?null:Number(e.target.value))}/></td>)}<td className="formula-cell">{displayPercent(ratio(actual,target))}</td>{['lead_count','order_count','revenue'].map(key=><td key={key}><input disabled={!editable} type="number" value={valueOf(row[key])} onChange={e=>updateRow(index,key,e.target.value===''?null:Number(e.target.value))}/></td>)}<td className="formula-cell">{displayPercent(ratio(orders,lead))}</td><td className="formula-cell">{displayNumber(ratio(revenue,orders))}</td><td className="formula-cell">{displayPercent(ratio(actual,revenue))}</td><td><input disabled={!editable} value={valueOf(row.trend)} placeholder="Xu hướng" onChange={e=>updateRow(index,'trend',e.target.value)}/></td><td><input disabled={!editable} value={valueOf(row.note)} placeholder="Ghi chú" onChange={e=>updateRow(index,'note',e.target.value)}/></td><td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>})}<tr className="revenue-total-row"><td colSpan="2">TỔNG</td><td>{displayNumber(totalTarget)}</td><td>{displayNumber(totalActual)}</td><td>{displayPercent(ratio(totalActual,totalTarget))}</td><td>{displayNumber(totalLead)}</td><td>{displayNumber(totalOrder)}</td><td>{displayNumber(totalRevenue)}</td><td>{displayPercent(ratio(totalOrder,totalLead))}</td><td>{displayNumber(ratio(totalRevenue,totalOrder))}</td><td>{displayPercent(ratio(totalActual,totalRevenue))}</td><td colSpan="3"/></tr></tbody></table>{!details.length&&<div className="no-rows compact">Chưa có nguồn traffic. Chọn “Thêm dòng” để bắt đầu.</div>}</div>;
}

function AdsProductTable({rows,editable,masterData,updateRow,removeRow}){
  const totalCost=rows.reduce((sum,row)=>sum+(Number(row.ad_cost)||0),0),totalRevenue=rows.reduce((sum,row)=>sum+(Number(row.revenue)||0),0);
  return <div className="detail-entry-table ads-product-table"><table><thead><tr><th>#</th><th>Nhóm sản phẩm</th><th>Sản phẩm</th><th>Chi phí Ads</th><th>Tỷ trọng Ads</th><th>Doanh thu</th><th>Tỷ trọng DT</th><th>Ghi chú</th><th/></tr></thead><tbody>{rows.map((row,index)=>{const cost=Number(row.ad_cost)||0,revenue=Number(row.revenue)||0;return <tr key={row.row_key||row.id||index}><td>{index+1}</td><td><select disabled={!editable} value={valueOf(row.product_group)} onChange={e=>updateRow(index,'product_group',e.target.value)}><option value="">Chọn nhóm</option>{(masterData.product_group||[]).map(x=><option key={x.code} value={x.label}>{x.label}</option>)}</select></td><td><input disabled={!editable} value={valueOf(row.product_name)} placeholder="Tên sản phẩm" onChange={e=>updateRow(index,'product_name',e.target.value)}/></td><td><input disabled={!editable} type="number" value={valueOf(row.ad_cost)} onChange={e=>updateRow(index,'ad_cost',e.target.value===''?null:Number(e.target.value))}/></td><td className="formula-cell">{displayPercent(totalCost?cost/totalCost:null)}</td><td><input disabled={!editable} type="number" value={valueOf(row.revenue)} onChange={e=>updateRow(index,'revenue',e.target.value===''?null:Number(e.target.value))}/></td><td className="formula-cell">{displayPercent(totalRevenue?revenue/totalRevenue:null)}</td><td><input disabled={!editable} value={valueOf(row.note)} placeholder="Ghi chú" onChange={e=>updateRow(index,'note',e.target.value)}/></td><td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>})}<tr className="revenue-total-row"><td colSpan="3">TỔNG</td><td>{displayNumber(totalCost)}</td><td>{displayPercent(totalCost?1:null)}</td><td>{displayNumber(totalRevenue)}</td><td>{displayPercent(totalRevenue?1:null)}</td><td colSpan="2"/></tr></tbody></table>{!rows.length&&<div className="no-rows compact">Chưa có sản phẩm. Chọn “Thêm dòng” để bắt đầu.</div>}</div>;
}

export default function ManualReportPage({currentUser,showMsg}){
  const navigate=useNavigate();const {periodId,teamCode}=useParams();const team=(teamCode||'REV').toUpperCase();const canEdit=currentUser?.permissions?.includes('reports.upload');const canManage=currentUser?.permissions?.includes('reports.manage');
  const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [deadline,setDeadline]=useState('');const [bootstrap,setBootstrap]=useState({teams:[],masterData:{}});
  const [period,setPeriod]=useState(null);const [workspace,setWorkspace]=useState(null);const [kpis,setKpis]=useState([]);const [details,setDetails]=useState([]);const [adsProducts,setAdsProducts]=useState([]);const [note,setNote]=useState(emptyNote);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false);const saveTimer=useRef(null);const loadedRef=useRef(false);const showMsgRef=useRef(showMsg);

  useEffect(()=>{showMsgRef.current=showMsg;},[showMsg]);
  useEffect(()=>{api.get('/reports/bootstrap').then(r=>setBootstrap(r.data.data)).catch(()=>showMsgRef.current('Không thể tải master báo cáo.','error'));},[]);
  const findPeriod=useCallback(async()=>{setLoading(true);setWorkspace(null);try{const r=periodId?await api.get(`/reports/manual/periods/${periodId}`):await api.get('/reports/manual/periods/find',{params:{year,month}});const data=r.data.data;setPeriod(data);setYear(Number(data.year));setMonth(Number(data.month));const selected=data.submissions?.find(s=>s.teamCode===team)||data.submissions?.[0];if(selected&&selected.teamCode!==team)navigate(`/reports/manage/${data.id}/${selected.teamCode}`,{replace:true});else if(selected&&!teamCode)navigate(`/reports/manage/${data.id}/${selected.teamCode}`,{replace:true});}catch(error){if(error.response?.status===404)setPeriod(null);else showMsgRef.current(error.response?.data?.error||'Không thể tải kỳ báo cáo.','error');}finally{setLoading(false);}},[periodId,year,month,team,teamCode,navigate]);
  useEffect(()=>{findPeriod();},[periodId,teamCode]); // eslint-disable-line react-hooks/exhaustive-deps
  const loadWorkspace=useCallback(async()=>{if(!period?.id)return;setLoading(true);loadedRef.current=false;try{const r=await api.get(`/reports/manual/periods/${period.id}/teams/${team}`);const data=r.data.data;setWorkspace(data);setKpis(data.kpis||[]);setDetails(data.details||[]);setAdsProducts(data.adsProducts||[]);setNote({...emptyNote,...data.note});setDirty(false);setTimeout(()=>{loadedRef.current=true;},0);}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể tải phiếu nhập liệu.','error');}finally{setLoading(false);}},[period?.id,team]);
  useEffect(()=>{loadWorkspace();},[loadWorkspace]);

  const createPeriod=async()=>{setSaving(true);try{await api.post('/reports/manual/periods',{year,month,deadline:deadline||null,copyTargets:true});showMsgRef.current(`Đã tạo kỳ tháng ${month}/${year}.`);await findPeriod();}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể tạo kỳ.','error');}finally{setSaving(false);}};
  const editable=canEdit&&['draft','editing','returned'].includes(workspace?.submission_status);
  const markDirty=()=>{if(loadedRef.current)setDirty(true);};
  const save=useCallback(async(silent=false)=>{if(!workspace||!editable||saving)return null;const incompleteDynamicKpi=kpis.some(kpi=>!String(kpi.code||'').trim()||!String(kpi.name||'').trim()||!String(kpi.unit||'').trim()||!String(kpi.evaluation_direction||'').trim());if(incompleteDynamicKpi){if(!silent)showMsgRef.current('Vui lòng nhập đủ mã KPI, tên chỉ số, đơn vị và chiều đánh giá.','error');return null;}setSaving(true);try{const r=await api.put(`/reports/manual/periods/${period.id}/teams/${team}`,{kpis,details,adsProducts,note});const data=r.data.data;setWorkspace(data);setKpis(data.kpis||[]);setDetails(data.details||[]);setAdsProducts(data.adsProducts||[]);setNote({...emptyNote,...data.note});setDirty(false);if(!silent)showMsgRef.current('Đã lưu dữ liệu báo cáo.');return data;}catch(error){if(!silent)showMsgRef.current(error.response?.data?.error||'Không thể lưu dữ liệu.','error');return null;}finally{setSaving(false);}},[workspace,editable,saving,period?.id,team,kpis,details,adsProducts,note]);
  useEffect(()=>{if(!dirty||!editable)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>save(true),1500);return()=>clearTimeout(saveTimer.current);},[dirty,editable,save]);
  const updateKpi=(index,key,value)=>{setKpis(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));markDirty();};
  const updateRow=(index,key,value)=>{setDetails(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));markDirty();};
  const updateAdsProduct=(index,key,value)=>{setAdsProducts(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));markDirty();};
  const addRow=()=>{setDetails(items=>[...items,{row_key:crypto.randomUUID()}]);markDirty();};
  const addAdsProduct=()=>{setAdsProducts(items=>[...items,{row_key:crypto.randomUUID()}]);markDirty();};
  const removeRow=index=>{setDetails(items=>items.filter((_,i)=>i!==index));markDirty();};
  const removeAdsProduct=index=>{setAdsProducts(items=>items.filter((_,i)=>i!==index));markDirty();};
  const updateNote=(key,value)=>{setNote(item=>({...item,[key]:value}));markDirty();};
  const transition=async(action)=>{if(action==='submit'){const saved=await save(true);if(!saved)return;}try{await api.post(`/reports/manual/periods/${period.id}/teams/${team}/workflow`,{action});showMsgRef.current(action==='submit'?'Đã gửi bộ phận duyệt.':action==='approve'?'Đã duyệt bộ phận.':'Đã trả lại phiếu nhập liệu.');await findPeriod();await loadWorkspace();}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể cập nhật trạng thái.','error');}};
  const publish=async()=>{try{await api.post(`/reports/manual/periods/${period.id}/publish`);showMsgRef.current('Đã publish dữ liệu lên dashboard.');navigate('/reports/manage');}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể publish báo cáo.','error');}};
  const reopen=async()=>{if(!window.confirm(`Thu hồi báo cáo tháng ${month}/${year} để cập nhật? Dashboard vẫn dùng bản hiện tại cho đến khi publish lại.`))return;setSaving(true);try{await api.post(`/reports/manual/periods/${period.id}/reopen`);showMsgRef.current('Đã mở phiên chỉnh sửa mới từ bản đã publish.');await findPeriod();}catch(error){showMsgRef.current(error.response?.data?.error||'Không thể thu hồi báo cáo.','error');}finally{setSaving(false);}};
  const validation=workspace?.validation_result||{errors:[],warnings:[]};
  const approvedCount=useMemo(()=>period?.submissions?.filter(s=>s.status==='approved').length||0,[period]);
  const progress=useMemo(()=>{const total=period?.submissions?.length||0;return total?Math.round(approvedCount/total*100):0;},[period,approvedCount]);
  const dynamicKpi=true;

  return <div className="manual-report-page">
    <header className="manual-header"><div><button className="back" onClick={()=>navigate('/reports/manage')} title="Quay lại danh sách kỳ"><ArrowLeft/></button><div><span>PHIẾU BÁO CÁO · {workspace?.team_code||team}</span><h1>{workspace?.team_name||'Chi tiết phiếu báo cáo'}</h1><p>Kỳ tháng {month}/{year} · Hoàn thiện dữ liệu, kiểm tra và gửi duyệt.</p></div></div>{period&&<div className="period-progress"><div><span>TIẾN ĐỘ TOÀN KỲ</span><strong>{approvedCount}/{period.submissions?.length||6} bộ phận</strong></div><i><b style={{width:`${progress}%`}}/></i>{canManage&&period.version_status==='draft'&&<button onClick={publish} disabled={progress<100}>Publish dashboard</button>}</div>}</header>
    <section className="manual-period-bar"><div><strong>Kỳ tháng {month}/{year}</strong><span className={`period-state ${period?.status||''}`}>{PERIOD_STATUS[period?.status]||period?.status||'—'}</span></div><div>{period?.status==='published'&&canManage?<button className="reopen-period" onClick={reopen} disabled={saving}><RotateCcw/>Thu hồi để cập nhật</button>:<span>Cập nhật dữ liệu và tiến độ mới nhất</span>}<button onClick={findPeriod}><RefreshCw/>Làm mới</button></div></section>
    {loading&&!workspace?<div className="manual-empty"><RefreshCw className="spin"/>Đang tải dữ liệu…</div>:!period?<section className="create-period-card"><span>01</span><h2>Chưa tạo kỳ báo cáo</h2><p>Tạo kỳ sẽ sinh phiếu nhập liệu và danh sách KPI cho toàn bộ sáu bộ phận.</p>{canManage?<div><label>Hạn nhập liệu<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button onClick={createPeriod} disabled={saving}><Plus/>Tạo kỳ tháng {month}/{year}</button></div>:<small>Liên hệ quản trị báo cáo để tạo kỳ.</small>}</section>:<div className="manual-layout">
      {workspace&&<main className="entry-workspace">{period?.status==='published'&&<section className="published-readonly"><Eye/><div><b>Đang xem dữ liệu đã publish</b><span>Phiếu được khóa chỉnh sửa. Chọn “Thu hồi để cập nhật” để tạo phiên bản mới.</span></div></section>}<section className="workspace-title"><div><div className="workspace-code">{workspace.team_code}</div><div><h2>{workspace.team_name}</h2><p>Phiên bản {workspace.version_no}<span className={`submission-state ${workspace.submission_status}`}>{STATUS[workspace.submission_status]}</span></p></div></div><div><span className={`save-state ${saving?'saving':dirty?'dirty':'saved'}`}>{saving?'Đang lưu…':dirty?'Có thay đổi chưa lưu':period?.status==='published'?'Chỉ xem':'Đã đồng bộ'}</span><button className="save-draft" onClick={()=>save(false)} disabled={!editable||saving}><Save/>Lưu nháp</button></div></section>
        {(validation.errors?.length>0||validation.warnings?.length>0)&&<section className="validation-panel"><AlertCircle/><div>{validation.errors?.map(x=><p className="error" key={x}>{x}</p>)}{validation.warnings?.map(x=><p key={x}>{x}</p>)}</div></section>}
        <section className="entry-section kpi-section"><header><div><span>01 · KPI TỔNG HỢP</span><h3>Kế hoạch và kết quả</h3></div><div className="kpi-legend"><span><i/>Bộ KPI theo cấu hình kỳ</span><span><i/>Không được thêm hoặc xóa tại phiếu</span></div></header><div className="kpi-entry-table revenue-kpi-table"><table><thead><tr><th>Mã KPI</th><th>Chỉ số KPI</th><th>Đơn vị</th><th>Chiều đánh giá</th><th>Kế hoạch</th><th>Thực hiện</th><th>% HT KH</th><th>Tháng trước</th><th>% vs TTr</th><th>Cùng kỳ</th><th>% vs CK</th><th>Đánh giá</th><th>Ghi chú</th></tr></thead><tbody>{kpis.map((kpi,index)=><tr key={kpi.code} className={kpi.input_mode==='derived'?'derived-row':'manual-row'}><td><code className="locked-kpi-code">{kpi.code}</code></td><td><strong className="locked-kpi-name">{kpi.name}</strong></td><td><span className="unit-pill">{kpi.unit}</span></td><td><span className="direction-pill">{DIRECTION_OPTIONS.find(item=>item[0]===kpi.evaluation_direction)?.[1]||'Theo dõi'}</span></td><td><input aria-label={`Kế hoạch ${kpi.name}`} disabled={!editable} type="number" step="any" placeholder="Kế hoạch" value={valueOf(kpi.target_value)} onChange={e=>updateKpi(index,'target_value',e.target.value===''?null:Number(e.target.value))}/></td><td>{kpi.input_mode==='derived'?<div className="derived-value"><span>{displayNumber(kpi.actual_value)}</span><em>Tự tính từ chi tiết</em></div>:<input aria-label={`Thực hiện ${kpi.name}`} disabled={!editable} type="number" step="any" placeholder="Thực hiện" value={valueOf(kpi.actual_value)} onChange={e=>updateKpi(index,'actual_value',e.target.value===''?null:Number(e.target.value))}/>}</td><td className="formula-cell">{displayPercent(kpi.achievement_rate??(kpi.target_value?Number(kpi.actual_value)/Number(kpi.target_value):null))}</td><td><strong className="previous-value">{displayNumber(kpi.previous_value)}</strong></td><td className="formula-cell">{displayPercent(kpi.previous_change)}</td><td>{displayNumber(kpi.prior_year_value)}</td><td className="formula-cell">{displayPercent(kpi.prior_year_change)}</td><td><span className={`evaluation-badge ${(kpi.evaluation||'').toLowerCase().replaceAll(' ','-')}`}>{kpi.evaluation||'—'}</span></td><td><input aria-label={`Ghi chú ${kpi.name}`} disabled={!editable} placeholder="Ghi chú…" value={valueOf(kpi.note)} onChange={e=>updateKpi(index,'note',e.target.value)}/></td></tr>)}</tbody></table></div></section>
        <section className="entry-section"><header><div><span>02 · DỮ LIỆU CHI TIẾT</span><h3>{workspace.config.title}</h3></div><button onClick={addRow} disabled={!editable}><Plus/>Thêm dòng</button></header><div className="entry-guide">{workspace.config.instructions.map(item=><p key={item}><Check/>{item}</p>)}</div>{team==='REV'?<RevenueDetailTable details={details} editable={editable} masterData={bootstrap.masterData||{}} updateRow={updateRow} removeRow={removeRow}/>:team==='ADS'?<AdsTrafficTable details={details} editable={editable} masterData={bootstrap.masterData||{}} updateRow={updateRow} removeRow={removeRow}/>:<div className="detail-entry-table"><table><thead><tr><th>#</th>{workspace.config.fields.map(field=><th key={field.key}>{field.label}{field.required&&<b>*</b>}</th>)}<th/></tr></thead><tbody>{details.map((row,index)=><tr key={row.row_key||row.id||index}><td>{index+1}</td>{workspace.config.fields.map(field=><td key={field.key}><FieldInput field={field} value={row[field.key]} onChange={value=>updateRow(index,field.key,value)} lookups={bootstrap.masterData||{}} disabled={!editable}/></td>)}<td><button className="delete-row" onClick={()=>removeRow(index)} disabled={!editable}><Trash2/></button></td></tr>)}</tbody></table>{!details.length&&<div className="no-rows compact">Chưa có dữ liệu. Chọn “Thêm dòng” để bắt đầu.</div>}</div>}</section>
        {team==='ADS'&&<section className="entry-section"><header><div><span>03 · PHÂN BỔ NGÂN SÁCH</span><h3>Tỷ trọng Ads theo sản phẩm</h3></div><button onClick={addAdsProduct} disabled={!editable}><Plus/>Thêm dòng</button></header><div className="entry-guide"><p><Check/>Chi phí Ads và doanh thu được tổng hợp theo từng sản phẩm.</p><p><Check/>Tỷ trọng được hệ thống tự tính trên tổng dữ liệu đã nhập.</p></div><AdsProductTable rows={adsProducts} editable={editable} masterData={bootstrap.masterData||{}} updateRow={updateAdsProduct} removeRow={removeAdsProduct}/></section>}
        <section className={`entry-section notes-entry ${dynamicKpi?'revenue-notes':''}`}><header><div><span>{team==='ADS'?'04':'03'} · NHẬN XÉT</span><h3>Nhận xét và đề xuất điều hành</h3></div><small>Thông tin phục vụ tổng hợp và điều hành kỳ báo cáo</small></header><div>{(dynamicKpi?[['highlights','Điểm nổi bật','Kết quả tích cực, cột mốc hoặc thay đổi đáng chú ý'],['issues','Nguyên nhân / vấn đề','Nguyên nhân ảnh hưởng đến kết quả thực hiện'],['risks','Rủi ro / vướng mắc','Rủi ro hiện tại và vấn đề cần hỗ trợ'],['proposals','Đề xuất / kế hoạch tháng tới','Hành động, người phụ trách và kế hoạch tiếp theo']]:[['highlights','Điểm nổi bật','Kết quả tích cực và thay đổi đáng chú ý'],['issues','Nguyên nhân / vấn đề','Nguyên nhân ảnh hưởng đến kết quả'],['risks','Rủi ro / vướng mắc','Rủi ro và vấn đề cần hỗ trợ'],['proposals','Đề xuất','Giải pháp và đề xuất điều hành'],['next_month_plan','Kế hoạch tháng tới','Hành động ưu tiên trong kỳ tiếp theo']]).map(([key,label,hint])=><label key={key}><span>{label}</span><small>{hint}</small><textarea disabled={!editable} placeholder={`Nhập ${label.toLowerCase()}…`} value={note[key]||''} onChange={e=>updateNote(key,e.target.value)}/><em>{(note[key]||'').length} ký tự</em></label>)}</div></section>
        <footer className="workflow-actions"><div><span className={`autosave-dot ${saving?'saving':dirty?'dirty':'saved'}`}/><span>{saving?'Đang tự động lưu…':dirty?'Đang chờ tự động lưu':'Mọi thay đổi đã được lưu'}</span></div><div>{workspace.submission_status==='submitted'&&canManage&&<><button className="return" onClick={()=>transition('return')}>Trả lại</button><button className="approve" onClick={()=>transition('approve')}><Check/>Duyệt bộ phận</button></>}{['editing','returned'].includes(workspace.submission_status)&&canEdit&&<button className="submit" onClick={()=>transition('submit')}><Send/>Gửi duyệt</button>}</div></footer>
      </main>}
    </div>}
  </div>;
}
