import {Fragment,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {CalendarDays,ChevronDown,ChevronRight,Clock3,Eye,FilePlus2,LayoutDashboard,Plus,RefreshCw,RotateCcw,Send,Trash2,UserRound,X} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import api from '../../../services/api';
import {useDialog} from '../../../components/feedback/dialogContext';
import './ReportPeriodManagementPage.css';

const now=new Date();
const STATUS={draft:'Bản nháp',open:'Chưa nhập',in_progress:'Đang nhập',submitted:'Chờ duyệt',approved:'Đã duyệt',published:'Đã publish',locked:'Đã khóa',reopened:'Mở lại'};
const SUBMISSION_STATUS={draft:'Chưa nhập',editing:'Đang nhập',submitted:'Chờ duyệt',returned:'Cần chỉnh sửa',approved:'Đã duyệt'};
const formatDate=value=>value?new Date(value).toLocaleString('vi-VN'):'—';
const toDateTimeInput=value=>{if(!value)return'';const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);};

export default function ReportPeriodManagementPage({currentUser,showMsg}){
  const {confirm:confirmDialog,prompt:promptDialog}=useDialog();
  const navigate=useNavigate(),permissions=currentUser?.permissions||[],canManage=permissions.includes('reports.manage'),canAssign=canManage||permissions.includes('reports.assign'),notify=useRef(showMsg);
  const [periods,setPeriods]=useState([]),[loading,setLoading]=useState(true),[yearFilter,setYearFilter]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [expandedPeriod,setExpandedPeriod]=useState(null),[periodDetails,setPeriodDetails]=useState({}),[loadingPeriod,setLoadingPeriod]=useState(null);
  const [creating,setCreating]=useState(false),[form,setForm]=useState({year:now.getFullYear(),month:now.getMonth()+1,deadline:''}),[busy,setBusy]=useState(false);
  const [assignees,setAssignees]=useState([]),[assigning,setAssigning]=useState(''),[assignmentDialog,setAssignmentDialog]=useState(null),[deadlineDialog,setDeadlineDialog]=useState(null),[deadlineValue,setDeadlineValue]=useState('');
  useEffect(()=>{notify.current=showMsg;},[showMsg]);
  const load=useCallback(async()=>{setLoading(true);try{const r=await api.get('/reports/manual/periods',{params:{year:yearFilter||undefined,status:statusFilter||undefined}});setPeriods(r.data.data||[]);}catch(error){notify.current(error.response?.data?.error||'Không thể tải danh sách kỳ báo cáo.','error');}finally{setLoading(false);}},[yearFilter,statusFilter]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{if(canAssign)api.get('/reports/manual/assignees').then(r=>setAssignees(r.data.data||[])).catch(()=>setAssignees([]));},[canAssign]);
  const summary=useMemo(()=>({total:periods.length,active:periods.filter(p=>['open','in_progress','submitted','approved','reopened'].includes(p.status)).length,published:periods.filter(p=>p.status==='published').length,pending:periods.reduce((sum,p)=>sum+Number(p.total_teams-p.approved_teams||0),0)}),[periods]);

  const loadPeriod=async period=>{setLoadingPeriod(period.id);try{const r=await api.get(`/reports/manual/periods/${period.id}`);setPeriodDetails(items=>({...items,[period.id]:r.data.data}));return r.data.data;}catch(error){notify.current(error.response?.data?.error||'Không thể tải danh sách phiếu báo cáo.','error');}finally{setLoadingPeriod(null);}};
  const togglePeriod=async period=>{if(expandedPeriod===period.id){setExpandedPeriod(null);return;}setExpandedPeriod(period.id);if(!periodDetails[period.id])await loadPeriod(period);};
  const create=async event=>{event.preventDefault();setBusy(true);try{const r=await api.post('/reports/manual/periods',{...form,deadline:form.deadline||null,copyTargets:true});const id=r.data.data.periodId;notify.current(`Đã tạo kỳ tháng ${form.month}/${form.year}.`);setCreating(false);await load();setExpandedPeriod(id);await loadPeriod({id});}catch(error){notify.current(error.response?.data?.error||'Không thể tạo kỳ báo cáo.','error');}finally{setBusy(false);}};
  const initialize=async period=>{setBusy(true);try{const r=await api.post('/reports/manual/periods',{year:period.year,month:period.month,deadline:period.submission_deadline||null,copyTargets:true});notify.current('Đã sinh sáu phiếu nhập liệu.');await load();navigate(`/reports/manage/${r.data.data.periodId}/REV`);}catch(error){notify.current(error.response?.data?.error||'Không thể sinh phiếu nhập liệu.','error');}finally{setBusy(false);}};
  const publish=async period=>{if(!await confirmDialog({title:'Publish báo cáo?',message:`Báo cáo tháng ${period.month}/${period.year} sẽ được publish lên dashboard.`,confirmText:'Publish',tone:'primary'}))return;setBusy(true);try{await api.post(`/reports/manual/periods/${period.id}/publish`);notify.current('Đã publish kỳ báo cáo.');await load();}catch(error){notify.current(error.response?.data?.error||'Không thể publish kỳ báo cáo.','error');}finally{setBusy(false);}};
  const reopen=async period=>{const reason=await promptDialog({title:'Thu hồi báo cáo',message:`Nhập lý do thu hồi báo cáo tháng ${period.month}/${period.year}.`,label:'Lý do thu hồi',required:true,confirmText:'Thu hồi báo cáo'});if(reason===null)return;setBusy(true);try{const r=await api.post(`/reports/manual/periods/${period.id}/reopen`,{reason});notify.current('Đã tạo phiên chỉnh sửa mới.');await load();navigate(`/reports/manage/${period.id}/REV`,{state:{versionId:r.data.data.versionId}});}catch(error){notify.current(error.response?.data?.error||'Không thể thu hồi báo cáo.','error');}finally{setBusy(false);}};
  const remove=async period=>{if(!await confirmDialog({title:'Xóa kỳ báo cáo?',message:`Kỳ tháng ${period.month}/${period.year} và toàn bộ dữ liệu nhập sẽ bị xóa. Thao tác này không thể hoàn tác.`,confirmText:'Xóa kỳ báo cáo'}))return;setBusy(true);try{await api.delete(`/reports/manual/periods/${period.id}`);notify.current('Đã xóa kỳ báo cáo.');await load();}catch(error){notify.current(error.response?.data?.error||'Không thể xóa kỳ báo cáo.','error');}finally{setBusy(false);}};
  const assign=async userId=>{const {period,item}=assignmentDialog,key=`${period.id}:${item.teamCode}`;setAssigning(key);try{const r=await api.patch(`/reports/manual/periods/${period.id}/teams/${item.teamCode}/assignee`,{userId:userId||null});setPeriodDetails(current=>({...current,[period.id]:r.data.data}));notify.current(userId?'Đã phân công người thực hiện.':'Đã bỏ phân công.');setAssignmentDialog(null);}catch(error){notify.current(error.response?.data?.error||'Không thể cập nhật người thực hiện.','error');}finally{setAssigning('');}};
  const updateDeadline=async()=>{setBusy(true);try{await api.patch(`/reports/manual/periods/${deadlineDialog.id}/deadline`,{deadline:deadlineValue||null});notify.current(deadlineValue?'Đã cập nhật hạn nhập liệu.':'Đã bỏ hạn nhập liệu.');setDeadlineDialog(null);await load();if(periodDetails[deadlineDialog.id])await loadPeriod(deadlineDialog);}catch(error){notify.current(error.response?.data?.error||'Không thể cập nhật hạn nhập liệu.','error');}finally{setBusy(false);}};

  return <div className="period-management-page">
    <header className="period-page-header"><div><span>QUẢN LÝ BÁO CÁO</span><h1>Danh sách kỳ báo cáo</h1><p>Tạo kỳ, theo dõi phiếu nhập liệu và publish kết quả lên dashboard.</p></div><div><button onClick={()=>navigate('/reports/kpi')}><LayoutDashboard/>Dashboard</button>{canManage&&<button className="primary" onClick={()=>setCreating(true)}><Plus/>Tạo kỳ</button>}</div></header>
    <section className="period-summary"><article><CalendarDays/><div><b>{summary.total}</b><span>Tổng số kỳ</span></div></article><article><RefreshCw/><div><b>{summary.active}</b><span>Đang thực hiện</span></div></article><article><Send/><div><b>{summary.published}</b><span>Đã publish</span></div></article><article><FilePlus2/><div><b>{summary.pending}</b><span>Phiếu chưa duyệt</span></div></article></section>
    <section className="period-list-card"><header><div><h2>Các kỳ báo cáo</h2><p>{periods.length} kỳ phù hợp bộ lọc</p></div><div className="period-filters"><select value={yearFilter} onChange={e=>setYearFilter(e.target.value)}><option value="">Tất cả năm</option>{Array.from({length:7},(_,i)=>now.getFullYear()+2-i).map(y=><option key={y}>{y}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button onClick={load}><RefreshCw/>Làm mới</button></div></header>
      <div className="period-table-wrap"><table><thead><tr><th>Kỳ báo cáo</th><th>Trạng thái</th><th>Tiến độ</th><th>Hạn nhập liệu</th><th>Cập nhật</th><th>Thao tác</th></tr></thead><tbody>{periods.map(period=>{const publishedLegacy=period.status==='published'&&!period.total_teams,total=period.total_teams||6,approved=publishedLegacy?6:period.approved_teams,progress=total?Math.round(approved/total*100):0,expanded=expandedPeriod===period.id,detail=periodDetails[period.id];return <Fragment key={period.id}><tr className={expanded?'expanded':''}><td><div className="period-name"><i>T{period.month}</i><div><b>Tháng {period.month}/{period.year}</b><span>Phiên bản {period.version_no||'—'} · Nhập trực tiếp</span></div></div></td><td><span className={`period-status ${period.status}`}>{STATUS[period.status]||period.status}</span></td><td><div className="period-progress-cell"><div><span>{approved}/{total} đã duyệt</span><b>{progress}%</b></div><i><em style={{width:`${progress}%`}}/></i></div></td><td>{formatDate(period.submission_deadline)}</td><td>{formatDate(period.updated_at)}</td><td><div className="period-actions">{period.total_teams>0||period.status==='published'?<button className="submission-toggle" aria-expanded={expanded} onClick={()=>togglePeriod(period)}><Eye/>Phiếu<ChevronDown/></button>:canManage&&<button className="initialize" onClick={()=>initialize(period)}><FilePlus2/>Tạo phiếu</button>}{canManage&&!['published','locked'].includes(period.status)&&<button className="deadline-action" title="Đặt hạn nhập liệu" onClick={()=>{setDeadlineValue(toDateTimeInput(period.submission_deadline));setDeadlineDialog(period);}}><Clock3/></button>}{canManage&&period.status==='published'&&<button className="reopen" onClick={()=>reopen(period)}><RotateCcw/>Thu hồi</button>}{canManage&&period.version_status==='draft'&&period.total_teams>0&&period.approved_teams===period.total_teams&&<button className="publish" onClick={()=>publish(period)}><Send/>Publish</button>}{canManage&&!['published','locked'].includes(period.status)&&<button className="delete" onClick={()=>remove(period)}><Trash2/></button>}</div></td></tr>
        {expanded&&<tr className="submission-detail-row"><td colSpan="6"><div className="period-submission-panel"><header><div><b>Phiếu báo cáo theo bộ phận</b><span>Trạng thái, người phụ trách và thao tác trên từng phiếu</span></div><strong>{detail?.submissions?.length||total} phiếu</strong></header>{loadingPeriod===period.id?<div className="submission-panel-loading"><RefreshCw className="spin"/>Đang tải…</div>:<div className="period-submission-list"><div className="submission-list-head"><span>Bộ phận</span><span>Trạng thái</span><span>Người phụ trách</span><span>Kiểm tra</span><span>Thao tác</span></div>{(detail?.submissions||[]).map((item,index)=>{const assignee=item.assigneeName||item.assignedUserName;return <div className="submission-list-row" key={item.teamCode}><div className="submission-team"><span className="submission-number">{String(index+1).padStart(2,'0')}</span><div><b>{item.teamName}</b><small>{item.teamCode}</small></div></div><span className={`submission-status ${item.status}`}><i/>{SUBMISSION_STATUS[item.status]||item.status}</span><span className={`submission-assignee ${assignee?'assigned':''}`}><UserRound/>{assignee||'Chưa phân công'}</span><span className={`submission-validation ${item.errors?'has-error':'valid'}`}>{item.errors?`${item.errors} lỗi`:'Hợp lệ'}</span><div className="submission-row-actions">{canAssign&&detail?.version_status==='draft'&&<button className="assign-submission" title="Phân công" onClick={()=>setAssignmentDialog({period,item})}><UserRound/></button>}<button className="open-submission" onClick={()=>navigate(`/reports/manage/${period.id}/${item.teamCode}`)}>Chi tiết<ChevronRight/></button></div></div>})}</div>}</div></td></tr>}</Fragment>;})}</tbody></table>{!loading&&!periods.length&&<div className="period-empty"><CalendarDays/><h3>Chưa có kỳ báo cáo</h3></div>}</div>
    </section>
    {creating&&<div className="period-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setCreating(false)}><form className="period-create-modal" onSubmit={create}><header><div><span>TẠO KỲ MỚI</span><h2>Tạo kỳ báo cáo tháng</h2></div><button type="button" onClick={()=>setCreating(false)}><X/></button></header><div className="period-form-grid"><label>Năm<select value={form.year} onChange={e=>setForm({...form,year:Number(e.target.value)})}>{Array.from({length:5},(_,i)=>now.getFullYear()-2+i).map(y=><option key={y}>{y}</option>)}</select></label><label>Tháng<select value={form.month} onChange={e=>setForm({...form,month:Number(e.target.value)})}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>Tháng {i+1}</option>)}</select></label><label className="deadline">Hạn nhập liệu<input type="datetime-local" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setCreating(false)}>Hủy</button><button className="primary" disabled={busy}><Plus/>Tạo kỳ</button></footer></form></div>}
    {assignmentDialog&&<div className="period-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setAssignmentDialog(null)}><section className="compact-action-modal"><header><div><span>PHÂN CÔNG PHIẾU</span><h2>{assignmentDialog.item.teamName}</h2><p>Tháng {assignmentDialog.period.month}/{assignmentDialog.period.year}</p></div><button onClick={()=>setAssignmentDialog(null)}><X/></button></header><label>Người thực hiện<select defaultValue={assignmentDialog.item.assignedUserId||''} disabled={Boolean(assigning)} onChange={e=>assign(e.target.value)}><option value="">Chưa phân công</option>{assignees.map(user=><option key={user.id} value={user.id}>{user.name||user.email} · {user.role_name||user.role}</option>)}</select></label><small>Người được chọn sẽ được cấp quyền truy cập phiếu này trên hệ thống.</small></section></div>}
    {deadlineDialog&&<div className="period-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDeadlineDialog(null)}><section className="compact-action-modal"><header><div><span>HẠN NHẬP LIỆU</span><h2>Tháng {deadlineDialog.month}/{deadlineDialog.year}</h2><p>Sau hạn này người nhập không thể lưu hoặc gửi duyệt.</p></div><button onClick={()=>setDeadlineDialog(null)}><X/></button></header><label>Thời hạn<input type="datetime-local" value={deadlineValue} onChange={e=>setDeadlineValue(e.target.value)}/></label><footer><button onClick={()=>{setDeadlineValue('');}}>Bỏ hạn</button><button className="primary" disabled={busy} onClick={updateDeadline}>Cập nhật</button></footer></section></div>}
  </div>;
}
