import api from './api';
export const listContentSources=params=>api.get('/content-sources',{params}).then(response=>response.data);
export const getContentSource=id=>api.get(`/content-sources/${id}`).then(response=>response.data.data);
export const deleteContentSource=id=>api.delete(`/content-sources/${id}`).then(response=>response.data.data);
export const detectContentSource=({file,files,text})=>{const form=new FormData();if(files?.length)files.forEach(item=>form.append('files',item));else if(file)form.append('file',file);else form.append('text',text);return api.post('/content-sources/detect',form,{timeout:130000}).then(response=>response.data.data);};
export const analyzeContentSource=(id,text)=>api.post(`/content-sources/${id}/analyze`,{text},{timeout:130000}).then(response=>response.data.data);
export const reviewContentAnalysis=(analysisId,label,note)=>api.patch(`/content-sources/analyses/${analysisId}/review`,{label,note}).then(response=>response.data.data);
export const listContentTrends=()=>api.get('/content-sources/trends').then(response=>response.data);
export const rebuildContentTrends=(data={})=>api.post('/content-sources/trends/rebuild',data).then(response=>response.data);
export const selectContentTrends=trendIds=>api.put('/content-sources/trends/selection',{trendIds}).then(response=>response.data);
export const getMaterialSettings=()=>api.get('/content-sources/material-settings').then(response=>response.data.data);
export const saveMaterialSettings=data=>api.put('/content-sources/material-settings',data).then(response=>response.data.data);
export const previewMaterialRules=()=>api.get('/content-sources/material-settings/preview').then(response=>response.data);
export const listMaterialBlueprints=()=>api.get('/content-sources/blueprints').then(response=>response.data);
export const createMaterialBlueprint=data=>api.post('/content-sources/blueprints',data).then(response=>response.data.data);
export const getMaterialBlueprint=id=>api.get(`/content-sources/blueprints/${id}`).then(response=>response.data.data);
export const updateMaterialBlueprint=(id,data)=>api.put(`/content-sources/blueprints/${id}`,data).then(response=>response.data.data);
export const reviewMaterialBlueprint=(id,status,note)=>api.patch(`/content-sources/blueprints/${id}/status`,{status,note}).then(response=>response.data.data);
export const listGeneratedMaterials=(blueprintId,itemId)=>api.get(`/content-sources/blueprints/${blueprintId}/items/${itemId}/materials`).then(response=>response.data);
export const generateLearningMaterial=(blueprintId,itemId)=>api.post(`/content-sources/blueprints/${blueprintId}/items/${itemId}/materials`,{},{timeout:130000}).then(response=>response.data.data);
export const updateGeneratedMaterial=(id,data)=>api.put(`/content-sources/generated-materials/${id}`,data).then(response=>response.data.data);
export const reviewGeneratedMaterial=(id,status,note)=>api.patch(`/content-sources/generated-materials/${id}/status`,{status,note}).then(response=>response.data.data);
