import api from './api';
const unwrap = request => request.then(response => response.data);
export const listExams = params => unwrap(api.get('/exams',{params}));
export const getExam = id => unwrap(api.get(`/exams/${id}`)).then(r=>r.data);
export const createExam = data => unwrap(api.post('/exams',data)).then(r=>r.data);
export const updateExam = (id,data) => unwrap(api.put(`/exams/${id}`,data)).then(r=>r.data);
export const deleteExam = id => unwrap(api.delete(`/exams/${id}`));
export const duplicateExam = id => unwrap(api.post(`/exams/${id}/duplicate`)).then(r=>r.data);
export const addExamPart = (id,data) => unwrap(api.post(`/exams/${id}/parts`,data)).then(r=>r.data);
export const updateExamPart = (id,partId,data) => unwrap(api.put(`/exams/${id}/parts/${partId}`,data)).then(r=>r.data);
export const deleteExamPart = (id,partId) => unwrap(api.delete(`/exams/${id}/parts/${partId}`)).then(r=>r.data);
export const reorderExamParts = (id,partIds) => unwrap(api.put(`/exams/${id}/parts/reorder`,{partIds})).then(r=>r.data);
export const listAvailableQuestions = (id,params) => unwrap(api.get(`/exams/${id}/available-questions`,{params}));
export const addExamQuestions = (id,partId,questionIds) => unwrap(api.post(`/exams/${id}/parts/${partId}/questions`,{questionIds})).then(r=>r.data);
export const deleteExamQuestion = (id,partId,questionId) => unwrap(api.delete(`/exams/${id}/parts/${partId}/questions/${questionId}`)).then(r=>r.data);
export const reorderExamQuestions = (id,partId,questionIds) => unwrap(api.put(`/exams/${id}/parts/${partId}/questions/reorder`,{questionIds})).then(r=>r.data);
export const validateExam = id => unwrap(api.get(`/exams/${id}/validation`)).then(r=>r.data);
export const activateExam = id => unwrap(api.post(`/exams/${id}/activate`)).then(r=>r.data);
export const deactivateExam = id => unwrap(api.post(`/exams/${id}/deactivate`)).then(r=>r.data);
