import api from './api';
const unwrap = request => request.then(response => response.data);
export const listExams = params => unwrap(api.get('/exams',{params}));
export const getExam = id => unwrap(api.get(`/exams/${id}`)).then(r=>r.data);
export const createExam = data => unwrap(api.post('/exams',data)).then(r=>r.data);
export const updateExam = (id,data) => unwrap(api.put(`/exams/${id}`,data)).then(r=>r.data);
export const deleteExam = id => unwrap(api.delete(`/exams/${id}`));
export const duplicateExam = id => unwrap(api.post(`/exams/${id}/duplicate`)).then(r=>r.data);
export const createExamSection = (id,data) => unwrap(api.post(`/exams/${id}/sections`,data)).then(r=>r.data);
export const updateExamSection = (id,sectionId,data) => unwrap(api.put(`/exams/${id}/sections/${sectionId}`,data)).then(r=>r.data);
export const deleteExamSection = (id,sectionId) => unwrap(api.delete(`/exams/${id}/sections/${sectionId}`)).then(r=>r.data);
export const reorderExamSections = (id,sectionIds) => unwrap(api.put(`/exams/${id}/sections/reorder`,{sectionIds})).then(r=>r.data);
export const createExamPart = (id,sectionId,data) => unwrap(api.post(`/exams/${id}/sections/${sectionId}/parts`,data)).then(r=>r.data);
export const updateExamPartContent = (id,sectionId,partId,data) => unwrap(api.put(`/exams/${id}/sections/${sectionId}/parts/${partId}`,data)).then(r=>r.data);
export const deleteExamSectionPart = (id,sectionId,partId) => unwrap(api.delete(`/exams/${id}/sections/${sectionId}/parts/${partId}`)).then(r=>r.data);
export const reorderExamSectionParts = (id,sectionId,partIds) => unwrap(api.put(`/exams/${id}/sections/${sectionId}/parts/reorder`,{partIds})).then(r=>r.data);
export const deleteExamPartInstructionAudio = (id,sectionId,partId) => unwrap(api.delete(`/exams/${id}/sections/${sectionId}/parts/${partId}/instruction-audio`)).then(r=>r.data);
export const addExamPart = (id,data) => unwrap(api.post(`/exams/${id}/parts`,data)).then(r=>r.data);
export const updateExamPart = (id,partId,data) => unwrap(api.put(`/exams/${id}/parts/${partId}`,data)).then(r=>r.data);
export const deleteExamPart = (id,partId) => unwrap(api.delete(`/exams/${id}/parts/${partId}`)).then(r=>r.data);
export const reorderExamParts = (id,partIds) => unwrap(api.put(`/exams/${id}/parts/reorder`,{partIds})).then(r=>r.data);
export const listAvailableQuestions = (id,partId,params) => unwrap(api.get(`/exams/${id}/parts/${partId}/available-questions`,{params}));
export const addExamQuestions = (id,sectionId,partId,questionIds) => unwrap(api.post(`/exams/${id}/sections/${sectionId}/parts/${partId}/questions`,{questionIds})).then(r=>r.data);
export const deleteExamQuestion = (id,sectionId,partId,questionId) => unwrap(api.delete(`/exams/${id}/sections/${sectionId}/parts/${partId}/questions/${questionId}`)).then(r=>r.data);
export const reorderExamQuestions = (id,sectionId,partId,questionIds) => unwrap(api.put(`/exams/${id}/sections/${sectionId}/parts/${partId}/questions/reorder`,{questionIds})).then(r=>r.data);
export const validateExam = id => unwrap(api.get(`/exams/${id}/validation`)).then(r=>r.data);
export const activateExam = id => unwrap(api.post(`/exams/${id}/activate`)).then(r=>r.data);
export const deactivateExam = id => unwrap(api.post(`/exams/${id}/deactivate`)).then(r=>r.data);
