import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,BookOpenCheck,CheckCircle2,FileSearch,Lightbulb,RefreshCw,ShieldAlert} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import {getContentSource,reviewContentAnalysis} from '../../../services/contentSourceService';
import './ContentSourceDetailPage.css';

const list=value=>Array.isArray(value)?value:[];
const label={HIGH:'Cao',MEDIUM:'Trung bình',LOW:'Thấp',SINGLE_ITEM:'Một câu',QUESTION_GROUP:'Nhóm câu',PARTIAL_SECTION:'Một phần',FULL_SECTION:'Đủ một kỹ năng',FULL_SKILL_TEST:'Đề đủ một kỹ năng',MULTI_SKILL:'Nhiều kỹ năng',FULL_SW_TEST:'Đủ 19 câu S&W',FULL_TOEIC_TEST:'Đề TOEIC 4 kỹ năng',FULL_EXAM:'Đầy đủ'};
const insightTypeLabel={TESTED_ABILITY:'Năng lực được kiểm tra',TASK_DEMAND:'Yêu cầu nhiệm vụ',DIFFICULTY:'Điểm khó',LEARNING_IMPLICATION:'Hàm ý luyện tập',CONTENT_PATTERN:'Đặc điểm nội dung'};
const materialTypeLabel={SKILL_DRILL:'Bài luyện kỹ năng',SAMPLE_ANSWER:'Bài mẫu',STRATEGY_LESSON:'Bài chiến lược',VOCABULARY_PACK:'Bộ từ vựng',ERROR_DRILL:'Bài sửa lỗi',MINI_TEST:'Mini test',FULL_MOCK_TEST:'Đề thi thử',ANSWER_KEY:'Đáp án',SELF_REVIEW_RUBRIC:'Rubric tự đánh giá'};

function normalize(source){
  const latest=source?.latestAnalysis,data=latest?.analysis||{},v2=data.schemaVersion==='source-analysis-v2'||latest?.schemaVersion==='source-analysis-v2';
  if(v2)return {latest,data,legacy:false,summary:data.sourceSummary||{},context:data.examContext||{},coverage:data.coverage||{},recalls:list(data.recalledItems),insights:list(data.sourceInsights),needs:list(data.learningNeeds),blocked:list(data.notRecommended),uncertainties:list(data.uncertainties)};
  const recalls=list(data.recalledItems).map((item,index)=>({id:`RC-${String(index+1).padStart(3,'0')}`,skill:item.skill,questionNumbers:String(item.questionNumbers||'').split(/\s*[,–-]\s*/).filter(Boolean),taskType:item.taskType,topic:item.topic,recalledContent:item.promptRecall,candidateResponse:item.candidateResponse,evidence:item.evidence?[{quote:item.evidence}]:[],confidence:{score:Math.round(Number(item.confidence||0)*100),level:Number(item.confidence||0)>=.7?'HIGH':Number(item.confidence||0)>=.4?'MEDIUM':'LOW',reasons:['Điểm tin cậy từ phiên bản phân tích cũ']},limitations:[]}));
  return {latest,data,legacy:true,summary:{contentType:data.classification?.contentType,exam:data.classification?.exam,skills:data.classification?.skills||[],coverageLevel:recalls.length<=1?'SINGLE_ITEM':'PARTIAL_SECTION',detailLevel:'PARTIAL'},context:data.examContext||{},coverage:{level:recalls.length<=1?'SINGLE_ITEM':'PARTIAL_SECTION',coveredGroups:recalls.map(item=>`${item.skill} ${item.questionNumbers.join('–')}`),allowedScopes:['SINGLE_ITEM','QUESTION_GROUP'],blockedScopes:['FULL_TOEIC_TEST']},recalls,insights:list(data.insights).map((item,index)=>({id:`IS-${String(index+1).padStart(3,'0')}`,basedOnRecallIds:[],type:item.type,finding:item.finding,learnerImplication:item.implication,confidenceLevel:Number(item.confidence||0)>=.7?'HIGH':'MEDIUM',confidenceReasons:[],limitations:['Kết quả cũ chưa liên kết insight với câu nhớ lại.']})),needs:list(data.materialRecommendations).map((item,index)=>({id:`LN-${String(index+1).padStart(3,'0')}`,basedOnRecallIds:[],basedOnInsightIds:[],scope:'QUESTION_GROUP',skill:item.skill,title:item.title,objective:item.reason,materialTypes:item.suggestedAssets||[],limitations:['Kết quả cũ chưa liên kết đề xuất với câu nhớ lại.']})),blocked:[],uncertainties:list(data.uncertainties)};
}

export default function ContentSourceDetailPage({showMsg}){
  const {sourceId}=useParams(),navigate=useNavigate();
  const [source,setSource]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('recalls'),[note,setNote]=useState(''),[saving,setSaving]=useState(false);
  const view=useMemo(()=>normalize(source),[source]);
  const load=useCallback(async()=>{setLoading(true);try{const data=await getContentSource(sourceId);setSource(data);setNote(data.latestAnalysis?.reviewNote||'');}catch(error){showMsg(error.response?.data?.error||'Không thể tải nguồn.','error');}finally{setLoading(false);}},[sourceId,showMsg]);
  useEffect(()=>{load();},[load]);
  const review=async reviewLabel=>{if(!view.latest)return;setSaving(true);try{const updated=await reviewContentAnalysis(view.latest.id,reviewLabel,note);setSource(current=>({...current,latestAnalysis:{...current.latestAnalysis,...updated}}));showMsg('Đã cập nhật nhãn kiểm duyệt.');}catch(error){showMsg(error.response?.data?.error||'Không thể cập nhật nhãn.','error');}finally{setSaving(false);}};
  if(loading)return <div className="source-detail-loading"><RefreshCw className="spin"/>Đang tải kết quả…</div>;
  if(!source)return <div className="source-detail-loading">Không tìm thấy nguồn.</div>;
  const title=source.detectedContent?.title||source.filename||'Nội dung đã nhập';
  if(!view.latest)return <div className="source-detail-page"><button className="source-back" onClick={()=>navigate('/content-sources')}><ArrowLeft/>Nguồn học liệu</button><section className="source-detail-empty card"><FileSearch/><h1>{title}</h1><p>Nguồn này chưa được AI phân tích. Hãy quay lại màn nhập nguồn để bắt đầu phân tích.</p><button onClick={()=>navigate('/content-sources')}>Quay lại nhập nguồn</button></section></div>;
  const active=view.latest.reviewLabel||'NEEDS_REVIEW';
  return <div className="source-detail-page">
    <button className="source-back" onClick={()=>navigate('/content-sources')}><ArrowLeft/>Nguồn học liệu</button>
    <header className="source-detail-header card"><div><span>PHÂN TÍCH NGUỒN</span><h1>{title}</h1><p>{view.summary.exam||'TOEIC'} · {list(view.summary.skills).join(', ')||'Chưa xác định kỹ năng'} · {label[view.coverage.level||view.summary.coverageLevel]||'Chưa xác định phạm vi'}</p></div><div className="source-review-status"><small>Nhãn kiểm duyệt</small><div><button className={active==='APPROVED'?'active approved':''} disabled={saving} onClick={()=>review('APPROVED')}>Đã xác nhận</button><button className={active==='NEEDS_REVIEW'?'active pending':''} disabled={saving} onClick={()=>review('NEEDS_REVIEW')}>Cần kiểm tra</button><button className={active==='REJECTED'?'active rejected':''} disabled={saving} onClick={()=>review('REJECTED')}>Không sử dụng</button></div></div></header>
    {view.legacy&&<div className="source-version-note"><ShieldAlert/>Đây là kết quả phiên bản cũ. Insight và đề xuất chưa được liên kết bắt buộc với từng câu nhớ lại.</div>}
    <section className="source-summary-grid"><SummaryCard title="Phạm vi nguồn" value={label[view.coverage.level||view.summary.coverageLevel]||'Chưa rõ'} note={`${view.recalls.length} câu/nhóm câu được ghi nhận`}/><SummaryCard title="Bằng chứng" value={`${view.latest.validationMetadata?.acceptedEvidence||0} hợp lệ`} note={`${view.latest.validationMetadata?.rejectedEvidence||0} mục đã loại`}/><SummaryCard title="Nguồn phân tích" value={(view.latest.provider||'gemini').toUpperCase()} note={view.latest.schemaVersion||'source-analysis-v1'}/></section>
    <nav className="source-detail-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Tổng quan</button><button className={tab==='recalls'?'active':''} onClick={()=>setTab('recalls')}>Câu được nhớ lại <b>{view.recalls.length}</b></button><button className={tab==='insights'?'active':''} onClick={()=>setTab('insights')}>Insight <b>{view.insights.length}</b></button><button className={tab==='needs'?'active':''} onClick={()=>setTab('needs')}>Đề xuất học liệu <b>{view.needs.length}</b></button></nav>
    <main className="source-detail-content card">
      {tab==='overview'&&<Overview view={view} source={source}/>} {tab==='recalls'&&<RecallList items={view.recalls}/>} {tab==='insights'&&<InsightList items={view.insights}/>} {tab==='needs'&&<NeedList items={view.needs} blocked={view.blocked}/>} 
    </main>
    <section className="source-review-note card"><div><strong>Ghi chú kiểm duyệt</strong><span>Ghi lại điều cần kiểm tra hoặc nội dung đã đối chiếu.</span></div><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Nhập ghi chú…"/><button disabled={saving} onClick={()=>review(active)}>{saving?<RefreshCw className="spin"/>:<CheckCircle2/>}Lưu ghi chú</button></section>
  </div>;
}

function SummaryCard({title,value,note}){return <article className="card"><small>{title}</small><strong>{value}</strong><span>{note}</span></article>}
function Empty({icon:Icon,title,note}){return <div className="source-tab-empty"><Icon/><strong>{title}</strong><span>{note}</span></div>}
function Overview({view,source}){return <div className="source-overview"><section><h2>Tóm tắt nguồn</h2><dl><div><dt>Phân loại</dt><dd>{view.summary.contentType||'OTHER'}</dd></div><div><dt>Ngày thi</dt><dd>{view.context.examDate||view.context.exam_date||'Chưa rõ'}</dd></div><div><dt>Ca thi</dt><dd>{view.context.examSession||view.context.exam_session||'Chưa rõ'}</dd></div><div><dt>Phương thức nhập</dt><dd>{source.sourceType==='text'?'Văn bản':source.sourceType==='pdf'?'PDF':'Ảnh'}</dd></div></dl></section><section><h2>Độ bao phủ</h2><div className="coverage-chips">{list(view.coverage.coveredGroups).map(item=><span key={item}>{item.replaceAll('_',' ')}</span>)}</div>{!list(view.coverage.coveredGroups).length&&<p>Chưa xác định được nhóm câu cụ thể.</p>}<h3>Thông tin chưa chắc chắn</h3>{view.uncertainties.length?<ul>{view.uncertainties.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>Không có cảnh báo bổ sung.</p>}</section></div>}
function RecallList({items}){if(!items.length)return <Empty icon={FileSearch} title="Chưa nhận diện được câu hỏi" note="Nguồn chưa có bằng chứng đủ rõ về câu hoặc nhóm câu đã thi."/>;return <div className="source-card-list">{items.map((item,index)=><details key={item.id} open={index===0}><summary><div><b>{item.id}</b><h2>{item.skill} · {item.questionNumbers?.join('–')||item.taskType||'Chưa rõ câu'}</h2><span>{item.taskType} · {item.topic||'Chưa xác định chủ đề'}</span></div><em className={`confidence ${(item.confidence?.level||'LOW').toLowerCase()}`}>{label[item.confidence?.level]||item.confidence?.level}</em></summary><div className="source-card-body"><p>{item.recalledContent||'Không có nội dung nhớ lại chi tiết.'}</p>{item.candidateResponse&&<div className="candidate-response"><strong>Phản hồi thí sinh</strong><span>{item.candidateResponse}</span></div>}<Evidence items={item.evidence}/></div></details>)}</div>}
function InsightList({items}){if(!items.length)return <Empty icon={Lightbulb} title="Chưa có insight đủ bằng chứng" note="Insight chỉ xuất hiện khi liên kết được với câu hoặc nhóm câu đã nhớ lại."/>;return <div className="source-card-list insight-list">{items.map((item,index)=><details key={item.id} open={index===0}><summary><div><b>{item.id} · {insightTypeLabel[item.type]||item.type}</b><h2>{item.finding}</h2><span>{item.basedOnRecallIds?.join(', ')}</span></div><em className={`confidence ${(item.confidenceLevel||'MEDIUM').toLowerCase()}`}>{label[item.confidenceLevel]||item.confidenceLevel}</em></summary><div className="source-card-body insight-body">{item.observation&&<section className="insight-observation"><strong>Dữ kiện từ bài review</strong><p>{item.observation}</p></section>}<div className="insight-grid"><InsightSection title="Năng lực được kiểm tra" items={item.testedAbilities}/><InsightSection title="Điểm đáng chú ý" items={item.notableFeatures}/><InsightSection title={`Độ khó: ${label[item.difficulty?.level]||item.difficulty?.level||'Chưa rõ'}`} items={item.difficulty?.reasons}/><InsightSection title="Lỗi người học dễ gặp" items={item.likelyErrors}/></div><section className="insight-action"><strong>Hướng luyện tập đề xuất</strong><p>{item.learnerImplication||'Chưa có diễn giải.'}</p>{list(item.recommendedPractice).length>0&&<ul>{item.recommendedPractice.map((value,i)=><li key={i}>{value}</li>)}</ul>}</section><Refs title="Dựa trên câu" values={item.basedOnRecallIds}/></div></details>)}</div>}
function NeedList({items,blocked}){return <>{items.length?<div className="source-card-list proposal-list">{items.map((item,index)=><details key={item.id} open={index===0}><summary><div><b>{item.id} · {label[item.scope]||item.scope}</b><h2>{item.title||item.objective||'Đề xuất học liệu'}</h2><span>{item.skill} {item.questionGroup&&`· ${item.questionGroup}`}</span></div><em className={`priority ${(item.priority?.level||'MEDIUM').toLowerCase()}`}>Ưu tiên {label[item.priority?.level]||item.priority?.level||'Trung bình'}</em></summary><div className="source-card-body proposal-body"><section className="proposal-purpose"><strong>Mục tiêu học liệu</strong><p>{item.objective||'Chưa xác định mục tiêu.'}</p>{item.rationale&&<><strong>Vì sao cần tạo</strong><p>{item.rationale}</p></>}</section><InsightSection title="Trọng tâm luyện tập" items={item.learningFocus}/><ContentBrief brief={item.contentBrief}/><Deliverables item={item}/><InsightSection title="Tiêu chí nghiệm thu" items={item.successCriteria}/><div className="proposal-links"><Refs title="Dựa trên câu" values={item.basedOnRecallIds}/><Refs title="Dựa trên insight" values={item.basedOnInsightIds}/></div></div></details>)}</div>:<Empty icon={BookOpenCheck} title="Chưa có đề xuất học liệu hợp lệ" note="Hệ thống chưa xác định được học liệu gắn trực tiếp với câu nhớ lại."/>}{blocked.length>0&&<section className="blocked-scope"><h2>Chưa đủ dữ liệu để đề xuất</h2>{blocked.map((item,index)=><div key={index}><strong>{label[item.scope]||item.scope?.replaceAll('_',' ')}</strong><span>{item.reason}</span></div>)}</section>}</>}
function Evidence({items}){return list(items).length?<div className="evidence-box"><strong>Bằng chứng nguyên văn</strong>{items.map((item,index)=><blockquote key={index}>“{item.quote||item}”{item.segmentId&&<small>{item.segmentId}</small>}</blockquote>)}</div>:null}
function Refs({title,values}){return <div className="source-refs"><strong>{title}</strong>{list(values).length?values.map(value=><span key={value}>{value}</span>):<em>Phiên bản cũ chưa có liên kết</em>}</div>}
function InsightSection({title,items}){const values=list(items);if(!values.length)return null;return <section><strong>{title}</strong><ul>{values.map((value,index)=><li key={index}>{value}</li>)}</ul></section>}
function ContentBrief({brief={}}){if(!brief.context&&!brief.task&&!list(brief.languageFocus).length)return null;return <section className="content-brief"><strong>Brief nội dung</strong><dl>{brief.context&&<div><dt>Bối cảnh mới</dt><dd>{brief.context}</dd></div>}{brief.task&&<div><dt>Nhiệm vụ</dt><dd>{brief.task}</dd></div>}<div><dt>Độ khó</dt><dd>{label[brief.difficulty]||brief.difficulty||'Trung bình'}</dd></div>{list(brief.languageFocus).length>0&&<div><dt>Ngôn ngữ trọng tâm</dt><dd>{brief.languageFocus.join(' · ')}</dd></div>}</dl></section>}
function Deliverables({item}){const deliverables=list(item.deliverables).length?item.deliverables:list(item.materialTypes).map(type=>({type,quantity:1,description:''}));if(!deliverables.length)return null;return <section className="proposal-deliverables"><strong>Bộ học liệu cần tạo</strong><div>{deliverables.map((deliverable,index)=><article key={`${deliverable.type}-${index}`}><b>{deliverable.quantity}</b><span>{materialTypeLabel[deliverable.type]||deliverable.type.replaceAll('_',' ')}</span>{deliverable.description&&<small>{deliverable.description}</small>}</article>)}</div></section>}
