import {useCallback,useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ChevronLeft,ChevronRight,ClipboardPaste,Eye,FileImage,FileText,RefreshCw,ScanSearch,Sparkles,Trash2,UploadCloud,X} from 'lucide-react';
import {useDialog} from '../../../components/feedback/dialogContext';
import {analyzeContentSource,deleteContentSource,detectContentSource,listContentSources} from '../../../services/contentSourceService';
import './ContentSourcePage.css';
import './ContentSourceAnalysis.css';
import './ContentSourceReview.css';
import './ContentSourceCompact.css';
import './ContentSourceInputTabs.css';
import './ContentSourceHistory.css';
import './ContentSourceAnalysisAnchor.css';

const ACCEPT=['image/jpeg','image/png','image/webp','application/pdf'];
const size=value=>value>1024*1024?`${(value/1024/1024).toFixed(1)} MB`:`${Math.ceil(value/1024)} KB`;

export default function ContentSourcePage({showMsg}){
  const navigate=useNavigate();
  const [inputMode,setInputMode]=useState('text'),[files,setFiles]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[history,setHistory]=useState([]),[dragging,setDragging]=useState(false),[draft,setDraft]=useState(''),[,setAnalysis]=useState(null),[analyzing,setAnalyzing]=useState(false);
  const [page,setPage]=useState(1),[historyMeta,setHistoryMeta]=useState({page:1,totalPages:1,total:0}),[deletingId,setDeletingId]=useState(null);
  const {confirm:confirmDialog}=useDialog();
  const inputRef=useRef(null);
  const load=useCallback(async(targetPage=1)=>{try{const sources=await listContentSources({page:targetPage,limit:10});setHistory(sources.data||[]);setHistoryMeta(sources.meta||{page:targetPage,totalPages:1,total:0});setPage(targetPage);}catch{}},[]);
  useEffect(()=>{load(1);},[load]);
  const openResult=data=>{setInputMode(data?.sourceType==='text'?'text':'file');setResult(data);setDraft(data?.extractedText||'');setText(data?.sourceType==='text'?data?.extractedText||'':'');setFiles([]);setAnalysis(data?.latestAnalysis||null);};
  const choose=useCallback(candidates=>{const incoming=[...(candidates||[])];if(!incoming.length)return;const invalid=incoming.find(item=>!ACCEPT.includes(item.type));if(invalid){showMsg(`File “${invalid.name}” không được hỗ trợ. Chỉ dùng JPG, PNG, WebP và PDF.`,'error');return;}const oversized=incoming.find(item=>item.size>20*1024*1024);if(oversized){showMsg(`File “${oversized.name}” vượt quá 20 MB.`,'error');return;}setInputMode('file');setText('');setResult(null);setAnalysis(null);setFiles(current=>{const merged=[...current];for(const item of incoming){if(!merged.some(file=>file.name===item.name&&file.size===item.size&&file.lastModified===item.lastModified))merged.push(item);}if(merged.length>10){showMsg('Mỗi lượt hỗ trợ tối đa 10 file.','error');return merged.slice(0,10);}if(merged.reduce((sum,item)=>sum+item.size,0)>50*1024*1024){showMsg('Tổng dung lượng mỗi lượt không được vượt quá 50 MB.','error');return current;}return merged;});},[showMsg]);
  useEffect(()=>{const paste=event=>{const images=[...(event.clipboardData?.items||[])].filter(item=>item.type.startsWith('image/')).map((item,index)=>{const blob=item.getAsFile();return new File([blob],`screenshot-${Date.now()}-${index+1}.png`,{type:blob.type||'image/png'});});if(images.length){event.preventDefault();choose(images);}};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);},[choose]);
  const detect=async()=>{if(!files.length&&!text.trim())return;setBusy(true);try{const data=await detectContentSource({file:files[0],files:files.length>1?files:undefined,text:text.trim()});openResult(data);if(inputMode==='text'){const analyzed=await analyzeContentSource(data.id,text.trim());setAnalysis(analyzed);showMsg(analyzed.cached?'Đã mở kết quả phân tích hiện có.':'AI đã phân tích và kiểm chứng nội dung.');navigate(`/content-sources/${data.id}`);}else showMsg(`Đã trích xuất nội dung từ ${files.length} file.`);await load(1);}catch(error){showMsg(error.response?.data?.error||'Không thể xử lý nội dung.','error');}finally{setBusy(false);}};
  const remove=async item=>{if(!await confirmDialog({title:'Xóa nguồn?',message:`“${item.detectedContent?.title||item.filename||'Nội dung đã nhập'}” và kết quả phân tích liên quan sẽ bị xóa.`,confirmText:'Xóa nguồn'}))return;setDeletingId(item.id);try{await deleteContentSource(item.id);if(result?.id===item.id){setResult(null);setAnalysis(null);setDraft('');setText('');}const targetPage=history.length===1&&page>1?page-1:page;await load(targetPage);showMsg('Đã xóa nguồn và cập nhật lại xu hướng.');}catch(error){showMsg(error.response?.data?.error||'Không thể xóa nguồn.','error');}finally{setDeletingId(null);}};
  const analyze=async()=>{if(!result||draft.trim().length<20)return;setAnalyzing(true);try{const data=await analyzeContentSource(result.id,draft.trim());setAnalysis(data);showMsg(data.cached?'Đã mở kết quả phân tích hiện có.':'AI đã phân tích và kiểm chứng bằng chứng.');navigate(`/content-sources/${result.id}`);}catch(error){showMsg(error.response?.data?.error||'Không thể phân tích nội dung.','error');}finally{setAnalyzing(false);}};
  const meta=result?.detectedContent||{};
  return <div className="content-source-page">
    <header className="content-source-header"><div><span>CONTENT INTELLIGENCE</span><h1>Nhập nguồn học liệu</h1><p>Tải tài liệu, ảnh hoặc dán screenshot để hệ thống nhận diện nội dung.</p></div><button onClick={()=>load(page)}><RefreshCw/>Làm mới</button></header>
    <div className="content-source-layout file-mode"><section className="content-source-ingest card">
      <div className="section-heading"><span><ScanSearch/></span><div><h2>Thêm nội dung mới</h2><p>Chọn một cách nhập cho mỗi lượt xử lý.</p></div></div>
      <div className="content-input-tabs" role="tablist" aria-label="Cách nhập nội dung"><button role="tab" aria-selected={inputMode==='text'} className={inputMode==='text'?'active':''} onClick={()=>{setInputMode('text');setFiles([]);setResult(null);setAnalysis(null);}}><FileText/>Dán văn bản</button><button role="tab" aria-selected={inputMode==='file'} className={inputMode==='file'?'active':''} onClick={()=>{setInputMode('file');setText('');setResult(null);setAnalysis(null);}}><FileImage/>Ảnh / PDF</button></div>
      {inputMode==='file'&&<><div className={`content-dropzone content-dropzone-tab compact ${dragging?'dragging':''}`} onDragEnter={event=>{event.preventDefault();setDragging(true);}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);choose(event.dataTransfer.files);}} onClick={()=>inputRef.current?.click()}>
        <input ref={inputRef} multiple type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={event=>{choose(event.target.files);event.target.value='';}}/>
        <UploadCloud/><strong>Thêm ảnh hoặc PDF</strong><small>Chọn nhiều file, kéo thả hoặc dán ảnh</small><em><ClipboardPaste/>Tối đa 10 file · 50 MB/lượt</em>
      </div><div className="content-file-list"><header><strong>File đã chọn</strong><span>{files.length}/10</span></header>{files.length===0?<p>Chưa có file nào.</p>:files.map((file,index)=><article key={`${file.name}-${file.size}-${file.lastModified}`}><span>{file.type==='application/pdf'?<FileText/>:<FileImage/>}</span><div><strong>{file.name}</strong><small>{size(file.size)}</small></div><button aria-label={`Xóa ${file.name}`} onClick={()=>{setFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index));setResult(null);setAnalysis(null);}}><X/></button></article>)}</div></>}
      {inputMode==='text'&&<div className="content-text-guide"><FileText/><strong>Dán nội dung đầy đủ</strong><p>Có thể nhập bài review, bài đăng, bình luận hoặc ghi chú.</p><ul><li>Giữ nguyên câu chữ của nguồn</li><li>Không cần tự tóm tắt trước</li><li>AI sẽ trích bằng chứng từ nội dung gốc</li></ul></div>}
      {inputMode==='file'&&<footer><span>Các file được ghép thành một nguồn theo đúng thứ tự danh sách.</span><button disabled={busy||!files.length} onClick={detect}>{busy?<RefreshCw className="spin"/>:<ScanSearch/>}{busy?'Đang trích xuất…':`Trích xuất ${files.length||''} file`}</button></footer>}
    </section>
    <section className="content-source-result card">
      <div className="section-heading"><span><FileText/></span><div><h2>{inputMode==='text'?'Dán nội dung nguồn':'Nội dung đã trích xuất'}</h2><p>{inputMode==='text'?'Nhập văn bản gốc tại đây rồi gửi thẳng sang bước phân tích AI.':'Văn bản đọc từ nguồn sẽ xuất hiện ở đây để bạn kiểm tra và sửa trước khi AI phân tích.'}</p></div></div>
      {inputMode==='text'?<div className="content-text-entry"><textarea value={text} onChange={event=>{setText(event.target.value);setResult(null);setAnalysis(null);}} placeholder="Dán toàn bộ bài review, nội dung bài đăng, bình luận hoặc ghi chú tại đây…"/><small>{text.length.toLocaleString('vi-VN')} ký tự</small><footer><span>Nên dán đầy đủ nội dung để AI giữ đúng ngữ cảnh.</span><button disabled={busy||!text.trim()} onClick={detect}>{busy?<RefreshCw className="spin"/>:<Sparkles/>}{busy?'AI đang phân tích…':'Phân tích bằng AI'}</button></footer></div>:!result?<div className="content-result-empty"><FileText/><strong>Chưa có nội dung</strong><span>Sau khi bấm “Trích xuất nội dung”, kết quả có thể chỉnh sửa sẽ hiển thị tại đây.</span></div>:<div className="content-result-body">
        <div className="content-result-title"><div><span>{meta.documentType||result.sourceType}</span><h3>{meta.title||result.filename||'Nội dung đã nhập'}</h3></div><b>{Math.round((Number(meta.confidence)||0)*100)}% tin cậy</b></div>
        <div className="content-result-tags">{(meta.toeicSkills||[]).map(skill=><span key={skill}>{skill}</span>)}{meta.isExamRecall&&<span className="recall">REVIEW ĐỀ THI</span>}</div>
        {meta.summary&&<p className="content-summary">{meta.summary}</p>}
        <label>Nội dung trích xuất · có thể chỉnh sửa</label><textarea className="content-extracted-editor" value={draft} onChange={event=>{setDraft(event.target.value);setAnalysis(null);}}/>
        <div className="content-result-foot"><span>Phương thức: {result.extractionMethod==='gemini_vision'?'Gemini Vision':result.extractionMethod==='pdf_text'?'PDF Text':'Quy tắc nội bộ'}</span>{meta.pageCount&&<span>{meta.pageCount} trang</span>}</div>
        <button className="content-analyze-button" disabled={analyzing||draft.trim().length<20} onClick={analyze}>{analyzing?<RefreshCw className="spin"/>:<Sparkles/>}{analyzing?'AI đang đối chiếu bằng chứng…':'Phân tích chính xác bằng AI'}</button>
      </div>}
    </section></div>
    <SourceHistory items={history} meta={historyMeta} page={page} deletingId={deletingId} open={item=>navigate(`/content-sources/${item.id}`)} remove={remove} changePage={load}/>
  </div>;
}

function SourceHistory({items,meta,page,deletingId,open,remove,changePage}){return <section className="content-source-history card"><header className="content-history-head"><div className="section-heading"><span><FileText/></span><div><h2>Lịch sử nguồn đã nhập</h2><p>10 nguồn mỗi trang · chọn Xem để mở nội dung và kết quả AI.</p></div></div><b>{meta.total||0} nguồn</b></header>{items.length===0?<div className="history-empty">Chưa có nguồn nào.</div>:<div className="content-history-table"><div className="history-row history-labels"><span>Nguồn</span><span>Loại</span><span>Trạng thái</span><span>Thời gian</span><span>Thao tác</span></div>{items.map(item=><HistoryRow key={item.id} item={item} deleting={deletingId===item.id} open={open} remove={remove}/>)}</div>}<footer className="history-pagination"><span>Trang {page}/{meta.totalPages||1}</span><div><button aria-label="Trang trước" disabled={page<=1} onClick={()=>changePage(page-1)}><ChevronLeft/></button><button aria-label="Trang sau" disabled={page>=(meta.totalPages||1)} onClick={()=>changePage(page+1)}><ChevronRight/></button></div></footer></section>}
function HistoryRow({item,deleting,open,remove}){const analysis=item.latestAnalysis,status=item.status==='failed'?['failed','Có lỗi']:analysis?.reviewLabel==='APPROVED'?['approved','Đã xác nhận']:analysis?.reviewLabel==='REJECTED'?['rejected','Không sử dụng']:analysis?['pending','Cần kiểm tra']:['unprocessed','Chưa phân tích'];const kind=item.sourceType==='text'?'Văn bản':item.sourceType==='pdf'?'PDF':'Ảnh';return <div className="history-row"><div className="history-source"><span className={`source-kind ${item.sourceType}`}>{item.sourceType==='image'?<FileImage/>:<FileText/>}</span><span><strong>{item.detectedContent?.title||item.filename||'Nội dung đã nhập'}</strong><small>{(item.detectedContent?.toeicSkills||[]).join(', ')||'Chưa phân loại'}</small></span></div><span>{kind}</span><b className={`history-status ${status[0]}`}>{status[1]}</b><time>{new Date(item.createdAt).toLocaleString('vi-VN')}</time><div className="history-actions"><button onClick={()=>open(item)}><Eye/>Xem</button><button className="delete" disabled={deleting} onClick={()=>remove(item)}>{deleting?<RefreshCw className="spin"/>:<Trash2/>}Xóa</button></div></div>}
