import {useEffect,useState} from 'react';
import {BookOpenCheck,RefreshCw,Save,Settings2,X} from 'lucide-react';
import {getMaterialSettings,previewMaterialRules,saveMaterialSettings} from '../../../services/contentSourceService';
import './MaterialSettingsPanel.css';
import './MaterialSettingsIsolation.css';
import './MaterialSettingsInsights.css';

const SKILLS=['LISTENING','READING','SPEAKING','WRITING'];
const TYPES=[['STRATEGY_LESSON','Bài chiến lược'],['SKILL_DRILL','Bài luyện từng dạng'],['ERROR_DRILL','Bài luyện lỗi'],['VOCABULARY_PACK','Bộ từ vựng'],['MINI_TEST','Mini test'],['FULL_MOCK_TEST','Đề thi thử'],['SAMPLE_ANSWER','Bài mẫu'],['SELF_REVIEW_RUBRIC','Rubric tự đánh giá']];
const toggle=(array,value)=>array.includes(value)?array.filter(item=>item!==value):[...array,value];

export default function MaterialSettingsPanel({showMsg}){
  const [settings,setSettings]=useState(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[preview,setPreview]=useState(null);
  useEffect(()=>{Promise.all([getMaterialSettings(),previewMaterialRules()]).then(([savedSettings,rulePreview])=>{setSettings(savedSettings);setPreview(rulePreview);}).catch(()=>{});},[]);
  useEffect(()=>{if(!open)return undefined;const close=event=>{if(event.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[open]);
  if(!settings)return null;
  const patch=value=>setSettings(current=>({...current,...value}));
  const save=async()=>{setSaving(true);try{const data=await saveMaterialSettings(settings);setSettings(data);showMsg('Đã lưu cấu hình đề xuất học liệu.');setPreview(await previewMaterialRules());setOpen(false);}catch(error){showMsg(error.response?.data?.error||'Không thể lưu cấu hình.','error');}finally{setSaving(false);}};
  const runPreview=async()=>{try{setPreview(await previewMaterialRules());}catch(error){showMsg(error.response?.data?.error||'Không thể kiểm tra rule.','error');}};
  const total=Object.values(settings.materialQuantities||{}).reduce((sum,value)=>sum+Number(value||0),0);
  return <>
    <section className="settings-overview card">
      <div className="section-heading"><span><Settings2/></span><div><h2>Cấu hình tạo học liệu</h2><p>Các tiêu chí đang áp dụng khi lập blueprint.</p></div></div>
      <div className="settings-overview-facts"><span><small>Xu hướng đã chọn</small><strong>{preview?.meta?.selected??0}</strong></span><span><small>Qua rule hiện tại</small><strong>{preview?.meta?.eligible??0}</strong></span><span><small>Loại học liệu</small><strong>{settings.enabledMaterialTypes.length}</strong></span><span><small>Số lượng dự kiến</small><strong>{total}</strong></span></div>
      <button onClick={()=>setOpen(true)}><Settings2/>Mở cấu hình</button>
    </section>
    {preview&&<RulePreview result={preview}/>}
    {open&&<div className="settings-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false);}}><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-modal-title">
      <header><div><small>CẤU HÌNH BLUEPRINT</small><h2 id="settings-modal-title">Tiêu chí tạo học liệu</h2><p>Thiết lập một lần, sau đó áp dụng cho các blueprint mới.</p></div><button aria-label="Đóng" onClick={()=>setOpen(false)}><X/></button></header>
      <div className="material-settings-body">
        <div className="settings-context"><BookOpenCheck/><span><small>ĐANG CẤU HÌNH CHO</small><strong>{preview?.meta?.selected||0} xu hướng đã chọn · {preview?.data?.filter(item=>item.eligible).map(item=>item.skill).filter((value,index,array)=>array.indexOf(value)===index).join(', ')||'chưa có kỹ năng qua rule'}</strong><em>{preview?.meta?.eligible||0} xu hướng đang đáp ứng cấu hình hiện tại</em></span></div>
        <div className="setting-section"><h3>1. Đối tượng học liệu</h3><p className="setting-help">Chỉ bật các kỹ năng cần sinh học liệu và xác định trình độ người học.</p><div className="setting-chips">{SKILLS.map(skill=><button key={skill} className={settings.enabledSkills.includes(skill)?'active':''} onClick={()=>patch({enabledSkills:toggle(settings.enabledSkills,skill)})}>{skill}</button>)}</div><div className="setting-grid target"><label>Target Listening/Reading<input value={settings.targetScores.LISTENING_READING||''} onChange={event=>patch({targetScores:{...settings.targetScores,LISTENING_READING:event.target.value}})}/></label><label>Target Speaking/Writing<input value={settings.targetScores.SPEAKING_WRITING||''} onChange={event=>patch({targetScores:{...settings.targetScores,SPEAKING_WRITING:event.target.value}})}/></label><label>Ngôn ngữ hướng dẫn<select value={settings.instructionLanguage} onChange={event=>patch({instructionLanguage:event.target.value})}><option value="VI">Tiếng Việt</option><option value="EN">Tiếng Anh</option><option value="BILINGUAL">Song ngữ</option></select></label></div></div>
        <div className="setting-section"><h3>2. Thành phần bộ học liệu</h3><p className="setting-help">Chọn đầu ra cần tạo. Số lượng có thể chỉnh tiếp trong blueprint.</p><div className="material-type-grid">{TYPES.map(([type,typeLabel])=><label className={settings.enabledMaterialTypes.includes(type)?'enabled':''} key={type}><input type="checkbox" checked={settings.enabledMaterialTypes.includes(type)} onChange={()=>patch({enabledMaterialTypes:toggle(settings.enabledMaterialTypes,type)})}/><span><strong>{typeLabel}</strong><small>{settings.enabledMaterialTypes.includes(type)?'Có trong blueprint':'Không sử dụng'}</small></span><input aria-label={`Số lượng ${typeLabel}`} type="number" min="0" max="100" disabled={!settings.enabledMaterialTypes.includes(type)} value={settings.materialQuantities[type]??0} onChange={event=>patch({materialQuantities:{...settings.materialQuantities,[type]:Number(event.target.value)}})}/></label>)}</div></div>
        <div className="setting-section"><h3>3. Phân bổ độ khó</h3><p className="setting-help">Tỷ lệ câu hỏi theo ba mức độ trong bộ học liệu.</p><div className="difficulty-grid">{[['BASIC','Cơ bản'],['INTERMEDIATE','Trung bình'],['ADVANCED','Nâng cao']].map(([key,difficultyLabel])=><label key={key}>{difficultyLabel}<div><input type="number" min="0" max="100" value={settings.difficultyMix[key]} onChange={event=>patch({difficultyMix:{...settings.difficultyMix,[key]:Number(event.target.value)}})}/><span>%</span></div></label>)}</div><small className="difficulty-total">Tổng: {Object.values(settings.difficultyMix).reduce((sum,value)=>sum+Number(value||0),0)}%</small></div>
        <details className="advanced-settings"><summary><span><strong>Cài đặt nâng cao</strong><small>Ngưỡng bằng chứng, độ tin cậy và chống sao chép nguồn</small></span><b>Mở</b></summary><div className="setting-grid"><label>Nguồn độc lập tối thiểu<input type="number" min="1" max="20" value={settings.minimumSources} onChange={event=>patch({minimumSources:Number(event.target.value)})}/></label><label>Độ tin cậy tối thiểu (%)<input type="number" min="0" max="100" value={Math.round(settings.minimumConfidence*100)} onChange={event=>patch({minimumConfidence:Number(event.target.value)/100})}/></label><label>Khoảng xu hướng (ngày)<input type="number" min="7" max="365" value={settings.trendWindowDays} onChange={event=>patch({trendWindowDays:Number(event.target.value)})}/></label><label>Độ giống tối đa với nguồn (%)<input type="number" min="30" max="90" value={Math.round(settings.maximumSourceSimilarity*100)} onChange={event=>patch({maximumSourceSimilarity:Number(event.target.value)/100})}/></label></div></details>
        <label className="blueprint-approval"><input type="checkbox" checked={settings.requireBlueprintApproval} onChange={event=>patch({requireBlueprintApproval:event.target.checked})}/><span><strong>Duyệt blueprint trước khi AI sinh nội dung</strong><small>Ngăn sinh hàng loạt khi kế hoạch chưa được xác nhận.</small></span></label>
      </div>
      <footer><button className="secondary" onClick={runPreview}><BookOpenCheck/>Xem trước kết quả</button><button disabled={saving} onClick={save}>{saving?<RefreshCw className="spin"/>:<Save/>}{saving?'Đang lưu…':'Lưu và áp dụng'}</button></footer>
    </section></div>}
  </>;
}

function RulePreview({result}){return <div className="rule-preview"><header><div><small>KẾT QUẢ ÁP DỤNG RULE</small><strong>{result.meta?.eligible||0} xu hướng đủ điều kiện</strong></div><span>{result.meta?.excluded||0} xu hướng bị loại</span></header>{result.data?.length===0?<p>Chưa có trend để đánh giá.</p>:result.data?.map(item=><article key={item.id}><span>{item.skill} · {item.questionGroup}</span><strong>{item.topic||item.taskType}</strong><b className={item.eligible?'eligible':'excluded'}>{item.eligible?'Đưa vào blueprint':item.exclusionReasons.join(' · ')}</b></article>)}</div>}
