import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ListFilter,RefreshCw,ScanSearch,X} from 'lucide-react';
import './ContentSourceTrends.css';

const trendKey=trend=>trend.id||`${trend.skill}-${trend.questionGroup}-${trend.topic}`;
const trendLabel=trend=>trend.trendType==='REPEATED_PROMPT'?'Nội dung câu hỏi được ghi nhận lặp lại giữa các đề.':trend.trendType==='RECURRING_TASK_TOPIC'?'Dạng bài hoặc chủ đề đang xuất hiện lại ở nhiều nguồn.':'Tín hiệu mới chỉ xuất hiện trong một nguồn.';
const implication=trend=>trend.verificationStatus==='CONFIRMED'?`Ưu tiên tạo bài luyện ${trend.taskType||trend.questionGroup||'đúng dạng'} quanh chủ đề này.`:'Chưa đưa vào học liệu; cần thêm ít nhất một nguồn độc lập để xác nhận.';
const sourceTitle=source=>source.detectedContent?.title||source.filename||'Nội dung đã nhập';
const formatDate=value=>value?new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(value)):'';

export default function TrendClusters({trends,meta,sources=[],busy,rebuild,onContinue}){
  const [mode,setMode]=useState('ALL'),[selectedSources,setSelectedSources]=useState([]),[selectedTrends,setSelectedTrends]=useState([]),[pickerOpen,setPickerOpen]=useState(false),[signalsOpen,setSignalsOpen]=useState(false);
  const confirmed=useMemo(()=>trends.filter(item=>item.verificationStatus==='CONFIRMED'),[trends]);
  const signals=useMemo(()=>trends.filter(item=>item.verificationStatus!=='CONFIRMED'),[trends]);
  useEffect(()=>{setSelectedSources(current=>current.filter(id=>sources.some(source=>source.id===id)));},[sources]);
  useEffect(()=>{const hasPersistedField=confirmed.some(item=>Object.prototype.hasOwnProperty.call(item,'isSelected'));setSelectedTrends((hasPersistedField?confirmed.filter(item=>item.isSelected):confirmed).map(trendKey));},[confirmed]);
  const activeCount=mode==='ALL'?sources.length:selectedSources.length;
  const chosenSources=useMemo(()=>sources.filter(source=>selectedSources.includes(source.id)),[sources,selectedSources]);
  const toggleSource=id=>setSelectedSources(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleTrend=id=>setSelectedTrends(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const run=()=>rebuild(mode==='SELECTED'?selectedSources:undefined);
  return <section className="trend-clusters card">
    <div className="trend-cluster-head"><div className="section-heading"><span><ScanSearch/></span><div><h2>Insight xu hướng</h2><p>Đối chiếu các nguồn đã xác nhận và chọn xu hướng dùng cho học liệu.</p></div></div><div className="trend-actions"><button className="source-scope-button" onClick={()=>setPickerOpen(true)}><ListFilter/>{activeCount} nguồn đang đối chiếu</button><button disabled={busy||!activeCount} onClick={run}>{busy?<RefreshCw className="spin"/>:<ScanSearch/>}{busy?'Đang tổng hợp…':'Tổng hợp lại'}</button></div></div>
    <div className="trend-scope-chip"><span>Phạm vi</span><strong>{mode==='ALL'?`Tất cả ${sources.length} nguồn đã xác nhận`:`${selectedSources.length} nguồn được chọn`}</strong>{mode==='SELECTED'&&<small>{chosenSources.slice(0,2).map(sourceTitle).join(' · ')}{chosenSources.length>2?` · +${chosenSources.length-2}`:''}</small>}</div>
    {trends.length===0?<div className="trend-empty"><strong>Chưa có cụm xu hướng</strong><span>Chọn nguồn đã xác nhận và bấm Tổng hợp lại.</span></div>:<>
      <div className="trend-flow-summary"><div><small>NGUỒN ĐỐI CHIẾU</small><strong>{activeCount}</strong><span>nguồn đã xác nhận</span></div><i><ArrowRight/></i><div><small>NHÓM NỘI DUNG</small><strong>{trends.length}</strong><span>nhóm sau khi gộp</span></div><i><ArrowRight/></i><div className="confirmed"><small>XU HƯỚNG ĐỦ CĂN CỨ</small><strong>{confirmed.length}</strong><span>{confirmed.length}/{trends.length} nhóm được xác nhận</span></div></div>
      <div className="trend-decision-compact"><div><small>KẾT LUẬN BƯỚC 2</small><strong>{confirmed.length}/{trends.length} nhóm được xác nhận là xu hướng</strong></div><span>Đã chọn <b>{selectedTrends.length}</b> xu hướng cho bước cấu hình</span></div>
      <div className="trend-section-heading"><div><h3>Xu hướng đủ điều kiện</h3><p>Chọn những xu hướng sẽ được áp dụng rule và đưa vào blueprint.</p></div>{confirmed.length>0&&<button onClick={()=>setSelectedTrends(selectedTrends.length===confirmed.length?[]:confirmed.map(trendKey))}>{selectedTrends.length===confirmed.length?'Bỏ chọn tất cả':'Chọn tất cả'}</button>}</div>
      {confirmed.length?<div className="trend-grid eligible-grid">{confirmed.map(trend=><TrendCard key={trendKey(trend)} trend={trend} selected={selectedTrends.includes(trendKey(trend))} onToggle={()=>toggleTrend(trendKey(trend))}/>)}</div>:<div className="trend-empty compact"><strong>Chưa có xu hướng đủ điều kiện</strong><span>Cần ít nhất hai nguồn độc lập có nội dung tương đồng.</span></div>}
      {signals.length>0&&<section className="trend-signals"><button onClick={()=>setSignalsOpen(value=>!value)}><span><strong>Nội dung chưa đủ căn cứ</strong><small>{signals.length} nội dung mới xuất hiện ở một nguồn; hệ thống sẽ tự đối chiếu khi có thêm review.</small></span><b>{signalsOpen?'Thu gọn':'Xem nội dung'}</b></button>{signalsOpen&&<><div className="signal-explainer"><strong>Chưa dùng để tạo học liệu</strong><span>Mỗi nội dung cần được ghi nhận từ ít nhất hai nguồn độc lập trước khi được coi là xu hướng.</span></div><div className="trend-grid signal-grid">{signals.map(trend=><TrendCard key={trendKey(trend)} trend={trend}/>)}</div></>}</section>}
      <footer className="trend-continue"><span>{selectedTrends.length?`${selectedTrends.length} xu hướng sẽ được đưa sang cấu hình.`:'Chọn ít nhất một xu hướng đủ điều kiện để tiếp tục.'}</span><button disabled={!selectedTrends.length||busy} onClick={()=>onContinue(selectedTrends)}>Tiếp tục với {selectedTrends.length} xu hướng <ArrowRight/></button></footer>
    </>}
    {pickerOpen&&<div className="trend-picker-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setPickerOpen(false);}}><section className="trend-picker" role="dialog" aria-modal="true" aria-labelledby="trend-picker-title"><header><div><small>PHẠM VI TỔNG HỢP</small><h2 id="trend-picker-title">Chọn đề để phân tích xu hướng</h2><p>Chỉ nguồn đã xác nhận mới có thể được sử dụng.</p></div><button aria-label="Đóng" onClick={()=>setPickerOpen(false)}><X/></button></header><div className="trend-mode-picker"><button className={mode==='ALL'?'active':''} onClick={()=>setMode('ALL')}><strong>Tất cả nguồn đã xác nhận</strong><span>Tự động dùng toàn bộ {sources.length} nguồn hiện có.</span></button><button className={mode==='SELECTED'?'active':''} onClick={()=>setMode('SELECTED')}><strong>Chọn nguồn thủ công</strong><span>Phân tích riêng một đợt thi hoặc nhóm kỹ năng.</span></button></div>{mode==='SELECTED'&&<><div className="trend-picker-toolbar"><span>Đã chọn {selectedSources.length}/{sources.length} nguồn</span><button onClick={()=>setSelectedSources(selectedSources.length===sources.length?[]:sources.map(source=>source.id))}>{selectedSources.length===sources.length?'Bỏ chọn tất cả':'Chọn tất cả'}</button></div><div className="trend-source-list">{sources.map(source=>{const analysis=source.latestAnalysis?.analysis||{},skills=analysis.sourceSummary?.skills||analysis.classification?.skills||[];return <label key={source.id} className={selectedSources.includes(source.id)?'selected':''}><input type="checkbox" checked={selectedSources.includes(source.id)} onChange={()=>toggleSource(source.id)}/><span><strong>{sourceTitle(source)}</strong><small>{skills.join(' · ')||'Chưa phân loại'} · {analysis.examContext?.examDate||'Chưa rõ ngày thi'}</small></span></label>})}</div></>}<footer><button className="secondary" onClick={()=>setPickerOpen(false)}>Hủy</button><button disabled={mode==='SELECTED'&&!selectedSources.length} onClick={()=>{setPickerOpen(false);run();}}>Áp dụng và tổng hợp</button></footer></section></div>}
  </section>;
}

function TrendCard({trend,selected=false,onToggle}){const first=formatDate(trend.firstSeenAt),last=formatDate(trend.lastSeenAt),isConfirmed=trend.verificationStatus==='CONFIRMED';if(!isConfirmed)return <article className="signal"><header><span>{trend.skill} · {trend.questionGroup}</span><b className="unverified">Chưa dùng cho học liệu</b></header><h3>{trend.topic||trend.taskType||'Chưa xác định chủ đề'}</h3><p className="signal-reason">Mới được ghi nhận trong một bài review nên chưa thể kết luận đây là xu hướng.</p><div className="signal-progress"><span><small>Đã ghi nhận</small><b>{trend.sourceCount} nguồn</b></span><i/><span><small>Còn thiếu</small><b>{Math.max(0,2-trend.sourceCount)} nguồn để xác nhận</b></span></div><details><summary>Xem bài review đã ghi nhận</summary>{(trend.members||[]).map((member,index)=><blockquote key={index}><strong>Nguồn {index+1}{member.examDate?` · ${formatDate(member.examDate)}`:''}</strong>“{member.evidence}”</blockquote>)}</details></article>;return <article className={`eligible ${selected?'selected':''}`}><header><span>{trend.skill} · {trend.questionGroup}</span><button className="trend-use-toggle" onClick={onToggle}><i>{selected&&<Check/>}</i>{selected?'Đang sử dụng':'Sử dụng xu hướng'}</button></header><h3>{trend.topic||trend.taskType||'Chưa xác định chủ đề'}</h3><div className="trend-finding"><small>NHẬN ĐỊNH</small><p>{trendLabel(trend)}</p></div><div className="trend-implication"><small>Ý NGHĨA VỚI HỌC LIỆU</small><p>{implication(trend)}</p></div><footer><span><b>{trend.sourceCount}</b> nguồn</span><span><b>{Math.round((trend.averageSimilarity||0)*100)}%</b> tương đồng</span><span><b>{Math.round((trend.confidence||0)*100)}%</b> tin cậy</span>{first&&<span>{first===last?first:`${first} → ${last}`}</span>}</footer><details><summary>Xem {trend.members?.length||0} bằng chứng nguồn</summary>{(trend.members||[]).map((member,index)=><blockquote key={index}><strong>Nguồn {index+1}{member.examDate?` · ${formatDate(member.examDate)}`:''}</strong>“{member.evidence}”</blockquote>)}</details></article>}
