import React from 'react';
import {CalendarDays,ChevronDown,FileText,Image as ImageIcon,Upload} from 'lucide-react';
import RichTextEditor from '../../../components/common/RichTextEditor';
import {DateTimePicker} from '../../../components/ui/DateTime';
import SchoolCombobox from './SchoolCombobox';
import {EVENT_CONFIGURATION_OPTIONS,resolveEventLifecycle} from '../examEventStatus';
import './ExamEventFormSections.css';

export default function ExamEventFormSections({form,update,schools,onSchoolCreated,showMsg,selectedExam,onOpenExamPicker,image,banner,onPickImage,onPickBanner,onRemoveImage,onRemoveBanner,isEdit=false}){
  const lifecycle=resolveEventLifecycle(form.status,form.startAt,form.endAt);
  const configurationTone=EVENT_CONFIGURATION_OPTIONS.find(option=>option.value===form.status)?.tone||'draft';
  return <>
    <section className="event-create-card general"><div className="card-title"><div><h2>Thông tin kỳ thi</h2><span>•</span><em className={`is-${lifecycle.tone}`}><i/>{lifecycle.label}</em></div><small>Các trường có dấu <b>*</b> là bắt buộc</small></div><div className="event-general-grid"><label className="event-name-field"><span>Tên kỳ thi <b>*</b></span><input maxLength="240" required value={form.name} onChange={event=>update('name',event.target.value)} placeholder="Ví dụ: Kỳ thi thử TOEIC 4 Kỹ năng - Đợt 1/2026"/><small>Tên hiển thị trên giao diện thí sinh và báo cáo điểm</small></label><label className="event-code-field"><span>Mã kỳ thi (Exam Code) <i>({isEdit?'Cố định':'Tự động'})</i></span><div><input disabled readOnly value={isEdit?form.eventCode:''}/></div><small>Mã định danh duy nhất của kỳ thi</small></label><label className="event-school-field"><span>Đơn vị / Trường tổ chức <b>*</b></span><SchoolCombobox value={form.schoolIds} schools={schools} onChange={value=>update('schoolIds',value)} onCreated={onSchoolCreated} showMsg={showMsg}/></label><label className="event-status-field"><span>Chế độ trạng thái <b>*</b></span><select className={`status-select is-${configurationTone}`} value={form.status} onChange={event=>update('status',event.target.value)}>{EVENT_CONFIGURATION_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><small>Chưa bắt đầu, đang diễn ra và đã kết thúc được tự động xác định theo lịch</small></label><label className="event-description-field"><span>Mô tả &amp; Giới thiệu kỳ thi <b>*</b><i>{form.description.length} / 5,000 ký tự</i></span><RichTextEditor value={form.description} onChange={value=>update('description',value)} placeholder="Nhập nội dung chi tiết về kỳ thi..." minHeight="156px" variant="stitch"/></label></div></section>
    <section className="event-create-card branding"><div className="card-title icon-title"><div><i><ImageIcon/></i><span><h2>Hình ảnh nhận diện kỳ thi</h2><p>Avatar đại diện và ảnh bìa biểu ngữ của kỳ thi hiển thị cho thí sinh</p></span></div><em>Branding Assets</em></div><div className="branding-grid"><MediaField title="Ảnh đại diện kỳ thi (Avatar / Logo)" kind="avatar" value={image} onChange={onPickImage} onRemove={onRemoveImage}/><MediaField title="Ảnh bìa kỳ thi (Cover Banner)" kind="banner" value={banner} onChange={onPickBanner} onRemove={onRemoveBanner} name={form.name}/></div></section>
    <section className="event-create-card schedule"><div className="card-title icon-title"><div><i><CalendarDays/></i><span><h2>Thời gian tổ chức &amp; Đề thi áp dụng</h2><p>Cấu hình khung giờ thí sinh được phép truy cập và bộ đề sử dụng</p></span></div><em><i/>Đã đồng bộ ngân hàng đề</em></div><div className="time-grid"><div className="time-field-wrap"><DateTimePicker label="Ngày & giờ bắt đầu *" value={form.startAt} onChange={isoString=>update('startAt',isoString)}/><small>Hệ thống mở cổng phòng thi đúng thời gian này (GMT+7)</small></div><div className="time-field-wrap"><DateTimePicker label="Ngày & giờ kết thúc *" value={form.endAt} minDate={form.startAt} onChange={isoString=>update('endAt',isoString)}/><small>Tự động khóa nộp bài và kết thúc đợt thi</small></div></div><div className="exam-config-grid"><label className="exam-select"><span>Chọn đề thi áp dụng <b>*</b></span><button className="exam-picker-trigger" type="button" onClick={onOpenExamPicker}><span>{selectedExam?.title||'Chọn đề thi đã duyệt phát hành'}</span><ChevronDown/></button>{selectedExam&&<div className="exam-preview"><i><FileText/></i><span><strong>{selectedExam.title}</strong><small>{Math.floor(selectedExam.durationSeconds/60)} phút • {selectedExam.subQuestionCount} câu hỏi • Thang điểm {selectedExam.scoreScale}</small></span><em><i/>Đã duyệt phát hành</em></div>}</label><label className="internal-note"><span>Ghi chú bổ sung cho kỳ thi (Giám thị &amp; Quản trị viên)</span><input maxLength="1000" value={form.internalNote} onChange={event=>update('internalNote',event.target.value)} placeholder="Ví dụ: Mã keycode phòng máy sẽ được phát tại bàn lễ tân trước ca thi 30 phút..."/></label></div></section>
  </>;
}

function MediaField({title,kind,value,onChange,onRemove,name}){const inputId=`event-${kind}-upload`;return <div className={`event-media-field ${kind}${value?' has-value':''}`}><span>{title}</span><div className="event-media-box"><input id={inputId} type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{onChange(event.target.files?.[0]);event.target.value='';}}/>{value?<div className="event-media-preview"><img src={value.url} alt={title}/>{kind==='banner'&&<div className="banner-caption"><em>Preview Banner</em><strong>{name||'Kỳ thi mới'}</strong></div>}</div>:<label className="media-placeholder" htmlFor={inputId}><Upload/><strong>Kéo &amp; thả {kind==='avatar'?'logo':'ảnh bìa'} hoặc <span>tải lên</span></strong><small>{kind==='avatar'?'Khuyến nghị tỉ lệ 1:1 • PNG, JPG tối đa 2MB':'Kích thước đề xuất: 1200 x 400 px • JPG, PNG tối đa 5MB'}</small></label>}{value&&<footer><small>{kind==='avatar'?'Khuyến nghị tỉ lệ 1:1 • PNG, JPG tối đa 2MB':'Kích thước đề xuất: 1200 × 400 px (JPG, PNG tối đa 5MB)'}</small><aside>{onRemove&&<button type="button" onClick={onRemove}>{kind==='banner'?'Gỡ bỏ':'Xóa'}</button>}<label htmlFor={inputId}>{kind==='banner'?'Tải ảnh mới':'Đổi ảnh khác'}</label></aside></footer>}</div></div>}
