const service=require('../modules/exams/examService');
const list=async(req,res)=>res.json({success:true,...await service.list(req.query)});
const detail=async(req,res)=>res.json({success:true,data:await service.get(req.params.examId)});
const create=async(req,res)=>res.status(201).json({success:true,data:await service.create(req.body,req.auth?.userId)});
const update=async(req,res)=>res.json({success:true,data:await service.update(req.params.examId,req.body,req.auth?.userId)});
const remove=async(req,res)=>{await service.remove(req.params.examId);res.json({success:true,id:req.params.examId});};
const duplicate=async(req,res)=>res.status(201).json({success:true,data:await service.duplicate(req.params.examId,req.auth?.userId)});
const addPart=async(req,res)=>res.status(201).json({success:true,data:await service.addPart(req.params.examId,req.body)});
const updatePart=async(req,res)=>res.json({success:true,data:await service.updatePart(req.params.examId,req.params.partId,req.body)});
const removePart=async(req,res)=>res.json({success:true,data:await service.removePart(req.params.examId,req.params.partId)});
const reorderParts=async(req,res)=>res.json({success:true,data:await service.reorderParts(req.params.examId,req.body.partIds)});
const available=async(req,res)=>res.json({success:true,...await service.listAvailableQuestions(req.params.examId,req.query)});
const addQuestions=async(req,res)=>res.status(201).json({success:true,data:await service.addQuestions(req.params.examId,req.params.partId,req.body.questionIds)});
const removeQuestion=async(req,res)=>res.json({success:true,data:await service.removeQuestion(req.params.examId,req.params.partId,req.params.questionId)});
const reorderQuestions=async(req,res)=>res.json({success:true,data:await service.reorderQuestions(req.params.examId,req.params.partId,req.body.questionIds)});
const validation=async(req,res)=>res.json({success:true,data:await service.validation(req.params.examId)});
const activate=async(req,res)=>res.json({success:true,data:await service.activate(req.params.examId,req.auth?.userId)});
const deactivate=async(req,res)=>res.json({success:true,data:await service.deactivate(req.params.examId,req.auth?.userId)});
module.exports={list,detail,create,update,remove,duplicate,addPart,updatePart,removePart,reorderParts,available,addQuestions,removeQuestion,reorderQuestions,validation,activate,deactivate};
