const service=require('../modules/exam-events/examEventService');
const list=async(req,res)=>res.json({success:true,...await service.list(req.query)});
const detail=async(req,res)=>res.json({success:true,data:await service.get(req.params.eventId)});
const create=async(req,res)=>res.status(201).json({success:true,data:await service.createExamEvent(req.body,req.auth?.userId)});
const update=async(req,res)=>res.json({success:true,data:await service.updateExamEvent(req.params.eventId,req.body,req.auth?.userId)});
const remove=async(req,res)=>{await service.removeExamEvent(req.params.eventId);res.json({success:true,id:req.params.eventId});};
const schools=async(req,res)=>res.json({success:true,data:await service.schools()});
const createSchool=async(req,res)=>res.status(201).json({success:true,data:await service.createSchool(req.body,req.auth?.userId)});
const uploadMedia=async(req,res)=>res.json({success:true,data:await service.uploadMedia(req.params.eventId,req.params.kind,req.file)});
const removeMedia=async(req,res)=>res.json({success:true,data:await service.removeMedia(req.params.eventId,req.params.kind)});
module.exports={list,detail,create,update,remove,schools,createSchool,uploadMedia,removeMedia};
