import React,{useEffect,useMemo,useState} from 'react';
import {useParams} from 'react-router-dom';
import {ArrowLeft,Check} from 'lucide-react';
import {listExams} from '../../../services/examService';
import {deleteExamEventMedia,getExamEvent,listExamEventSchools,updateExamEvent,uploadExamEventMedia} from '../../../services/examEventService';
import ExamEventFormSections from '../components/ExamEventFormSections';
import ExamPickerModal from '../components/ExamPickerModal';
import PublicExamAccessCard from '../components/PublicExamAccessCard';
import './ExamEventCreatePage.css';
import './ExamEventStitch.css';

const localDate=value=>value?new Date(new Date(value).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const plain=value=>String(value||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim();
export default function ExamEventEditPage({navigate,showMsg}){
  const {id}=useParams();const [form,setForm]=useState(null);const [schools,setSchools]=useState([]);const [exams,setExams]=useState([]);const [saving,setSaving]=useState(false);const [image,setImage]=useState(null);const [banner,setBanner]=useState(null);const [pickerOpen,setPickerOpen]=useState(false);
  useEffect(()=>{Promise.all([getExamEvent(id),listExamEventSchools(),listExams({limit:100})]).then(([event,schoolRows,examRows])=>{setForm({name:event.name||'',eventCode:event.eventCode||'',schoolIds:(event.schools||[]).map(school=>school.id),status:event.status||'DRAFT',description:event.description||'',startAt:localDate(event.startAt),endAt:localDate(event.endAt),examId:event.exam?.id||'',internalNote:event.internalNote||''});setImage(event.imageUrl?{url:event.imageUrl,persisted:true}:null);setBanner(event.bannerUrl?{url:event.bannerUrl,persisted:true}:null);setSchools(schoolRows||[]);setExams(examRows.data||[]);}).catch(error=>{showMsg?.(error.response?.data?.error||'Không thể tải thông tin kỳ thi.','error');navigate('/exam-events');});},[id,navigate,showMsg]);
  const selectedExam=useMemo(()=>exams.find(exam=>exam.id===form?.examId),[exams,form?.examId]);const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  const pick=(setter,current,file,maxMb)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return showMsg?.('Chỉ hỗ trợ ảnh JPG, PNG hoặc WEBP.','error');if(file.size>maxMb*1024*1024)return showMsg?.(`Ảnh không được vượt quá ${maxMb}MB.`,'error');if(current?.url&&!current.persisted)URL.revokeObjectURL(current.url);setter({file,url:URL.createObjectURL(file)});};
  const removeMedia=async(kind,setter,current)=>{if(!current)return;if(!current.persisted){if(current.url)URL.revokeObjectURL(current.url);setter(null);return;}try{await deleteExamEventMedia(id,kind);setter(null);showMsg?.(kind==='banner'?'Đã gỡ ảnh bìa kỳ thi.':'Đã xóa ảnh đại diện kỳ thi.','success');}catch(error){showMsg?.(error.response?.data?.error||'Không thể xóa ảnh. Vui lòng thử lại.','error');}};
  const submit=async event=>{event.preventDefault();if(!form.name.trim()||!form.schoolIds.length||!plain(form.description)||!form.examId||!form.startAt||!form.endAt)return showMsg?.('Vui lòng nhập đủ các trường bắt buộc.','error');if(new Date(form.endAt)<=new Date(form.startAt))return showMsg?.('Thời gian kết thúc phải sau thời gian bắt đầu.','error');setSaving(true);try{await updateExamEvent(id,{...form,startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString()});if(image?.file)await uploadExamEventMedia(id,'image',image.file);if(banner?.file)await uploadExamEventMedia(id,'banner',banner.file);showMsg?.('Đã cập nhật kỳ thi thành công.','success');navigate('/exam-events');}catch(error){showMsg?.(error.response?.data?.error||'Không thể cập nhật kỳ thi.','error');}finally{setSaving(false);}};
  if(!form)return <section className="event-create-page"><div className="event-edit-loading">Đang tải thông tin kỳ thi...</div></section>;
  return <><section className="event-create-page"><header><button type="button" onClick={()=>navigate('/exam-events')}><ArrowLeft/></button><span>Quản lý kỳ thi</span><i>/</i><strong>Cập nhật kỳ thi</strong></header><PublicExamAccessCard eventId={id} eventName={form.name} status={form.status} showMsg={showMsg}/><form onSubmit={submit}><ExamEventFormSections form={form} update={update} schools={schools} onSchoolCreated={school=>setSchools(current=>[...current.filter(item=>item.id!==school.id),school].sort((a,b)=>a.name.localeCompare(b.name,'vi')))} showMsg={showMsg} selectedExam={selectedExam} onOpenExamPicker={()=>setPickerOpen(true)} image={image} banner={banner} onPickImage={file=>pick(setImage,image,file,2)} onPickBanner={file=>pick(setBanner,banner,file,5)} onRemoveImage={()=>removeMedia('image',setImage,image)} onRemoveBanner={()=>removeMedia('banner',setBanner,banner)} isEdit/><footer><button type="button" onClick={()=>navigate('/exam-events')}>Hủy</button><button type="submit" disabled={saving}><Check/>{saving?'Đang lưu...':'Lưu thay đổi'}</button></footer></form></section><ExamPickerModal open={pickerOpen} exams={exams} selectedId={form.examId} onClose={()=>setPickerOpen(false)} onConfirm={examId=>{update('examId',examId);setPickerOpen(false);}}/></>;
}
