const db=require('../../config/db');
const map=r=>r&&({id:r.id,questionId:r.question_id,title:r.title,contentHtml:r.content_html,scriptHtml:r.script_html,translationHtml:r.translation_html,displayOrder:r.display_order,createdAt:r.created_at,updatedAt:r.updated_at});
async function list(questionId){const r=await db.query('SELECT * FROM question_bank_contents WHERE question_id=$1 ORDER BY display_order,id',[questionId]);return r.rows.map(map);}
async function find(id,questionId){const r=await db.query('SELECT * FROM question_bank_contents WHERE id=$1 AND question_id=$2',[id,questionId]);return map(r.rows[0]);}
async function create(questionId,data){const r=await db.query(`INSERT INTO question_bank_contents(question_id,title,content_html,script_html,translation_html,display_order) SELECT $1,$2,$3,$4,$5,COALESCE(MAX(display_order)+1,0) FROM question_bank_contents WHERE question_id=$1 RETURNING *`,[questionId,data.title.trim(),data.contentHtml||null,data.scriptHtml||null,data.translationHtml||null]);return map(r.rows[0]);}
async function update(id,questionId,data){const r=await db.query(`UPDATE question_bank_contents SET title=COALESCE($3,title),content_html=COALESCE($4,content_html),script_html=COALESCE($5,script_html),translation_html=COALESCE($6,translation_html),updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND question_id=$2 RETURNING *`,[id,questionId,data.title,data.contentHtml,data.scriptHtml,data.translationHtml]);return map(r.rows[0]);}
async function remove(id,questionId){const r=await db.query('DELETE FROM question_bank_contents WHERE id=$1 AND question_id=$2 RETURNING id',[id,questionId]);if(r.rows[0])await normalize(questionId);return r.rows[0]||null;}
async function normalize(questionId,client=db){await client.query(`WITH ordered AS (SELECT id,ROW_NUMBER() OVER(ORDER BY display_order,id)-1 n FROM question_bank_contents WHERE question_id=$1) UPDATE question_bank_contents c SET display_order=o.n,updated_at=CURRENT_TIMESTAMP FROM ordered o WHERE c.id=o.id`,[questionId]);}
async function reorder(questionId,ids){return db.transaction(async client=>{const found=await client.query('SELECT id FROM question_bank_contents WHERE question_id=$1',[questionId]);const expected=found.rows.map(r=>String(r.id)).sort();const received=ids.map(String).sort();if(expected.length!==received.length||expected.some((id,i)=>id!==received[i]))return false;for(let i=0;i<ids.length;i++)await client.query('UPDATE question_bank_contents SET display_order=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND question_id=$3',[i,ids[i],questionId]);return true;});}
module.exports={list,find,create,update,remove,reorder};
