const crypto=require('crypto');const HttpError=require('../../http/httpError');const db=require('../../config/db');const storage=require('../../services/storageService');
const allowed={IMAGE:['image/'],AUDIO:['audio/'],VIDEO:['video/']};
function hasMpegAudioFrame(buffer){const bytes=Buffer.from(buffer||[]);const limit=Math.min(bytes.length-3,4096);for(let i=0;i<limit;i++){const b1=bytes[i+1],b2=bytes[i+2];if(bytes[i]!==0xff||(b1&0xe0)!==0xe0)continue;const version=(b1>>3)&0x03,layer=(b1>>1)&0x03,bitrate=(b2>>4)&0x0f,sampleRate=(b2>>2)&0x03;if(version!==1&&layer!==0&&bitrate!==0&&bitrate!==15&&sampleRate!==3)return true;}return false;}
function hasSignature(buffer,type){const bytes=Buffer.from(buffer||[]),header=bytes.subarray(0,16);if(type==='AUDIO'){const isMp3=header.subarray(0,3).toString('ascii')==='ID3'||hasMpegAudioFrame(bytes);const isWav=header.subarray(0,4).toString('ascii')==='RIFF'&&header.subarray(8,12).toString('ascii')==='WAVE';return isMp3||isWav;}if(type==='VIDEO')return header.subarray(4,8).toString('ascii')==='ftyp';if(type==='IMAGE'){const isPng=header.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));const isJpeg=header[0]===0xff&&header[1]===0xd8&&header[2]===0xff;return isPng||isJpeg;}return false;}
function validate(file){if(!file?.buffer)throw new HttpError('File media là bắt buộc.',400,'MEDIA_FILE_REQUIRED');const type=Object.keys(allowed).find(k=>allowed[k].some(prefix=>String(file.mimetype).startsWith(prefix)));if(!type)throw new HttpError('Chỉ hỗ trợ ảnh, audio hoặc video.',400,'MEDIA_TYPE_INVALID');if(file.size>100*1024*1024)throw new HttpError('File vượt quá 100MB.',400,'MEDIA_TOO_LARGE');if(!hasSignature(file.buffer,type)){const header=Buffer.from(file.buffer).subarray(0,256).toString('utf8').trimStart().toLowerCase();if(header.startsWith('<!doctype html')||header.startsWith('<html'))throw new HttpError('Tệp đã chọn thực chất là một trang HTML được lưu với đuôi .mp3, không phải file âm thanh. Vui lòng tải lại file MP3/WAV gốc.',400,'MEDIA_FILE_IS_HTML');throw new HttpError('Nội dung tệp không đúng với định dạng media đã chọn. Vui lòng chọn file MP3/WAV, MP4/MOV hoặc JPG/PNG hợp lệ.',400,'MEDIA_FILE_CONTENT_INVALID');}return type;}
const targets={CONTENT:{table:'question_bank_contents',column:'content_id'},SUB_QUESTION:{table:'question_bank_sub_questions',column:'sub_question_id'},SAMPLE_ANSWER:{table:'question_bank_sample_answers',column:'sample_answer_id'}};
async function target(scope,id){const config=targets[scope];if(!config)throw new HttpError('Media scope không hợp lệ.',400,'MEDIA_SCOPE_INVALID');const join=scope==='SAMPLE_ANSWER'?' JOIN question_bank_sub_questions s ON s.id=t.sub_question_id ':'';const questionColumn=scope==='SAMPLE_ANSWER'?'s.question_id':'t.question_id';const r=await db.query(`SELECT t.id,${questionColumn} question_id,q.status question_status FROM ${config.table} t ${join} JOIN question_bank_questions q ON q.id=${questionColumn} WHERE t.id=$1`,[id]);if(!r.rows[0])throw new HttpError('Media target không tồn tại.',404,'MEDIA_TARGET_NOT_FOUND');return r.rows[0];}
async function upload(scope,id,file,userId){const type=validate(file);const config=targets[scope];const t=await target(scope,id);if(t.question_status==='ACTIVE')throw new HttpError('Hãy chuyển câu hỏi sang Dừng hoạt động trước khi thay đổi media.',409,'ACTIVE_QUESTION_LOCKED');const mediaId=crypto.randomUUID();const safe=String(file.originalname||'file').replace(/[^a-zA-Z0-9._-]/g,'_');const key=`question-bank/${t.question_id}/${scope.toLowerCase()}/${id}/${mediaId}-${safe}`;const isDevelopment=process.env.NODE_ENV!=='production'&&process.env.APP_ENV!=='production';const storedKey=await storage.uploadBuffer(file.buffer,key,file.mimetype,{preferLocal:isDevelopment});try{const r=await db.query(`INSERT INTO question_bank_media(question_id,${config.column},media_type,original_name,storage_key,mime_type,file_size,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[t.question_id,id,type,file.originalname,storedKey,file.mimetype,file.size,userId||null]);const url=await storage.getSignedUrl(storedKey).catch(()=>null);return publicMedia(r.rows[0],url);}catch(e){await storage.deleteFile(storedKey).catch(()=>{});throw e;}}
function publicMedia(r,url=null){return{id:r.id,questionId:r.question_id,contentId:r.content_id||null,subQuestionId:r.sub_question_id||null,sampleAnswerId:r.sample_answer_id||null,mediaType:r.media_type,originalName:r.original_name,mimeType:r.mime_type,fileSize:Number(r.file_size||0),url};}
async function list(scope,id){const config=targets[scope];await target(scope,id);const r=await db.query(`SELECT * FROM question_bank_media WHERE ${config.column}=$1 ORDER BY created_at`,[id]);return Promise.all(r.rows.map(async m=>publicMedia(m,await storage.getSignedUrl(m.storage_key).catch(()=>null))));}
async function remove(id){const found=await db.query('SELECT m.*,q.status question_status FROM question_bank_media m JOIN question_bank_questions q ON q.id=m.question_id WHERE m.id=$1',[id]);if(!found.rows[0])throw new HttpError('Không tìm thấy media.',404,'MEDIA_NOT_FOUND');if(found.rows[0].question_status==='ACTIVE')throw new HttpError('Hãy chuyển câu hỏi sang Dừng hoạt động trước khi xóa media.',409,'ACTIVE_QUESTION_LOCKED');const r=await db.query('DELETE FROM question_bank_media WHERE id=$1 RETURNING *',[id]);await storage.deleteFile(r.rows[0].storage_key).catch(()=>{});return{id};}
async function url(id){const r=await db.query('SELECT storage_key FROM question_bank_media WHERE id=$1',[id]);if(!r.rows[0])throw new HttpError('Không tìm thấy media.',404,'MEDIA_NOT_FOUND');return storage.getSignedUrl(r.rows[0].storage_key);}
module.exports={upload,list,remove,url,validate,hasSignature};
