const HttpError = require('../../http/httpError');
const repo = require('./questionRepository');
const subQuestions = require('./subQuestionRepository');
const contents = require('./contentRepository');
const { validate } = require('./subQuestionService');
const { validateQuestionInput, ALLOWED_STATUS, ALLOWED_TYPES, UUID_PATTERN } = require('./questionValidator');
const db = require('../../config/db');

async function ensureGroup(id, requireActive = false) {
  const r = await db.query('SELECT id,status FROM question_groups WHERE id=$1', [id]);
  if (!r.rows[0]) throw new HttpError('Nhóm câu hỏi không tồn tại.', 404, 'GROUP_NOT_FOUND');
  if (requireActive && r.rows[0].status !== 'ACTIVE') throw new HttpError('Chỉ có thể kích hoạt câu hỏi thuộc nhóm đang hoạt động.', 409, 'QUESTION_GROUP_NOT_ACTIVE');
  return r.rows[0];
}

// Activation requires at least one content and at least one sub-question, and
// every sub-question must satisfy the rules of the parent question type.
async function ensureReady(id, question) {
  const contentItems = await contents.list(id);
  if (!contentItems.length) throw new HttpError('Câu hỏi cần có ít nhất một nội dung trước khi kích hoạt.', 400, 'QUESTION_CONTENT_REQUIRED');
  const items = await subQuestions.list(id);
  if (!items.length) throw new HttpError('Câu hỏi chưa có câu hỏi con.', 400, 'QUESTION_NOT_READY');
  for (const item of items) validate(item, question.questionType);
}

async function create(data, userId) {
  validateQuestionInput(data);
  await ensureGroup(data.groupId);
  // Business code is generated by the backend; ignore any client-provided code.
  return repo.create({ questionName: data.questionName, groupId: data.groupId, questionType: data.questionType, note: data.note }, userId);
}

async function get(id) {
  const q = await repo.findById(id);
  if (!q) throw new HttpError('Không tìm thấy câu hỏi.', 404, 'QUESTION_NOT_FOUND');
  return q;
}

async function update(id, data, userId) {
  const current = await get(id);
  if (data.questionType !== undefined && data.questionType !== current.questionType) {
    throw new HttpError('Không thể thay đổi loại câu hỏi sau khi đã tạo.', 400, 'QUESTION_TYPE_IMMUTABLE');
  }
  validateQuestionInput(data, true);
  const targetGroupId = data.groupId || current.groupId;
  const targetStatus = data.status || current.status;
  if (data.groupId) await ensureGroup(data.groupId);
  if (targetStatus === 'ACTIVE') {
    await ensureGroup(targetGroupId, true);
    await ensureReady(id, current);
  }
  // Never forward code or questionType to the repository update.
  const { code, questionType, ...allowed } = data;
  return repo.update(id, allowed, userId);
}

async function remove(id) {
  const question = await get(id);
  if (question.status === 'ACTIVE') throw new HttpError('Hãy ngừng hoạt động câu hỏi trước khi xóa.', 409, 'ACTIVE_QUESTION_DELETE_FORBIDDEN');
  const used = await db.query('SELECT 1 FROM exam_part_questions WHERE question_id=$1 LIMIT 1', [id]);
  if (used.rows[0]) throw new HttpError('Không thể xóa câu hỏi đang được sử dụng trong đề thi.', 409, 'QUESTION_IN_USE');
  const versioned = await db.query(
    `SELECT 1 FROM exam_versions
     WHERE jsonb_path_exists(snapshot, '$.parts[*].questions[*] ? (@.id == $questionId)', jsonb_build_object('questionId', to_jsonb($1::text)))
     LIMIT 1`,
    [id],
  );
  if (versioned.rows[0]) throw new HttpError('Không thể xóa câu hỏi đã được lưu trong phiên bản đề thi.', 409, 'QUESTION_IN_VERSION');
  return repo.remove(id);
}

function values(value) {
  if (Array.isArray(value)) return value.flatMap(values);
  return String(value || '').split(',').map(item => item.trim()).filter(Boolean);
}

function validateFilters(query = {}) {
  const groupIds = values(query.groupIds);
  if (groupIds.some(id => !UUID_PATTERN.test(id))) throw new HttpError('Bộ lọc nhóm câu hỏi không hợp lệ.', 400, 'GROUP_IDS_INVALID');
  const questionTypes = values(query.questionTypes);
  if (questionTypes.some(type => !ALLOWED_TYPES.has(type))) throw new HttpError('Bộ lọc loại câu hỏi không hợp lệ.', 400, 'QUESTION_TYPES_INVALID');
  const statuses = values(query.statuses);
  if (statuses.some(status => !ALLOWED_STATUS.has(status))) throw new HttpError('Bộ lọc trạng thái không hợp lệ.', 400, 'STATUSES_INVALID');
}

async function list(query) { validateFilters(query); return repo.list(query); }
async function filterOptions(query) { validateFilters(query); return repo.filterOptions(query); }

module.exports = { list, filterOptions, create, get, update, remove, validateFilters };
