const db=require('../../config/db');
const map=r=>r&&({id:r.id,questionId:r.question_id,contentId:r.content_id,promptHtml:r.prompt_html,hint:r.hint,explanation:r.explanation,note:r.note,instructionHtml:r.instruction_html,sentenceStartersHtml:r.sentence_starters_html,preparationDurationSeconds:r.preparation_duration_seconds,recordingDurationSeconds:r.recording_duration_seconds,maxCharacterCount:r.max_character_count,minWordCount:r.min_word_count,maxWordCount:r.max_word_count,displayOrder:r.display_order,createdAt:r.created_at,updatedAt:r.updated_at});
const mapOption=r=>({id:r.id,subQuestionId:r.sub_question_id,optionKey:r.option_key,optionText:r.option_text,isCorrect:r.is_correct,displayOrder:r.display_order});
async function list(questionId){const qs=await db.query('SELECT * FROM question_bank_sub_questions WHERE question_id=$1 ORDER BY display_order,id',[questionId]);if(!qs.rows.length)return[];const ids=qs.rows.map(r=>r.id);const os=await db.query('SELECT * FROM question_bank_sub_question_options WHERE sub_question_id=ANY($1::uuid[]) ORDER BY display_order,id',[ids]);const tags=await db.query('SELECT st.sub_question_id,t.id,t.name FROM question_bank_sub_question_tags st JOIN question_bank_tags t ON t.id=st.tag_id WHERE st.sub_question_id=ANY($1::uuid[])',[ids]);const samples=await db.query('SELECT * FROM question_bank_sample_answers WHERE sub_question_id=ANY($1::uuid[]) ORDER BY display_order,id',[ids]);return qs.rows.map(r=>({...map(r),options:os.rows.filter(o=>o.sub_question_id===r.id).map(mapOption),tags:tags.rows.filter(t=>t.sub_question_id===r.id).map(t=>({id:t.id,name:t.name})),sampleAnswers:samples.rows.filter(s=>s.sub_question_id===r.id).map(s=>({id:s.id,answerHtml:s.answer_html,displayOrder:s.display_order}))}));}
async function find(questionId,id){return (await list(questionId)).find(item=>item.id===id)||null;}
async function create(questionId,data){return db.transaction(async c=>{const q=await c.query(`INSERT INTO question_bank_sub_questions(question_id,content_id,prompt_html,hint,explanation,note,instruction_html,sentence_starters_html,preparation_duration_seconds,recording_duration_seconds,max_character_count,min_word_count,max_word_count,display_order) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,COALESCE(MAX(display_order)+1,0) FROM question_bank_sub_questions WHERE question_id=$1 RETURNING *`,[questionId,data.contentId||null,data.promptHtml.trim(),data.hint||null,data.explanation||null,data.note||null,data.instructionHtml||null,data.sentenceStartersHtml||null,data.preparationDurationSeconds||null,data.recordingDurationSeconds||null,data.maxCharacterCount||null,data.minWordCount||null,data.maxWordCount||data.minWordCount||null]);const id=q.rows[0].id;await syncOptions(c,id,data.options||[]);await syncSamples(c,id,data.sampleAnswers||[]);await syncTags(c,id,data.tags||[]);return id;});}
async function update(questionId,id,data){return db.transaction(async c=>{const q=await c.query(`UPDATE question_bank_sub_questions SET content_id=COALESCE($3,content_id),prompt_html=COALESCE($4,prompt_html),hint=$5,explanation=$6,note=$7,instruction_html=$8,sentence_starters_html=$9,preparation_duration_seconds=$10,recording_duration_seconds=$11,max_character_count=$12,min_word_count=$13,max_word_count=$14,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND question_id=$2 RETURNING id`,[id,questionId,data.contentId,data.promptHtml,data.hint||null,data.explanation||null,data.note||null,data.instructionHtml||null,data.sentenceStartersHtml||null,data.preparationDurationSeconds||null,data.recordingDurationSeconds||null,data.maxCharacterCount||null,data.minWordCount||null,data.maxWordCount||data.minWordCount||null]);if(!q.rows[0])return false;await syncOptions(c,id,data.options||[]);await syncSamples(c,id,data.sampleAnswers||[]);await syncTags(c,id,data.tags||[]);return true;});}
async function syncOptions(c,id,options){await c.query('DELETE FROM question_bank_sub_question_options WHERE sub_question_id=$1',[id]);for(let i=0;i<options.length;i++)await c.query('INSERT INTO question_bank_sub_question_options(sub_question_id,option_key,option_text,is_correct,display_order) VALUES($1,$2,$3,$4,$5)',[id,options[i].optionKey||String.fromCharCode(65+i),options[i].optionText.trim(),!!options[i].isCorrect,i]);}
async function syncSamples(c,id,samples){const existing=await c.query('SELECT id FROM question_bank_sample_answers WHERE sub_question_id=$1',[id]);const keep=[];for(let i=0;i<samples.length;i++){const sample=samples[i];if(sample.id&&existing.rows.some(row=>row.id===sample.id)){await c.query('UPDATE question_bank_sample_answers SET answer_html=$1,display_order=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND sub_question_id=$4',[sample.answerHtml.trim(),i,sample.id,id]);keep.push(sample.id);}else{const inserted=await c.query('INSERT INTO question_bank_sample_answers(sub_question_id,answer_html,display_order) VALUES($1,$2,$3) RETURNING id',[id,sample.answerHtml.trim(),i]);keep.push(inserted.rows[0].id);}}if(keep.length)await c.query('DELETE FROM question_bank_sample_answers WHERE sub_question_id=$1 AND NOT(id=ANY($2::uuid[]))',[id,keep]);else await c.query('DELETE FROM question_bank_sample_answers WHERE sub_question_id=$1',[id]);}
async function syncTags(c,id,names){await c.query('DELETE FROM question_bank_sub_question_tags WHERE sub_question_id=$1',[id]);for(const raw of names){const name=String(raw.name||raw).trim();if(!name)continue;const t=await c.query('INSERT INTO question_bank_tags(name) VALUES($1) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id',[name]);await c.query('INSERT INTO question_bank_sub_question_tags(sub_question_id,tag_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,t.rows[0].id]);}}
async function remove(questionId,id){const r=await db.query('DELETE FROM question_bank_sub_questions WHERE id=$1 AND question_id=$2 RETURNING id',[id,questionId]);return r.rows[0]||null;}
async function reorder(questionId,ids){return db.transaction(async c=>{const rows=await c.query('SELECT id FROM question_bank_sub_questions WHERE question_id=$1',[questionId]);const expected=rows.rows.map(r=>String(r.id)).sort(),got=ids.map(String).sort();if(expected.length!==got.length||expected.some((id,i)=>id!==got[i]))return false;for(let i=0;i<ids.length;i++)await c.query('UPDATE question_bank_sub_questions SET display_order=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND question_id=$3',[i,ids[i],questionId]);return true;});}
module.exports={list,find,create,update,remove,reorder};
