import React, { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, ChevronRight, Menu, X } from 'lucide-react';
import './advanced-display.css';

export function Listbox({ options = [], value, onChange, multiple = false }) { return <div className="ui-listbox" role="listbox" aria-multiselectable={multiple}>{options.map(option => { const active = multiple ? value?.includes(option.value) : value === option.value; return <button type="button" role="option" aria-selected={active} className={active ? 'is-selected' : ''} key={option.value} onClick={() => onChange?.(multiple ? (active ? value.filter(item => item !== option.value) : [...(value || []), option.value]) : option.value)}><span>{option.label}</span>{active && <Check />}</button>; })}</div>; }

export function DropdownMenu({ trigger = <Menu />, items = [] }) { const [open, setOpen] = useState(false); const root = useRef(null); useEffect(() => { if (!open) return undefined; const close = event => { if (!root.current?.contains(event.target)) setOpen(false); }; const escape = event => event.key === 'Escape' && setOpen(false); document.addEventListener('mousedown', close); document.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', escape); }; }, [open]); return <div ref={root} className="ui-dropdown-menu"><button type="button" onClick={() => setOpen(!open)}>{trigger}<ChevronDown /></button>{open && <div className="ui-dropdown-menu__content">{items.map(item => <button type="button" key={item.label} disabled={item.disabled} className={item.danger ? 'is-danger' : ''} onClick={() => { item.onClick?.(); setOpen(false); }}>{item.icon}{item.label}</button>)}</div>}</div>; }

export function TreeMenu({ items = [], selectedKey, onSelect }) { return <div className="ui-tree-menu">{items.map(item => <TreeItem key={item.key} item={item} selectedKey={selectedKey} onSelect={onSelect} />)}</div>; }
function TreeItem({ item, selectedKey, onSelect }) { const [open, setOpen] = useState(item.open); const hasChildren = item.children?.length; return <div><button type="button" className={`ui-tree-item${selectedKey === item.key ? ' is-selected' : ''}`} onClick={() => { onSelect?.(item.key); if (hasChildren) setOpen(!open); }}>{hasChildren ? (open ? <ChevronDown /> : <ChevronRight />) : <span className="ui-tree-spacer" />}{item.icon}{item.label}</button>{open && hasChildren && <div className="ui-tree-children">{item.children.map(child => <TreeItem key={child.key} item={child} selectedKey={selectedKey} onSelect={onSelect} />)}</div>}</div>; }

export function Panel({ title, actions, children, collapsible = false }) { const [open, setOpen] = useState(true); return <section className="ui-panel"><header><button type="button" className={collapsible ? '' : 'is-static'} onClick={() => collapsible && setOpen(!open)}>{collapsible && (open ? <ChevronDown /> : <ChevronRight />)}<strong>{title}</strong></button>{actions}</header>{open && <div className="ui-panel__body">{children}</div>}</section>; }
export function Fieldset({ legend, children }) { return <fieldset className="ui-fieldset"><legend>{legend}</legend>{children}</fieldset>; }

export function Drawer({ open, title, placement = 'right', onClose, children, footer }) { useEffect(() => { if (!open) return undefined; const escape = event => event.key === 'Escape' && onClose?.(); document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape); }, [open, onClose]); if (!open) return null; return <div className="ui-drawer-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose?.()}><aside className={`ui-drawer ui-drawer--${placement}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Đóng"><X /></button></header><div className="ui-drawer__body">{children}</div>{footer && <footer>{footer}</footer>}</aside></div>; }

export function Rating({ value = 0, max = 5, onChange, readonly = false }) { return <div className="ui-rating" role="group" aria-label="Đánh giá">{Array.from({ length: max }, (_, index) => <button type="button" key={index} className={index < value ? 'is-active' : ''} disabled={readonly} onClick={() => onChange?.(index + 1)} aria-label={`${index + 1} sao`}>★</button>)}</div>; }
export function Slider({ value = 0, min = 0, max = 100, step = 1, onChange, disabled = false }) { return <div className="ui-slider"><input type="range" min={min} max={max} step={step} value={value} disabled={disabled} onChange={event => onChange?.(Number(event.target.value))} /><output>{value}</output></div>; }
