import React, { useState } from 'react';
import { Edit, Eye, Plus, Trash2, MoreVertical, Search, ChevronDown } from 'lucide-react';
import Button, { IconButton } from './Button';
import Badge from './Badge';
import Chip from './Chip';
import { FormField, Input, Select, Textarea } from './FormField';
import { Checkbox, Combobox, MultiSelect, RadioGroup, Switch } from './AdvancedForm';
import { DataTable, Pagination, TableActions } from './DataTable';
import { Alert, Accordion, ConfirmDialog, Modal, Toast, ConfirmPopup, OverlayPanel, Popover, Tooltip } from './Feedback';
import { CalendarPopup, DatePicker, DateRangePicker, DateTimePicker, TimePicker } from './DateTime';
import { MediaGallery } from './MediaUpload';
import { Listbox, DropdownMenu, TreeMenu, Panel, Fieldset, Drawer, Rating, Slider } from './AdvancedDisplay';
import { Breadcrumb, PageHeader } from './Layout';
import './showcase.css';

const options = [{ value: 'reading', label: 'Reading' }, { value: 'listening', label: 'Listening' }];

export default function ComponentShowcasePage() {
  const [modal, setModal] = useState(false); const [confirm, setConfirm] = useState(false); const [popup, setPopup] = useState(false); const [overlay, setOverlay] = useState(false); const [drawer, setDrawer] = useState(false); const [toast, setToast] = useState(false); const [date, setDate] = useState(''); const [calendar, setCalendar] = useState(false); const [range, setRange] = useState({ startDate: '', endDate: '' }); const [selected, setSelected] = useState([]); const [listValue, setListValue] = useState('reading'); const [rating, setRating] = useState(4); const [slider, setSlider] = useState(60); const popupButton = React.useRef(null); const overlayButton = React.useRef(null);
  const rows = [{ id: 1, title: 'TOEIC_COMPACT450_U02_L1_Video_01', code: 'QT - KUSYEH', type: 'Dạng 3: MCQ', group: 'TOEIC Compact 450 +', count: 3, version: '1.0', updated: '17/02/2026 - 17:29', status: 'Dừng hoạt động' }, { id: 2, title: 'TOEIC_COMPACT450_U02_L1_Video_01', code: 'QT - KUSYEH', type: 'Dạng 1: Video tương tác', group: 'TOEIC Compact 450 +', count: 3, version: '1.0', updated: '17/02/2026 - 17:29', status: 'Nháp' }, { id: 3, title: 'TOEIC_COMPACT450_U02_L1_Video_01', code: 'QT - KUSYEH', type: 'Dạng 5: Nhận diện phát âm', group: 'TOEIC Compact 450 +', count: 3, version: '1.0', updated: '17/02/2026 - 17:29', status: 'Đang hoạt động' }];
  const statusTone = status => status === 'Đang hoạt động' ? 'success' : status === 'Dừng hoạt động' ? 'warning' : 'neutral';
  return <div className="ui-showcase"><div className="ui-showcase__business-header"><Breadcrumb items={[{ label: 'Ngân hàng câu hỏi', href: '#' }, { label: 'Danh sách ngân hàng câu hỏi', current: true }]} /><div><Button icon={<Plus />}>Thêm mới</Button><IconButton aria-label="Thêm thao tác"><MoreVertical /></IconButton></div></div><PageHeader horizontal eyebrow="DESIGN SYSTEM" title="Component Showcase" description="Kiểm thử component theo thiết kế Figma trước khi tích hợp vào màn nghiệp vụ." actions={<Button icon={<Plus />} onClick={() => setToast(true)}>Thông báo</Button>} />
    <section className="ui-showcase__question-table"><div className="ui-showcase__table-toolbar"><label><Search /><input placeholder="Tìm kiếm" /></label><Button variant="outline">TOEIC Compact 450+ <span>×</span></Button><Button variant="outline">Dạng câu hỏi <ChevronDown /></Button><Button variant="outline">Phân loại (Tag) <ChevronDown /></Button><Button variant="outline">Trạng thái <ChevronDown /></Button></div><DataTable columns={[{ key: 'title', label: 'Tên câu hỏi' }, { key: 'code', label: 'Mã câu hỏi' }, { key: 'type', label: 'Dạng câu hỏi' }, { key: 'group', label: 'Nhóm câu hỏi' }, { key: 'count', label: 'Số câu hỏi' }, { key: 'version', label: 'Phiên bản' }, { key: 'updated', label: 'Ngày cập nhật' }, { key: 'status', label: 'Trạng thái', render: row => <Badge tone={statusTone(row.status)}>{row.status}<ChevronDown /></Badge> }, { key: 'actions', label: 'Thao tác', render: () => <TableActions actions={[{ label: 'Xem', icon: <Eye /> }, { label: 'Sửa', icon: <Edit /> }, { label: 'Xóa', icon: <Trash2 />, danger: true }]} /> }]} data={rows} selectable /><Pagination page={1} pageSize={10} total={2000} /></section>
    <section><h2>Button, Badge & Chip</h2><div className="ui-showcase__row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="danger" icon={<Trash2 />}>Danger</Button><IconButton aria-label="Xem"><Eye /></IconButton><Badge tone="success">Hoạt động</Badge><Badge tone="warning">Bản nháp</Badge><Chip removable onRemove={() => {}}>Reading</Chip></div></section>
    <section><h2>Form controls</h2><div className="ui-showcase__grid"><FormField label="Tên câu hỏi" required><Input placeholder="Nhập tên câu hỏi" /></FormField><FormField label="Loại câu hỏi"><Select defaultValue=""><option value="" disabled>Chọn loại</option><option>MCQ</option><option>Writing</option></Select></FormField><FormField label="Ghi chú"><Textarea placeholder="Nhập ghi chú" /></FormField><FormField label="Nhóm"><Combobox options={options} placeholder="Chọn nhóm" /></FormField><FormField label="Tags"><MultiSelect options={options} placeholder="Chọn tags" selectAll /></FormField><div className="ui-showcase__stack"><Checkbox label="Đáp án đúng" checked onChange={() => {}} /><RadioGroup options={options} value="reading" onChange={() => {}} /><Switch label="Hoạt động" checked onChange={() => {}} /></div></div></section>
    <section><h2>Dropdown, popup & Date/Time</h2><div className="ui-showcase__grid"><FormField label="Dropdown / Combobox"><Combobox options={options} placeholder="Bấm để mở dropdown" /></FormField><FormField label="MultiSelect"><MultiSelect options={options} placeholder="Bấm để mở multi-select" selectAll /></FormField><div className="ui-showcase__popup-demo"><Button ref={popupButton} variant="secondary" onClick={() => setPopup(!popup)}>Confirm Popup</Button><ConfirmPopup open={popup} anchorRef={popupButton} message="Bạn có chắc muốn tiếp tục?" onCancel={() => setPopup(false)} onConfirm={() => setPopup(false)} /></div><div className="ui-showcase__popup-demo"><Button ref={overlayButton} variant="secondary" onClick={() => setOverlay(!overlay)}>Overlay Panel</Button><OverlayPanel open={overlay} anchorRef={overlayButton} onClose={() => setOverlay(false)}><strong>Nội dung Overlay</strong><p>Panel nổi theo vị trí trigger.</p></OverlayPanel></div><div className="ui-showcase__calendar-demo"><Button variant="secondary" onClick={() => setCalendar(!calendar)}>Calendar Popup</Button>{calendar && <CalendarPopup open value={date} onChange={value => { setDate(value); setCalendar(false); }} onClose={() => setCalendar(false)} />}</div><DatePicker label="Ngày bắt đầu" value={date} onChange={setDate} /><DateRangePicker label="Khoảng thời gian" {...range} onChange={setRange} /><TimePicker label="Giờ bắt đầu" /><DateTimePicker label="Ngày giờ" /></div></section>
    <section><h2>Table & pagination</h2><DataTable columns={[{ key: 'title', label: 'Tiêu đề' }, { key: 'skill', label: 'Kỹ năng' }, { key: 'status', label: 'Trạng thái', render: row => <Badge tone={row.status === 'Hoạt động' ? 'success' : 'warning'}>{row.status}</Badge> }, { key: 'actions', label: 'Hành động', render: () => <TableActions actions={[{ label: 'Xem', icon: <Eye /> }, { label: 'Sửa', icon: <Edit /> }, { label: 'Xóa', icon: <Trash2 />, danger: true }]} /> }]} data={rows} selectable selectedRowKeys={selected} onSelectionChange={setSelected} /><Pagination page={1} pageSize={10} total={21} onPageChange={() => {}} /></section>
    <section><h2>Navigation, display & interaction</h2><div className="ui-showcase__grid"><div><h3>Listbox</h3><Listbox options={options} value={listValue} onChange={setListValue} /></div><div><h3>Dropdown menu</h3><DropdownMenu trigger={<><Plus /> Tùy chọn</>} items={[{ label: 'Sửa câu hỏi', icon: <Edit /> }, { label: 'Xóa câu hỏi', icon: <Trash2 />, danger: true }]} /></div><div><h3>Tree menu</h3><TreeMenu selectedKey="content" items={[{ key: 'question', label: 'Question Bank', open: true, children: [{ key: 'content', label: 'Content' }, { key: 'sub', label: 'Câu hỏi con' }] }]} /></div><Panel title="Panel có thể thu gọn" collapsible actions={<Badge tone="info">Demo</Badge>}><p>Panel dùng cho các nhóm nội dung có thể mở rộng hoặc thu gọn.</p></Panel><Fieldset legend="Fieldset"><Input placeholder="Trường trong fieldset" /></Fieldset><div><h3>Rating</h3><Rating value={rating} onChange={setRating} /></div><div><h3>Slider</h3><Slider value={slider} onChange={setSlider} /></div><Button onClick={() => setDrawer(true)}>Mở Drawer</Button></div></section>
    <section><h2>Feedback, tooltip & media</h2><div className="ui-showcase__row"><Button onClick={() => setModal(true)}>Mở Modal</Button><Button variant="danger" onClick={() => setConfirm(true)}>Confirm Dialog</Button><Tooltip content="Tooltip mẫu"><IconButton aria-label="Tooltip"><Eye /></IconButton></Tooltip><Popover open trigger={<Button variant="ghost">Popover</Button>}>Nội dung Popover</Popover><Alert severity="info" title="Thông tin">Đây là alert mẫu.</Alert></div><Accordion items={[{ key: 'one', label: 'Accordion item', content: 'Nội dung accordion.' }]} /><h3>Media preview</h3><MediaGallery items={[{ id: 'demo-image', type: 'IMAGE', originalName: 'preview-image.png', url: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=640' }, { id: 'demo-audio', type: 'AUDIO', originalName: 'audio.mp3', url: 'https://www.w3schools.com/html/horse.mp3' }, { id: 'demo-video', type: 'VIDEO', originalName: 'video.mp4', url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4' }]} /></section>
    <Modal open={modal} title="Modal mẫu" onClose={() => setModal(false)} footer={<><Button variant="secondary" onClick={() => setModal(false)}>Hủy</Button><Button onClick={() => setModal(false)}>Lưu</Button></>}><p>Nội dung modal theo design system.</p></Modal><ConfirmDialog open={confirm} title="Xóa dữ liệu?" message="Thao tác này không thể hoàn tác." severity="danger" onCancel={() => setConfirm(false)} onConfirm={() => setConfirm(false)} /><>{toast && <Toast severity="success" title="Thành công" onClose={() => setToast(false)} autoClose={3000}>Đã hiển thị toast mẫu.</Toast>}</>
    <Drawer open={drawer} title="Bộ lọc nâng cao" onClose={() => setDrawer(false)} footer={<Button onClick={() => setDrawer(false)}>Áp dụng</Button>}><p>Nội dung Drawer và khu vực hành động cuối panel.</p></Drawer>
  </div>;
}
