const db=require('../../config/db');
const HttpError=require('../../http/httpError');
const repo=require('./examRepository');
const {validateExam,validatePart}=require('./examValidator');

async function get(id,client){const exam=await repo.findById(id,client);if(!exam)throw new HttpError('Không tìm thấy đề thi.',404,'EXAM_NOT_FOUND');return exam;}
async function create(data,userId){validateExam(data);if(data.status==='ACTIVE')throw new HttpError('Hãy tạo bản nháp rồi dùng thao tác kích hoạt.',400,'USE_ACTIVATE_ENDPOINT');return repo.create(data,userId);}
async function ensureEditable(id,client){const exam=await get(id,client);if(exam.status==='ACTIVE')throw new HttpError('Hãy ngừng hoạt động đề thi trước khi chỉnh sửa.',409,'ACTIVE_EXAM_LOCKED');return exam;}
async function update(id,data,userId){await ensureEditable(id);validateExam(data,true);if(data.status==='ACTIVE')throw new HttpError('Hãy dùng thao tác kích hoạt để xuất bản đề.',400,'USE_ACTIVATE_ENDPOINT');return repo.update(id,data,userId);}
async function remove(id){const exam=await get(id);if(exam.status==='ACTIVE')throw new HttpError('Không thể xóa đề thi đang hoạt động.',409,'ACTIVE_EXAM_DELETE_FORBIDDEN');const used=await db.query('SELECT 1 FROM exam_events WHERE exam_id=$1 LIMIT 1',[id]);if(used.rows[0])throw new HttpError('Không thể xóa đề thi đang được sử dụng trong kỳ thi. Hãy đổi đề áp dụng hoặc xóa kỳ thi liên quan trước.',409,'EXAM_IN_USE');await repo.remove(id);}
async function duplicate(id,userId){await get(id);return repo.duplicate(id,userId);}

async function addPart(examId,data){validatePart(data);await ensureEditable(examId);return db.transaction(async client=>{const order=await client.query('SELECT COALESCE(MAX(display_order),-1)+1 value,COALESCE(MAX(part_number),0)+1 number FROM exam_parts WHERE exam_id=$1',[examId]);await client.query('INSERT INTO exam_parts(exam_id,part_number,title,duration_minutes,part_label,instruction,display_order) VALUES($1,$2,$3,$4,$5,$6,$7)',[examId,order.rows[0].number,data.title.trim(),Number(data.durationMinutes||0),String(data.partLabel||'').trim()||null,String(data.instruction||'').trim()||null,order.rows[0].value]);return get(examId,client);});}
async function updatePart(examId,partId,data){validatePart(data);await ensureEditable(examId);await ensurePart(examId,partId);await db.query('UPDATE exam_parts SET title=$3,duration_minutes=$4,part_label=$5,instruction=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND exam_id=$2',[partId,examId,data.title.trim(),Number(data.durationMinutes||0),String(data.partLabel||'').trim()||null,String(data.instruction||'').trim()||null]);return get(examId);}
async function removePart(examId,partId){await ensureEditable(examId);await ensurePart(examId,partId);await db.query('DELETE FROM exam_parts WHERE id=$1 AND exam_id=$2',[partId,examId]);return get(examId);}
async function ensurePart(examId,partId,client=db){const r=await client.query('SELECT id FROM exam_parts WHERE id=$1 AND exam_id=$2',[partId,examId]);if(!r.rows[0])throw new HttpError('Phần thi không thuộc đề thi này.',404,'PART_NOT_FOUND');return r.rows[0];}
async function reorderParts(examId,ids){await ensureEditable(examId);return db.transaction(async client=>{const current=await client.query('SELECT id FROM exam_parts WHERE exam_id=$1',[examId]);assertSameIds(current.rows.map(r=>r.id),ids,'Danh sách phần sắp xếp không hợp lệ.');await client.query('UPDATE exam_parts SET display_order=display_order+$2,part_number=part_number+$2 WHERE exam_id=$1',[examId,ids.length+1]);for(let i=0;i<ids.length;i++)await client.query('UPDATE exam_parts SET display_order=$3,part_number=$3+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND exam_id=$2',[ids[i],examId,i]);return get(examId,client);});}

async function addQuestions(examId,partId,questionIds){if(!Array.isArray(questionIds)||!questionIds.length)throw new HttpError('Vui lòng chọn ít nhất một câu hỏi.',400,'QUESTIONS_REQUIRED');return db.transaction(async client=>{await ensureEditable(examId,client);await ensurePart(examId,partId,client);const unique=[...new Set(questionIds)];if(unique.length!==questionIds.length)throw new HttpError('Danh sách câu hỏi bị trùng.',400,'DUPLICATE_QUESTIONS');const valid=await client.query(`SELECT q.id,COUNT(s.id)::int child_count FROM question_bank_questions q LEFT JOIN question_bank_sub_questions s ON s.question_id=q.id WHERE q.id=ANY($1::uuid[]) AND q.status='ACTIVE' GROUP BY q.id`,[unique]);if(valid.rows.length!==unique.length||valid.rows.some(q=>q.child_count<1))throw new HttpError('Câu hỏi phải đang hoạt động và có ít nhất một câu hỏi con.',400,'QUESTION_NOT_READY');const used=await client.query('SELECT question_id FROM exam_part_questions WHERE exam_id=$1 AND question_id=ANY($2::uuid[])',[examId,unique]);if(used.rows.length)throw new HttpError('Một hoặc nhiều câu hỏi đã có trong đề thi.',409,'QUESTION_ALREADY_ADDED');const max=await client.query('SELECT COALESCE(MAX(display_order),-1) value FROM exam_part_questions WHERE part_id=$1',[partId]);let order=Number(max.rows[0].value)+1;for(const questionId of unique)await client.query('INSERT INTO exam_part_questions(exam_id,part_id,question_id,display_order,points) VALUES($1,$2,$3,$4,10)',[examId,partId,questionId,order++]);return get(examId,client);});}
async function listAvailableQuestions(examId,filters){await get(examId);return repo.listAvailableQuestions(examId,filters);}
async function removeQuestion(examId,partId,questionId){await ensureEditable(examId);await ensurePart(examId,partId);const r=await db.query('DELETE FROM exam_part_questions WHERE exam_id=$1 AND part_id=$2 AND question_id=$3 RETURNING id',[examId,partId,questionId]);if(!r.rows[0])throw new HttpError('Câu hỏi không có trong phần thi.',404,'EXAM_QUESTION_NOT_FOUND');return get(examId);}
async function reorderQuestions(examId,partId,ids){await ensureEditable(examId);await ensurePart(examId,partId);return db.transaction(async client=>{const current=await client.query('SELECT question_id id FROM exam_part_questions WHERE part_id=$1',[partId]);assertSameIds(current.rows.map(r=>r.id),ids,'Danh sách câu hỏi sắp xếp không hợp lệ.');for(let i=0;i<ids.length;i++)await client.query('UPDATE exam_part_questions SET display_order=$4 WHERE exam_id=$1 AND part_id=$2 AND question_id=$3',[examId,partId,ids[i],i]);return get(examId,client);});}
function assertSameIds(current,next,message){if(!Array.isArray(next)||current.length!==next.length||new Set(next).size!==next.length||current.some(id=>!next.includes(id)))throw new HttpError(message,400,'INVALID_REORDER');}

async function validation(examId){const exam=await get(examId);const errors=[];if(!exam.title)errors.push('Đề thi chưa có tên.');if(!stripHtml(exam.introduction))errors.push('Đề thi chưa có giới thiệu và hướng dẫn làm bài.');if(exam.durationSeconds<=0)errors.push('Thời gian làm bài phải lớn hơn 0.');if(!exam.parts.length)errors.push('Đề thi phải có ít nhất một phần.');for(const part of exam.parts){if(!part.title)errors.push('Có phần thi chưa có tên.');if(!stripHtml(part.instruction))errors.push(`Phần “${part.title}” chưa có hướng dẫn làm bài.`);if(!part.questions.length)errors.push(`Phần “${part.title}” chưa có câu hỏi.`);}
  const rows=await db.query(`SELECT q.id,q.question_name,q.question_type,q.status,s.id sub_id,s.recording_duration_seconds,s.max_character_count,s.min_word_count,s.max_word_count,
    COUNT(o.id)::int option_count,COUNT(o.id) FILTER(WHERE o.is_correct)::int correct_count
    FROM exam_part_questions epq JOIN question_bank_questions q ON q.id=epq.question_id
    LEFT JOIN question_bank_sub_questions s ON s.question_id=q.id LEFT JOIN question_bank_sub_question_options o ON o.sub_question_id=s.id
    WHERE epq.exam_id=$1 GROUP BY q.id,s.id`,[examId]);
  const parentIds=new Set(rows.rows.map(r=>r.id));for(const part of exam.parts)for(const q of part.questions){if(q.status!=='ACTIVE')errors.push(`Câu hỏi “${q.questionName}” chưa hoạt động.`);if(!parentIds.has(q.id))errors.push(`Câu hỏi “${q.questionName}” chưa có câu hỏi con.`);}
  for(const row of rows.rows){if(row.question_type==='MCQ_SINGLE'&&(row.option_count<2||row.correct_count!==1))errors.push(`Câu hỏi con của “${row.question_name}” phải có ít nhất 2 đáp án và đúng 1 đáp án đúng.`);if(row.question_type==='RECORD'&&!row.recording_duration_seconds)errors.push(`Câu hỏi Record “${row.question_name}” thiếu thời gian ghi âm.`);if(row.question_type==='WRITING'&&(!row.max_character_count||!row.min_word_count))errors.push(`Câu hỏi Writing “${row.question_name}” thiếu giới hạn ký tự hoặc số từ tối thiểu.`);}
  return {valid:errors.length===0,errors,summary:{partCount:exam.partCount,parentQuestionCount:exam.parentQuestionCount,subQuestionCount:exam.subQuestionCount,totalPoints:exam.totalPoints}};}
function stripHtml(value){return String(value||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim();}

async function buildSnapshot(examId,client){const exam=await get(examId,client);const result={exam:{id:exam.id,title:exam.title,durationSeconds:exam.durationSeconds,pointsPerSubQuestion:exam.pointsPerSubQuestion},parts:[]};for(const part of exam.parts){const out={id:part.id,title:part.title,displayOrder:part.displayOrder,questions:[]};for(const q of part.questions){const detail=await client.query(`SELECT q.id,q.question_name,q.question_type,q.note,q.status,g.title group_name FROM question_bank_questions q JOIN question_groups g ON g.id=q.group_id WHERE q.id=$1`,[q.id]);const contents=await client.query(`SELECT id,title,content_html,script_html,translation_html,display_order FROM question_bank_contents WHERE question_id=$1 ORDER BY display_order`,[q.id]);const subs=await client.query(`SELECT id,content_id,prompt_html,hint,explanation,note,instruction_html,sentence_starters_html,preparation_duration_seconds,recording_duration_seconds,max_character_count,min_word_count,max_word_count,display_order FROM question_bank_sub_questions WHERE question_id=$1 ORDER BY display_order`,[q.id]);for(const sub of subs.rows){const opts=await client.query('SELECT id,option_key,option_text,is_correct,display_order FROM question_bank_sub_question_options WHERE sub_question_id=$1 ORDER BY display_order',[sub.id]);sub.options=opts.rows;}out.questions.push({...detail.rows[0],contents:contents.rows,subQuestions:subs.rows});}result.parts.push(out);}return result;}
async function activate(examId,userId){const checked=await validation(examId);if(!checked.valid)throw new HttpError('Đề thi chưa đủ điều kiện kích hoạt.',400,'EXAM_NOT_READY',checked.errors);return db.transaction(async client=>{const snapshot=await buildSnapshot(examId,client);const n=await client.query('SELECT COALESCE(MAX(version_number),0)+1 value FROM exam_versions WHERE exam_id=$1',[examId]);const v=await client.query(`INSERT INTO exam_versions(exam_id,version_number,snapshot,total_parent_questions,total_sub_questions,total_points,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,version_number`,[examId,n.rows[0].value,JSON.stringify(snapshot),checked.summary.parentQuestionCount,checked.summary.subQuestionCount,checked.summary.totalPoints,userId||null]);await client.query("UPDATE exams SET status='ACTIVE',active_version_id=$2,updated_by=$3,updated_at=CURRENT_TIMESTAMP,lock_version=lock_version+1 WHERE id=$1",[examId,v.rows[0].id,userId||null]);return {...await get(examId,client),activeVersion:Number(v.rows[0].version_number)};});}
async function deactivate(examId,userId){const exam=await get(examId);if(exam.status!=='ACTIVE')return exam;const activeEvent=await repo.findInProgressEvent(examId);if(activeEvent)throw new HttpError(`Không thể ngừng hoạt động vì đề thi đang được sử dụng trong kỳ thi “${activeEvent.name}”.`,409,'EXAM_EVENT_IN_PROGRESS');return repo.update(examId,{status:'INACTIVE'},userId);}

module.exports={list:repo.list,get,create,update,remove,duplicate,addPart,updatePart,removePart,reorderParts,addQuestions,removeQuestion,reorderQuestions,listAvailableQuestions,validation,activate,deactivate};
