import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpenText, Clock3, Download, Eye, Plus, RefreshCw, Save, Search, Sparkles, Trash2, X } from 'lucide-react';
import { exportKeyVocabHistory, exportKeyVocabPreview, generateKeyVocab, getKeyVocabDetail, getKeyVocabHistory, saveKeyVocab } from '../../../services/keyVocabService';
import './KeyVocabPage.css';
import './KeyVocabPolish.css';

const TYPES = ['Noun','Verb','Adjective','Adverb','Noun Phrase','Phrasal Verb','Adjective Phrase','Idiom','Verb Phrase','Preposition','Prepositional Phrase','Prefix','Suffix','Conjunction','Interjection','Phrase'];
const blankItem = () => ({ t: '', p: 'Noun', i: '', m: '' });

export default function KeyVocabPage({ showMsg, currentUser }) {
  const [tab, setTab] = useState('create'); const [passage, setPassage] = useState('');
  const [generating, setGenerating] = useState(false); const [saving, setSaving] = useState(false); const [exporting, setExporting] = useState(false); const [modal, setModal] = useState(null);
  const [history, setHistory] = useState([]); const [loadingHistory, setLoadingHistory] = useState(false);
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [meta, setMeta] = useState({ page: 1, total: 0, totalPages: 1 });
  const canGenerate = currentUser?.permissions?.some(value => ['key_vocab.generate','key_vocab.manage'].includes(value));
  const canSave = currentUser?.permissions?.includes('key_vocab.manage');

  const loadHistory = async () => { setLoadingHistory(true); try { const result = await getKeyVocabHistory({ page, limit: 10, search: search.trim() || undefined }); setHistory(result.data || []); setMeta(result.meta); } catch (error) { showMsg?.(error.response?.data?.error || 'Không thể tải lịch sử.', 'error'); } finally { setLoadingHistory(false); } };
  useEffect(() => { if (tab !== 'history') return undefined; const timer = setTimeout(loadHistory, 250); return () => clearTimeout(timer); }, [tab, page, search]);

  const generate = async () => { setGenerating(true); try { setModal({ mode: 'preview', ...(await generateKeyVocab(passage)) }); } catch (error) { showMsg?.(error.response?.data?.error || 'Không thể tạo Key Vocab.', 'error'); } finally { setGenerating(false); } };
  const updateItem = (index, field, value) => setModal(current => ({ ...current, vocabularies: current.vocabularies.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) }));
  const removeItem = index => setModal(current => ({ ...current, vocabularies: current.vocabularies.filter((_, itemIndex) => itemIndex !== index) }));
  const save = async () => { setSaving(true); try { await saveKeyVocab(modal); showMsg?.('Đã lưu Key Vocab vào lịch sử.', 'success'); setModal(null); setPassage(''); setTab('history'); setPage(1); } catch (error) { showMsg?.(error.response?.data?.error || 'Không thể lưu Key Vocab.', 'error'); } finally { setSaving(false); } };
  const exportExcel = async () => { setExporting(true); try { if (modal.mode === 'history') await exportKeyVocabHistory(modal.id); else await exportKeyVocabPreview(modal.vocabularies); showMsg?.('Đã xuất file theo template hệ thống.', 'success'); } catch (error) { showMsg?.(error.response?.data?.error || 'Không thể xuất dữ liệu.', 'error'); } finally { setExporting(false); } };
  const view = async id => { try { setModal({ mode: 'history', ...(await getKeyVocabDetail(id)) }); } catch (error) { showMsg?.(error.response?.data?.error || 'Không thể mở lịch sử.', 'error'); } };
  const wordCount = passage.trim() ? passage.trim().split(/\s+/).length : 0;

  return <div className="key-vocab-page">
    <header className="key-vocab-header"><div><span>CONTENT TOOLS · AI ACADEMY</span><h1>Gen Key Vocab</h1><p>Trích xuất từ vựng TOEIC giá trị cao, rà soát và lưu lại theo từng đoạn văn.</p></div><div className="key-vocab-tabs"><button className={tab === 'create' ? 'active' : ''} onClick={() => setTab('create')}><Sparkles />Tạo mới</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}><Clock3 />Lịch sử</button></div></header>
    {tab === 'create' ? <section className="key-vocab-workspace">
      <div className="key-vocab-editor"><header><div><BookOpenText /><span><strong>Đoạn văn nguồn</strong><small>AI chỉ chọn từ hoặc cụm từ xuất hiện trong nội dung này.</small></span></div><em>{wordCount} từ · {passage.length.toLocaleString('vi-VN')} ký tự</em></header><textarea value={passage} onChange={event => setPassage(event.target.value)} maxLength={20000} placeholder="Dán đoạn văn TOEIC, email công việc, thông báo, báo cáo hoặc nội dung Reading vào đây…" /><footer><span>Tối thiểu 80 ký tự</span><button disabled={!canGenerate || passage.trim().length < 80 || generating} onClick={generate}>{generating ? <RefreshCw className="spin" /> : <Sparkles />}{generating ? 'AI Academy đang xử lý…' : 'Gen Key Vocab với AI Academy'}</button></footer></div>
      <aside><span><Sparkles /></span><h2>Quy trình kiểm soát</h2><ol><li><b>01</b><div><strong>AI trích xuất</strong><small>Phân tích theo chuẩn TOEIC và danh mục loại từ hệ thống.</small></div></li><li><b>02</b><div><strong>Rà soát tại popup</strong><small>Chỉnh từ, loại từ, IPA và nghĩa tiếng Việt trước khi lưu.</small></div></li><li><b>03</b><div><strong>Lưu lịch sử</strong><small>Mỗi lần lưu gắn với đoạn văn nguồn và người thực hiện.</small></div></li></ol></aside>
    </section> : <section className="key-vocab-history"><header><div><h2>Lịch sử Key Vocab</h2><p>{meta.total || 0} kết quả đã lưu</p></div><label><Search /><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Tìm theo nội dung đoạn văn…" /></label></header>{loadingHistory ? <div className="key-vocab-empty"><RefreshCw className="spin" />Đang tải lịch sử…</div> : !history.length ? <div className="key-vocab-empty"><Clock3 />Chưa có lịch sử phù hợp.</div> : <div className="key-vocab-table-wrap"><table><thead><tr><th>Đoạn văn</th><th>Số từ vựng</th><th>Người tạo</th><th>Thời gian</th><th /></tr></thead><tbody>{history.map(item => <tr key={item.id}><td><strong>{item.passage}</strong></td><td><span>{item.item_count} từ</span></td><td>{item.created_by_name}</td><td>{new Date(item.created_at).toLocaleString('vi-VN')}</td><td><button onClick={() => view(item.id)}><Eye />Xem</button></td></tr>)}</tbody></table></div>}<footer><span>Trang {meta.page}/{meta.totalPages}</span><div><button disabled={page <= 1} onClick={() => setPage(value => value - 1)}><ArrowLeft /></button><button disabled={page >= meta.totalPages} onClick={() => setPage(value => value + 1)}><ArrowRight /></button></div></footer></section>}
    {modal && <div className={`key-vocab-modal-backdrop ${modal.mode}`}><div className={`key-vocab-modal ${modal.mode}`}><header><div><span><Sparkles /></span><div><h2>{modal.mode === 'history' ? 'Chi tiết Key Vocab' : 'Rà soát kết quả AI'}</h2><p>{modal.vocabularies.length} mục từ vựng · {modal.mode === 'history' ? `Được lưu bởi ${modal.created_by_name || 'người dùng hệ thống'}` : 'Có thể chỉnh sửa trước khi lưu'}</p></div></div><button onClick={() => setModal(null)}><X /></button></header><div className="key-vocab-modal-body"><section className="key-vocab-source"><div><label>Đoạn văn nguồn</label>{modal.mode === 'history' && <time>{new Date(modal.created_at).toLocaleString('vi-VN')}</time>}</div><p>{modal.passage}</p></section><section className="key-vocab-list"><header><div><strong>Danh sách từ vựng</strong><span>{modal.vocabularies.length} mục đã chọn</span></div>{modal.mode !== 'history' && <button onClick={() => setModal(current => ({ ...current, vocabularies: [...current.vocabularies, blankItem()] }))}><Plus />Thêm từ</button>}</header>{modal.mode === 'history' ? <div className="key-vocab-read-grid">{modal.vocabularies.map((item, index) => <article className="key-vocab-read-card" key={`${item.t}-${index}`}><div className="key-vocab-read-index">{String(index + 1).padStart(2, '0')}</div><div className="key-vocab-read-main"><div><h3>{item.t}</h3><span>{item.p}</span></div><code>{item.i}</code><p>{item.m}</p></div></article>)}</div> : modal.vocabularies.map((item, index) => <article className="key-vocab-edit-row" key={index}><b>{String(index + 1).padStart(2, '0')}</b><label>Từ / cụm từ<input value={item.t} onChange={event => updateItem(index, 't', event.target.value)} /></label><label>Loại từ<select value={item.p} onChange={event => updateItem(index, 'p', event.target.value)}>{TYPES.map(type => <option key={type}>{type}</option>)}</select></label><label>Phát âm<input value={item.i} onChange={event => updateItem(index, 'i', event.target.value)} /></label><label>Nghĩa tiếng Việt<input value={item.m} onChange={event => updateItem(index, 'm', event.target.value)} /></label><button className="remove" onClick={() => removeItem(index)} title="Xóa từ"><Trash2 /></button></article>)}</section></div><footer><button className="secondary" onClick={() => setModal(null)}>{modal.mode === 'history' ? 'Đóng' : 'Hủy'}</button><button className="export" disabled={exporting || !modal.vocabularies.length} onClick={exportExcel}>{exporting ? <RefreshCw className="spin" /> : <Download />}{exporting ? 'Đang xuất…' : 'Xuất dữ liệu'}</button>{modal.mode !== 'history' && canSave && <button className="primary" disabled={saving || !modal.vocabularies.length} onClick={save}>{saving ? <RefreshCw className="spin" /> : <Save />}{saving ? 'Đang lưu…' : 'Lưu vào lịch sử'}</button>}</footer></div></div>}
  </div>;
}
